version: 2
updates:
  - package-ecosystem: cargo
    directory: /engine
    schedule:
      interval: weekly
      day: monday
      time: "06:00"
      timezone: Asia/Taipei
    open-pull-requests-limit: 5
    labels:
      - dependencies
      - rust
    groups:
      cargo-minor-and-patch:
        patterns:
          - "*"
        update-types:
          - minor
          - patch

  - package-ecosystem: cargo
    directory: /windows
    schedule:
      interval: weekly
      day: monday
      time: "06:00"
      timezone: Asia/Taipei
    open-pull-requests-limit: 5
    labels:
      - dependencies
      - rust
    groups:
      cargo-minor-and-patch:
        patterns:
          - "*"
        update-types:
          - minor
          - patch

  - package-ecosystem: gradle
    directory: /android
    schedule:
      interval: weekly
      day: monday
      time: "06:00"
      timezone: Asia/Taipei
    open-pull-requests-limit: 5
    labels:
      - dependencies
      - android
    groups:
      gradle-minor-and-patch:
        patterns:
          - "*"
        update-types:
          - minor
          - patch

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "06:00"
      timezone: Asia/Taipei
    open-pull-requests-limit: 3
    labels:
      - dependencies
      - github-actions
    groups:
      gh-actions-minor-and-patch:
        patterns:
          - "*"
        update-types:
          - minor
          - patch
