// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: nextword.proto
// Protobuf Java Version: 4.27.5

package com.siansiansu.taigikeyboard.engine.proto;

/**
 * Protobuf type {@code taigi.engine.AssociationPair}
 */
public  final class AssociationPair extends
    com.google.protobuf.GeneratedMessageLite<
        AssociationPair, AssociationPair.Builder> implements
    // @@protoc_insertion_point(message_implements:taigi.engine.AssociationPair)
    AssociationPairOrBuilder {
  private AssociationPair() {
    prev_ = "";
    prevTl_ = "";
    next_ = "";
    nextTl_ = "";
  }
  public static final int PREV_FIELD_NUMBER = 1;
  private java.lang.String prev_;
  /**
   * <code>string prev = 1;</code>
   * @return The prev.
   */
  @java.lang.Override
  public java.lang.String getPrev() {
    return prev_;
  }
  /**
   * <code>string prev = 1;</code>
   * @return The bytes for prev.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getPrevBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(prev_);
  }
  /**
   * <code>string prev = 1;</code>
   * @param value The prev to set.
   */
  private void setPrev(
      java.lang.String value) {
    java.lang.Class<?> valueClass = value.getClass();

    prev_ = value;
  }
  /**
   * <code>string prev = 1;</code>
   */
  private void clearPrev() {

    prev_ = getDefaultInstance().getPrev();
  }
  /**
   * <code>string prev = 1;</code>
   * @param value The bytes for prev to set.
   */
  private void setPrevBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    prev_ = value.toStringUtf8();

  }

  public static final int PREV_TL_FIELD_NUMBER = 2;
  private java.lang.String prevTl_;
  /**
   * <code>string prev_tl = 2;</code>
   * @return The prevTl.
   */
  @java.lang.Override
  public java.lang.String getPrevTl() {
    return prevTl_;
  }
  /**
   * <code>string prev_tl = 2;</code>
   * @return The bytes for prevTl.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getPrevTlBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(prevTl_);
  }
  /**
   * <code>string prev_tl = 2;</code>
   * @param value The prevTl to set.
   */
  private void setPrevTl(
      java.lang.String value) {
    java.lang.Class<?> valueClass = value.getClass();

    prevTl_ = value;
  }
  /**
   * <code>string prev_tl = 2;</code>
   */
  private void clearPrevTl() {

    prevTl_ = getDefaultInstance().getPrevTl();
  }
  /**
   * <code>string prev_tl = 2;</code>
   * @param value The bytes for prevTl to set.
   */
  private void setPrevTlBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    prevTl_ = value.toStringUtf8();

  }

  public static final int NEXT_FIELD_NUMBER = 3;
  private java.lang.String next_;
  /**
   * <code>string next = 3;</code>
   * @return The next.
   */
  @java.lang.Override
  public java.lang.String getNext() {
    return next_;
  }
  /**
   * <code>string next = 3;</code>
   * @return The bytes for next.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getNextBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(next_);
  }
  /**
   * <code>string next = 3;</code>
   * @param value The next to set.
   */
  private void setNext(
      java.lang.String value) {
    java.lang.Class<?> valueClass = value.getClass();

    next_ = value;
  }
  /**
   * <code>string next = 3;</code>
   */
  private void clearNext() {

    next_ = getDefaultInstance().getNext();
  }
  /**
   * <code>string next = 3;</code>
   * @param value The bytes for next to set.
   */
  private void setNextBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    next_ = value.toStringUtf8();

  }

  public static final int NEXT_TL_FIELD_NUMBER = 4;
  private java.lang.String nextTl_;
  /**
   * <code>string next_tl = 4;</code>
   * @return The nextTl.
   */
  @java.lang.Override
  public java.lang.String getNextTl() {
    return nextTl_;
  }
  /**
   * <code>string next_tl = 4;</code>
   * @return The bytes for nextTl.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getNextTlBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(nextTl_);
  }
  /**
   * <code>string next_tl = 4;</code>
   * @param value The nextTl to set.
   */
  private void setNextTl(
      java.lang.String value) {
    java.lang.Class<?> valueClass = value.getClass();

    nextTl_ = value;
  }
  /**
   * <code>string next_tl = 4;</code>
   */
  private void clearNextTl() {

    nextTl_ = getDefaultInstance().getNextTl();
  }
  /**
   * <code>string next_tl = 4;</code>
   * @param value The bytes for nextTl to set.
   */
  private void setNextTlBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    nextTl_ = value.toStringUtf8();

  }

  public static com.siansiansu.taigikeyboard.engine.proto.AssociationPair parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.siansiansu.taigikeyboard.engine.proto.AssociationPair parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.siansiansu.taigikeyboard.engine.proto.AssociationPair parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.siansiansu.taigikeyboard.engine.proto.AssociationPair parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.siansiansu.taigikeyboard.engine.proto.AssociationPair parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.siansiansu.taigikeyboard.engine.proto.AssociationPair parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.siansiansu.taigikeyboard.engine.proto.AssociationPair parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.siansiansu.taigikeyboard.engine.proto.AssociationPair parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static com.siansiansu.taigikeyboard.engine.proto.AssociationPair parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }

  public static com.siansiansu.taigikeyboard.engine.proto.AssociationPair parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static com.siansiansu.taigikeyboard.engine.proto.AssociationPair parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.siansiansu.taigikeyboard.engine.proto.AssociationPair parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }
  public static Builder newBuilder(com.siansiansu.taigikeyboard.engine.proto.AssociationPair prototype) {
    return DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * Protobuf type {@code taigi.engine.AssociationPair}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        com.siansiansu.taigikeyboard.engine.proto.AssociationPair, Builder> implements
      // @@protoc_insertion_point(builder_implements:taigi.engine.AssociationPair)
      com.siansiansu.taigikeyboard.engine.proto.AssociationPairOrBuilder {
    // Construct using com.siansiansu.taigikeyboard.engine.proto.AssociationPair.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <code>string prev = 1;</code>
     * @return The prev.
     */
    @java.lang.Override
    public java.lang.String getPrev() {
      return instance.getPrev();
    }
    /**
     * <code>string prev = 1;</code>
     * @return The bytes for prev.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getPrevBytes() {
      return instance.getPrevBytes();
    }
    /**
     * <code>string prev = 1;</code>
     * @param value The prev to set.
     * @return This builder for chaining.
     */
    public Builder setPrev(
        java.lang.String value) {
      copyOnWrite();
      instance.setPrev(value);
      return this;
    }
    /**
     * <code>string prev = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearPrev() {
      copyOnWrite();
      instance.clearPrev();
      return this;
    }
    /**
     * <code>string prev = 1;</code>
     * @param value The bytes for prev to set.
     * @return This builder for chaining.
     */
    public Builder setPrevBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setPrevBytes(value);
      return this;
    }

    /**
     * <code>string prev_tl = 2;</code>
     * @return The prevTl.
     */
    @java.lang.Override
    public java.lang.String getPrevTl() {
      return instance.getPrevTl();
    }
    /**
     * <code>string prev_tl = 2;</code>
     * @return The bytes for prevTl.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getPrevTlBytes() {
      return instance.getPrevTlBytes();
    }
    /**
     * <code>string prev_tl = 2;</code>
     * @param value The prevTl to set.
     * @return This builder for chaining.
     */
    public Builder setPrevTl(
        java.lang.String value) {
      copyOnWrite();
      instance.setPrevTl(value);
      return this;
    }
    /**
     * <code>string prev_tl = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearPrevTl() {
      copyOnWrite();
      instance.clearPrevTl();
      return this;
    }
    /**
     * <code>string prev_tl = 2;</code>
     * @param value The bytes for prevTl to set.
     * @return This builder for chaining.
     */
    public Builder setPrevTlBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setPrevTlBytes(value);
      return this;
    }

    /**
     * <code>string next = 3;</code>
     * @return The next.
     */
    @java.lang.Override
    public java.lang.String getNext() {
      return instance.getNext();
    }
    /**
     * <code>string next = 3;</code>
     * @return The bytes for next.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getNextBytes() {
      return instance.getNextBytes();
    }
    /**
     * <code>string next = 3;</code>
     * @param value The next to set.
     * @return This builder for chaining.
     */
    public Builder setNext(
        java.lang.String value) {
      copyOnWrite();
      instance.setNext(value);
      return this;
    }
    /**
     * <code>string next = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearNext() {
      copyOnWrite();
      instance.clearNext();
      return this;
    }
    /**
     * <code>string next = 3;</code>
     * @param value The bytes for next to set.
     * @return This builder for chaining.
     */
    public Builder setNextBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setNextBytes(value);
      return this;
    }

    /**
     * <code>string next_tl = 4;</code>
     * @return The nextTl.
     */
    @java.lang.Override
    public java.lang.String getNextTl() {
      return instance.getNextTl();
    }
    /**
     * <code>string next_tl = 4;</code>
     * @return The bytes for nextTl.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getNextTlBytes() {
      return instance.getNextTlBytes();
    }
    /**
     * <code>string next_tl = 4;</code>
     * @param value The nextTl to set.
     * @return This builder for chaining.
     */
    public Builder setNextTl(
        java.lang.String value) {
      copyOnWrite();
      instance.setNextTl(value);
      return this;
    }
    /**
     * <code>string next_tl = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearNextTl() {
      copyOnWrite();
      instance.clearNextTl();
      return this;
    }
    /**
     * <code>string next_tl = 4;</code>
     * @param value The bytes for nextTl to set.
     * @return This builder for chaining.
     */
    public Builder setNextTlBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setNextTlBytes(value);
      return this;
    }

    // @@protoc_insertion_point(builder_scope:taigi.engine.AssociationPair)
  }
  @java.lang.Override
  @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
  protected final java.lang.Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      java.lang.Object arg0, java.lang.Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new com.siansiansu.taigikeyboard.engine.proto.AssociationPair();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
          java.lang.Object[] objects = new java.lang.Object[] {
            "prev_",
            "prevTl_",
            "next_",
            "nextTl_",
          };
          java.lang.String info =
              "\u0000\u0004\u0000\u0000\u0001\u0004\u0004\u0000\u0000\u0000\u0001\u0208\u0002\u0208" +
              "\u0003\u0208\u0004\u0208";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      // fall through
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<com.siansiansu.taigikeyboard.engine.proto.AssociationPair> parser = PARSER;
        if (parser == null) {
          synchronized (com.siansiansu.taigikeyboard.engine.proto.AssociationPair.class) {
            parser = PARSER;
            if (parser == null) {
              parser =
                  new DefaultInstanceBasedParser<com.siansiansu.taigikeyboard.engine.proto.AssociationPair>(
                      DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
    }
    case GET_MEMOIZED_IS_INITIALIZED: {
      return (byte) 1;
    }
    case SET_MEMOIZED_IS_INITIALIZED: {
      return null;
    }
    }
    throw new UnsupportedOperationException();
  }


  // @@protoc_insertion_point(class_scope:taigi.engine.AssociationPair)
  private static final com.siansiansu.taigikeyboard.engine.proto.AssociationPair DEFAULT_INSTANCE;
  static {
    AssociationPair defaultInstance = new AssociationPair();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
      AssociationPair.class, defaultInstance);
  }

  public static com.siansiansu.taigikeyboard.engine.proto.AssociationPair getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<AssociationPair> PARSER;

  public static com.google.protobuf.Parser<AssociationPair> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}
