// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: user_data.proto
// Protobuf Java Version: 4.36.2

package com.siansiansu.taigikeyboard.engine.proto;

/**
 * <pre>
 * Rows merged per store; all 0 when refused.
 * </pre>
 *
 * Protobuf type {@code taigi.engine.BackupImported}
 */
@com.google.protobuf.Generated
public  final class BackupImported extends
    com.google.protobuf.GeneratedMessageLite<
        BackupImported, BackupImported.Builder> implements
    // @@protoc_insertion_point(message_implements:taigi.engine.BackupImported)
    BackupImportedOrBuilder {
  private BackupImported() {
  }
  public static final int REFUSAL_FIELD_NUMBER = 1;
  private int refusal_;
  /**
   * <code>.taigi.engine.BackupRefusal refusal = 1;</code>
   * @return The enum numeric value on the wire for refusal.
   */
  @java.lang.Override
  public int getRefusalValue() {
    return refusal_;
  }
  /**
   * <code>.taigi.engine.BackupRefusal refusal = 1;</code>
   * @return The refusal.
   */
  @java.lang.Override
  public com.siansiansu.taigikeyboard.engine.proto.BackupRefusal getRefusal() {
    com.siansiansu.taigikeyboard.engine.proto.BackupRefusal result = com.siansiansu.taigikeyboard.engine.proto.BackupRefusal.forNumber(refusal_);
    return result == null ? com.siansiansu.taigikeyboard.engine.proto.BackupRefusal.UNRECOGNIZED : result;
  }
  /**
   * <code>.taigi.engine.BackupRefusal refusal = 1;</code>
   * @param value The enum numeric value on the wire for refusal to set.
   */
  private void setRefusalValue(int value) {
      refusal_ = value;
  }
  /**
   * <code>.taigi.engine.BackupRefusal refusal = 1;</code>
   * @param value The refusal to set.
   * @throws IllegalArgumentException if UNRECOGNIZED is provided.
   */
  private void setRefusal(com.siansiansu.taigikeyboard.engine.proto.BackupRefusal value) {
    refusal_ = value.getNumber();

  }
  /**
   * <code>.taigi.engine.BackupRefusal refusal = 1;</code>
   */
  private void clearRefusal() {

    refusal_ = 0;
  }

  public static final int CUSTOM_DICTIONARY_FIELD_NUMBER = 2;
  private int customDictionary_;
  /**
   * <code>uint32 custom_dictionary = 2;</code>
   * @return The customDictionary.
   */
  @java.lang.Override
  public int getCustomDictionary() {
    return customDictionary_;
  }
  /**
   * <code>uint32 custom_dictionary = 2;</code>
   * @param value The customDictionary to set.
   */
  private void setCustomDictionary(int value) {

    customDictionary_ = value;
  }
  /**
   * <code>uint32 custom_dictionary = 2;</code>
   */
  private void clearCustomDictionary() {

    customDictionary_ = 0;
  }

  public static final int FREQUENCY_FIELD_NUMBER = 3;
  private int frequency_;
  /**
   * <code>uint32 frequency = 3;</code>
   * @return The frequency.
   */
  @java.lang.Override
  public int getFrequency() {
    return frequency_;
  }
  /**
   * <code>uint32 frequency = 3;</code>
   * @param value The frequency to set.
   */
  private void setFrequency(int value) {

    frequency_ = value;
  }
  /**
   * <code>uint32 frequency = 3;</code>
   */
  private void clearFrequency() {

    frequency_ = 0;
  }

  public static final int ASSOCIATION_FIELD_NUMBER = 4;
  private int association_;
  /**
   * <code>uint32 association = 4;</code>
   * @return The association.
   */
  @java.lang.Override
  public int getAssociation() {
    return association_;
  }
  /**
   * <code>uint32 association = 4;</code>
   * @param value The association to set.
   */
  private void setAssociation(int value) {

    association_ = value;
  }
  /**
   * <code>uint32 association = 4;</code>
   */
  private void clearAssociation() {

    association_ = 0;
  }

  public static com.siansiansu.taigikeyboard.engine.proto.BackupImported parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.siansiansu.taigikeyboard.engine.proto.BackupImported parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.siansiansu.taigikeyboard.engine.proto.BackupImported parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.siansiansu.taigikeyboard.engine.proto.BackupImported parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.siansiansu.taigikeyboard.engine.proto.BackupImported parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.siansiansu.taigikeyboard.engine.proto.BackupImported parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.siansiansu.taigikeyboard.engine.proto.BackupImported parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.siansiansu.taigikeyboard.engine.proto.BackupImported parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static com.siansiansu.taigikeyboard.engine.proto.BackupImported parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }

  public static com.siansiansu.taigikeyboard.engine.proto.BackupImported parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static com.siansiansu.taigikeyboard.engine.proto.BackupImported parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.siansiansu.taigikeyboard.engine.proto.BackupImported parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }
  public static Builder newBuilder(com.siansiansu.taigikeyboard.engine.proto.BackupImported prototype) {
    return DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * <pre>
   * Rows merged per store; all 0 when refused.
   * </pre>
   *
   * Protobuf type {@code taigi.engine.BackupImported}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        com.siansiansu.taigikeyboard.engine.proto.BackupImported, Builder> implements
      // @@protoc_insertion_point(builder_implements:taigi.engine.BackupImported)
      com.siansiansu.taigikeyboard.engine.proto.BackupImportedOrBuilder {
    // Construct using com.siansiansu.taigikeyboard.engine.proto.BackupImported.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <code>.taigi.engine.BackupRefusal refusal = 1;</code>
     * @return The enum numeric value on the wire for refusal.
     */
    @java.lang.Override
    public int getRefusalValue() {
      return instance.getRefusalValue();
    }
    /**
     * <code>.taigi.engine.BackupRefusal refusal = 1;</code>
     * @param value The refusal to set.
     * @throws IllegalArgumentException if UNRECOGNIZED is provided.
     * @return This builder for chaining.
     */
    public Builder setRefusalValue(int value) {
      copyOnWrite();
      instance.setRefusalValue(value);
      return this;
    }
    /**
     * <code>.taigi.engine.BackupRefusal refusal = 1;</code>
     * @return The refusal.
     */
    @java.lang.Override
    public com.siansiansu.taigikeyboard.engine.proto.BackupRefusal getRefusal() {
      return instance.getRefusal();
    }
    /**
     * <code>.taigi.engine.BackupRefusal refusal = 1;</code>
     * @param value The enum numeric value on the wire for refusal to set.
     * @return This builder for chaining.
     */
    public Builder setRefusal(com.siansiansu.taigikeyboard.engine.proto.BackupRefusal value) {
      copyOnWrite();
      instance.setRefusal(value);
      return this;
    }
    /**
     * <code>.taigi.engine.BackupRefusal refusal = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearRefusal() {
      copyOnWrite();
      instance.clearRefusal();
      return this;
    }

    /**
     * <code>uint32 custom_dictionary = 2;</code>
     * @return The customDictionary.
     */
    @java.lang.Override
    public int getCustomDictionary() {
      return instance.getCustomDictionary();
    }
    /**
     * <code>uint32 custom_dictionary = 2;</code>
     * @param value The customDictionary to set.
     * @return This builder for chaining.
     */
    public Builder setCustomDictionary(int value) {
      copyOnWrite();
      instance.setCustomDictionary(value);
      return this;
    }
    /**
     * <code>uint32 custom_dictionary = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearCustomDictionary() {
      copyOnWrite();
      instance.clearCustomDictionary();
      return this;
    }

    /**
     * <code>uint32 frequency = 3;</code>
     * @return The frequency.
     */
    @java.lang.Override
    public int getFrequency() {
      return instance.getFrequency();
    }
    /**
     * <code>uint32 frequency = 3;</code>
     * @param value The frequency to set.
     * @return This builder for chaining.
     */
    public Builder setFrequency(int value) {
      copyOnWrite();
      instance.setFrequency(value);
      return this;
    }
    /**
     * <code>uint32 frequency = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearFrequency() {
      copyOnWrite();
      instance.clearFrequency();
      return this;
    }

    /**
     * <code>uint32 association = 4;</code>
     * @return The association.
     */
    @java.lang.Override
    public int getAssociation() {
      return instance.getAssociation();
    }
    /**
     * <code>uint32 association = 4;</code>
     * @param value The association to set.
     * @return This builder for chaining.
     */
    public Builder setAssociation(int value) {
      copyOnWrite();
      instance.setAssociation(value);
      return this;
    }
    /**
     * <code>uint32 association = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearAssociation() {
      copyOnWrite();
      instance.clearAssociation();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:taigi.engine.BackupImported)
  }
  @java.lang.Override
  @java.lang.SuppressWarnings({"ThrowNull"})
  protected final java.lang.Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      java.lang.Object arg0, java.lang.Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new com.siansiansu.taigikeyboard.engine.proto.BackupImported();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
          java.lang.Object[] objects = new java.lang.Object[] {
            "refusal_",
            "customDictionary_",
            "frequency_",
            "association_",
          };
          java.lang.String info =
              "\u0000\u0004\u0000\u0000\u0001\u0004\u0004\u0000\u0000\u0000\u0001\f\u0002\u000b" +
              "\u0003\u000b\u0004\u000b";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<com.siansiansu.taigikeyboard.engine.proto.BackupImported> parser = PARSER;
        if (parser == null) {
          synchronized (com.siansiansu.taigikeyboard.engine.proto.BackupImported.class) {
            parser = PARSER;
            if (parser == null) {
              parser =
                  new DefaultInstanceBasedParser<com.siansiansu.taigikeyboard.engine.proto.BackupImported>(
                      DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      // SET_MEMOIZED_IS_INITIALIZED is never called for this message.
      // So it can do anything. Combine with default case for smaller codegen.
      case SET_MEMOIZED_IS_INITIALIZED:
    }
    // Should never happen. Generates tight code to throw an exception.
    throw null;
  }


  // @@protoc_insertion_point(class_scope:taigi.engine.BackupImported)
  private static final com.siansiansu.taigikeyboard.engine.proto.BackupImported DEFAULT_INSTANCE;
  static {
    BackupImported defaultInstance = new BackupImported();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
      BackupImported.class, defaultInstance);
  }

  public static com.siansiansu.taigikeyboard.engine.proto.BackupImported getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<BackupImported> PARSER;

  public static com.google.protobuf.Parser<BackupImported> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}
