// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: phonetics.proto
// Protobuf Java Version: 4.27.5

package com.siansiansu.taigikeyboard.engine.proto;

public interface BoolResultOrBuilder extends
    // @@protoc_insertion_point(interface_extends:taigi.engine.BoolResult)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>bool value = 1;</code>
   * @return The value.
   */
  boolean getValue();
}
