// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: composing.proto
// Protobuf Java Version: 4.27.5

package com.siansiansu.taigikeyboard.engine.proto;

public interface ComposingResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:taigi.engine.ComposingResponse)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>.taigi.engine.ComposingResponse.Preedit preedit = 1;</code>
   * @return Whether the preedit field is set.
   */
  boolean hasPreedit();
  /**
   * <code>.taigi.engine.ComposingResponse.Preedit preedit = 1;</code>
   * @return The preedit.
   */
  com.siansiansu.taigikeyboard.engine.proto.ComposingResponse.Preedit getPreedit();

  /**
   * <pre>
   * ordered side effects; prost preserves order
   * </pre>
   *
   * <code>repeated .taigi.engine.Effect effect = 2;</code>
   */
  java.util.List<com.siansiansu.taigikeyboard.engine.proto.Effect>
      getEffectList();
  /**
   * <pre>
   * ordered side effects; prost preserves order
   * </pre>
   *
   * <code>repeated .taigi.engine.Effect effect = 2;</code>
   */
  com.siansiansu.taigikeyboard.engine.proto.Effect getEffect(int index);
  /**
   * <pre>
   * ordered side effects; prost preserves order
   * </pre>
   *
   * <code>repeated .taigi.engine.Effect effect = 2;</code>
   */
  int getEffectCount();

  /**
   * <pre>
   * -1 idle, 0 fresh, preserved on ReplaceLast
   * </pre>
   *
   * <code>int32 selected_candidate_index = 3;</code>
   * @return The selectedCandidateIndex.
   */
  int getSelectedCandidateIndex();

  /**
   * <pre>
   * mirrors `state.isComposing`
   * </pre>
   *
   * <code>bool is_composing = 4;</code>
   * @return The isComposing.
   */
  boolean getIsComposing();
}
