// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: phonetics.proto
// Protobuf Java Version: 4.35.1

package com.siansiansu.taigikeyboard.engine.proto;

@com.google.protobuf.Generated
public interface CustomSearchKeysResultOrBuilder extends
    // @@protoc_insertion_point(interface_extends:taigi.engine.CustomSearchKeysResult)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>repeated .taigi.engine.CustomSearchKey keys = 1;</code>
   */
  java.util.List<com.siansiansu.taigikeyboard.engine.proto.CustomSearchKey>
      getKeysList();
  /**
   * <code>repeated .taigi.engine.CustomSearchKey keys = 1;</code>
   */
  com.siansiansu.taigikeyboard.engine.proto.CustomSearchKey getKeys(int index);
  /**
   * <code>repeated .taigi.engine.CustomSearchKey keys = 1;</code>
   */
  int getKeysCount();
}
