// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: user_data.proto
// Protobuf Java Version: 4.36.2

package com.siansiansu.taigikeyboard.engine.proto;

/**
 * Protobuf type {@code taigi.engine.CustomEntrySaved}
 */
@com.google.protobuf.Generated
public  final class CustomEntrySaved extends
    com.google.protobuf.GeneratedMessageLite<
        CustomEntrySaved, CustomEntrySaved.Builder> implements
    // @@protoc_insertion_point(message_implements:taigi.engine.CustomEntrySaved)
    CustomEntrySavedOrBuilder {
  private CustomEntrySaved() {
  }
  private int bitField0_;
  public static final int REFUSAL_FIELD_NUMBER = 1;
  private int refusal_;
  /**
   * <code>.taigi.engine.CustomDictionaryRefusal refusal = 1;</code>
   * @return The enum numeric value on the wire for refusal.
   */
  @java.lang.Override
  public int getRefusalValue() {
    return refusal_;
  }
  /**
   * <code>.taigi.engine.CustomDictionaryRefusal refusal = 1;</code>
   * @return The refusal.
   */
  @java.lang.Override
  public com.siansiansu.taigikeyboard.engine.proto.CustomDictionaryRefusal getRefusal() {
    com.siansiansu.taigikeyboard.engine.proto.CustomDictionaryRefusal result = com.siansiansu.taigikeyboard.engine.proto.CustomDictionaryRefusal.forNumber(refusal_);
    return result == null ? com.siansiansu.taigikeyboard.engine.proto.CustomDictionaryRefusal.UNRECOGNIZED : result;
  }
  /**
   * <code>.taigi.engine.CustomDictionaryRefusal refusal = 1;</code>
   * @param value The enum numeric value on the wire for refusal to set.
   */
  private void setRefusalValue(int value) {
      refusal_ = value;
  }
  /**
   * <code>.taigi.engine.CustomDictionaryRefusal refusal = 1;</code>
   * @param value The refusal to set.
   * @throws IllegalArgumentException if UNRECOGNIZED is provided.
   */
  private void setRefusal(com.siansiansu.taigikeyboard.engine.proto.CustomDictionaryRefusal value) {
    refusal_ = value.getNumber();

  }
  /**
   * <code>.taigi.engine.CustomDictionaryRefusal refusal = 1;</code>
   */
  private void clearRefusal() {

    refusal_ = 0;
  }

  public static final int ENTRY_FIELD_NUMBER = 2;
  private com.siansiansu.taigikeyboard.engine.proto.CustomDictionaryEntry entry_;
  /**
   * <pre>
   * The stored row; absent when refused.
   * </pre>
   *
   * <code>optional .taigi.engine.CustomDictionaryEntry entry = 2;</code>
   */
  @java.lang.Override
  public boolean hasEntry() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <pre>
   * The stored row; absent when refused.
   * </pre>
   *
   * <code>optional .taigi.engine.CustomDictionaryEntry entry = 2;</code>
   */
  @java.lang.Override
  public com.siansiansu.taigikeyboard.engine.proto.CustomDictionaryEntry getEntry() {
    return entry_ == null ? com.siansiansu.taigikeyboard.engine.proto.CustomDictionaryEntry.getDefaultInstance() : entry_;
  }
  /**
   * <pre>
   * The stored row; absent when refused.
   * </pre>
   *
   * <code>optional .taigi.engine.CustomDictionaryEntry entry = 2;</code>
   */
  private void setEntry(com.siansiansu.taigikeyboard.engine.proto.CustomDictionaryEntry value) {
    java.util.Objects.requireNonNull(value);
    entry_ = value;
    bitField0_ |= 0x00000001;
  }
  /**
   * <pre>
   * The stored row; absent when refused.
   * </pre>
   *
   * <code>optional .taigi.engine.CustomDictionaryEntry entry = 2;</code>
   */
  @java.lang.SuppressWarnings("ReferenceEquality")
  private void mergeEntry(com.siansiansu.taigikeyboard.engine.proto.CustomDictionaryEntry value) {
    java.util.Objects.requireNonNull(value);
    if (entry_ != null &&
        entry_ != com.siansiansu.taigikeyboard.engine.proto.CustomDictionaryEntry.getDefaultInstance()) {
      entry_ =
        com.siansiansu.taigikeyboard.engine.proto.CustomDictionaryEntry.newBuilder(entry_).mergeFrom(value).buildPartial();
    } else {
      entry_ = value;
    }
    bitField0_ |= 0x00000001;
  }
  /**
   * <pre>
   * The stored row; absent when refused.
   * </pre>
   *
   * <code>optional .taigi.engine.CustomDictionaryEntry entry = 2;</code>
   */
  private void clearEntry() {
    entry_ = null;
    bitField0_ = (bitField0_ & ~0x00000001);
  }

  public static com.siansiansu.taigikeyboard.engine.proto.CustomEntrySaved parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.siansiansu.taigikeyboard.engine.proto.CustomEntrySaved parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.siansiansu.taigikeyboard.engine.proto.CustomEntrySaved parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.siansiansu.taigikeyboard.engine.proto.CustomEntrySaved parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.siansiansu.taigikeyboard.engine.proto.CustomEntrySaved parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.siansiansu.taigikeyboard.engine.proto.CustomEntrySaved parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.siansiansu.taigikeyboard.engine.proto.CustomEntrySaved parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.siansiansu.taigikeyboard.engine.proto.CustomEntrySaved parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static com.siansiansu.taigikeyboard.engine.proto.CustomEntrySaved parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }

  public static com.siansiansu.taigikeyboard.engine.proto.CustomEntrySaved parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static com.siansiansu.taigikeyboard.engine.proto.CustomEntrySaved parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.siansiansu.taigikeyboard.engine.proto.CustomEntrySaved parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }
  public static Builder newBuilder(com.siansiansu.taigikeyboard.engine.proto.CustomEntrySaved prototype) {
    return DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * Protobuf type {@code taigi.engine.CustomEntrySaved}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        com.siansiansu.taigikeyboard.engine.proto.CustomEntrySaved, Builder> implements
      // @@protoc_insertion_point(builder_implements:taigi.engine.CustomEntrySaved)
      com.siansiansu.taigikeyboard.engine.proto.CustomEntrySavedOrBuilder {
    // Construct using com.siansiansu.taigikeyboard.engine.proto.CustomEntrySaved.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <code>.taigi.engine.CustomDictionaryRefusal refusal = 1;</code>
     * @return The enum numeric value on the wire for refusal.
     */
    @java.lang.Override
    public int getRefusalValue() {
      return instance.getRefusalValue();
    }
    /**
     * <code>.taigi.engine.CustomDictionaryRefusal refusal = 1;</code>
     * @param value The refusal to set.
     * @throws IllegalArgumentException if UNRECOGNIZED is provided.
     * @return This builder for chaining.
     */
    public Builder setRefusalValue(int value) {
      copyOnWrite();
      instance.setRefusalValue(value);
      return this;
    }
    /**
     * <code>.taigi.engine.CustomDictionaryRefusal refusal = 1;</code>
     * @return The refusal.
     */
    @java.lang.Override
    public com.siansiansu.taigikeyboard.engine.proto.CustomDictionaryRefusal getRefusal() {
      return instance.getRefusal();
    }
    /**
     * <code>.taigi.engine.CustomDictionaryRefusal refusal = 1;</code>
     * @param value The enum numeric value on the wire for refusal to set.
     * @return This builder for chaining.
     */
    public Builder setRefusal(com.siansiansu.taigikeyboard.engine.proto.CustomDictionaryRefusal value) {
      copyOnWrite();
      instance.setRefusal(value);
      return this;
    }
    /**
     * <code>.taigi.engine.CustomDictionaryRefusal refusal = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearRefusal() {
      copyOnWrite();
      instance.clearRefusal();
      return this;
    }

    /**
     * <pre>
     * The stored row; absent when refused.
     * </pre>
     *
     * <code>optional .taigi.engine.CustomDictionaryEntry entry = 2;</code>
     */
    @java.lang.Override
    public boolean hasEntry() {
      return instance.hasEntry();
    }
    /**
     * <pre>
     * The stored row; absent when refused.
     * </pre>
     *
     * <code>optional .taigi.engine.CustomDictionaryEntry entry = 2;</code>
     */
    @java.lang.Override
    public com.siansiansu.taigikeyboard.engine.proto.CustomDictionaryEntry getEntry() {
      return instance.getEntry();
    }
    /**
     * <pre>
     * The stored row; absent when refused.
     * </pre>
     *
     * <code>optional .taigi.engine.CustomDictionaryEntry entry = 2;</code>
     */
    public Builder setEntry(com.siansiansu.taigikeyboard.engine.proto.CustomDictionaryEntry value) {
      copyOnWrite();
      instance.setEntry(value);
      return this;
      }
    /**
     * <pre>
     * The stored row; absent when refused.
     * </pre>
     *
     * <code>optional .taigi.engine.CustomDictionaryEntry entry = 2;</code>
     */
    public Builder setEntry(
        com.siansiansu.taigikeyboard.engine.proto.CustomDictionaryEntry.Builder builderForValue) {
      copyOnWrite();
      instance.setEntry(builderForValue.build());
      return this;
    }
    /**
     * <pre>
     * The stored row; absent when refused.
     * </pre>
     *
     * <code>optional .taigi.engine.CustomDictionaryEntry entry = 2;</code>
     */
    public Builder mergeEntry(com.siansiansu.taigikeyboard.engine.proto.CustomDictionaryEntry value) {
      copyOnWrite();
      instance.mergeEntry(value);
      return this;
    }
    /**
     * <pre>
     * The stored row; absent when refused.
     * </pre>
     *
     * <code>optional .taigi.engine.CustomDictionaryEntry entry = 2;</code>
     */
    public Builder clearEntry() {  copyOnWrite();
      instance.clearEntry();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:taigi.engine.CustomEntrySaved)
  }
  @java.lang.Override
  @java.lang.SuppressWarnings({"ThrowNull"})
  protected final java.lang.Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      java.lang.Object arg0, java.lang.Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new com.siansiansu.taigikeyboard.engine.proto.CustomEntrySaved();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
          java.lang.Object[] objects = new java.lang.Object[] {
            "bitField0_",
            "refusal_",
            "entry_",
          };
          java.lang.String info =
              "\u0000\u0002\u0000\u0001\u0001\u0002\u0002\u0000\u0000\u0000\u0001\f\u0002\u1009" +
              "\u0000";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<com.siansiansu.taigikeyboard.engine.proto.CustomEntrySaved> parser = PARSER;
        if (parser == null) {
          synchronized (com.siansiansu.taigikeyboard.engine.proto.CustomEntrySaved.class) {
            parser = PARSER;
            if (parser == null) {
              parser =
                  new DefaultInstanceBasedParser<com.siansiansu.taigikeyboard.engine.proto.CustomEntrySaved>(
                      DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      // SET_MEMOIZED_IS_INITIALIZED is never called for this message.
      // So it can do anything. Combine with default case for smaller codegen.
      case SET_MEMOIZED_IS_INITIALIZED:
    }
    // Should never happen. Generates tight code to throw an exception.
    throw null;
  }


  // @@protoc_insertion_point(class_scope:taigi.engine.CustomEntrySaved)
  private static final com.siansiansu.taigikeyboard.engine.proto.CustomEntrySaved DEFAULT_INSTANCE;
  static {
    CustomEntrySaved defaultInstance = new CustomEntrySaved();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
      CustomEntrySaved.class, defaultInstance);
  }

  public static com.siansiansu.taigikeyboard.engine.proto.CustomEntrySaved getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<CustomEntrySaved> PARSER;

  public static com.google.protobuf.Parser<CustomEntrySaved> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}
