// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: lexicon.proto
// Protobuf Java Version: 4.36.0

package com.siansiansu.taigikeyboard.engine.proto;

@com.google.protobuf.Generated
public interface DictionaryTogglesOrBuilder extends
    // @@protoc_insertion_point(interface_extends:taigi.engine.DictionaryToggles)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <pre>
   * 教育部臺灣台語常用詞辭典
   * </pre>
   *
   * <code>bool kautian = 1;</code>
   * @return The kautian.
   */
  boolean getKautian();

  /**
   * <pre>
   * 台語新詞辭庫
   * </pre>
   *
   * <code>bool taigitv = 2;</code>
   * @return The taigitv.
   */
  boolean getTaigitv();

  /**
   * <pre>
   * iTaigi 華台對照典
   * </pre>
   *
   * <code>bool itaigi = 3;</code>
   * @return The itaigi.
   */
  boolean getItaigi();

  /**
   * <pre>
   * 台灣植物名彙
   * </pre>
   *
   * <code>bool sitbut = 4;</code>
   * @return The sitbut.
   */
  boolean getSitbut();

  /**
   * <pre>
   * 台華線頂對照典
   * </pre>
   *
   * <code>bool taihoa = 5;</code>
   * @return The taihoa.
   */
  boolean getTaihoa();

  /**
   * <pre>
   * 台日大辭典
   * </pre>
   *
   * <code>bool taijit = 6;</code>
   * @return The taijit.
   */
  boolean getTaijit();

  /**
   * <pre>
   * 台語工藝詞庫
   * </pre>
   *
   * <code>bool kungge = 7;</code>
   * @return The kungge.
   */
  boolean getKungge();

  /**
   * <pre>
   * 學科術語辭典
   * </pre>
   *
   * <code>bool stti = 8;</code>
   * @return The stti.
   */
  boolean getStti();

  /**
   * <pre>
   * 腔口補充資料
   * </pre>
   *
   * <code>bool khpoo = 9;</code>
   * @return The khpoo.
   */
  boolean getKhpoo();

  /**
   * <pre>
   * 異用字 (filter bit 12)
   * </pre>
   *
   * <code>bool variant = 10;</code>
   * @return The variant.
   */
  boolean getVariant();

  /**
   * <pre>
   * 在來字 (filter bit 9)
   * </pre>
   *
   * <code>bool khiin = 11;</code>
   * @return The khiin.
   */
  boolean getKhiin();

  /**
   * <pre>
   * LKK漢羅合用建議用字
   * </pre>
   *
   * <code>bool lkk = 12;</code>
   * @return The lkk.
   */
  boolean getLkk();

  /**
   * <pre>
   * 開發者補充辭典 (詞庫增補檔案, filter bit 10) — default on, now toggleable
   * </pre>
   *
   * <code>bool dev = 14;</code>
   * @return The dev.
   */
  boolean getDev();

  /**
   * <pre>
   * kautian subcollection toggles. Absent ⇒ engine skips the subcollection
   * gate (legacy all-on). Only meaningful when `kautian = true`.
   * </pre>
   *
   * <code>.taigi.engine.KautianSubcollToggles kautian_subcoll = 13;</code>
   * @return Whether the kautianSubcoll field is set.
   */
  boolean hasKautianSubcoll();
  /**
   * <pre>
   * kautian subcollection toggles. Absent ⇒ engine skips the subcollection
   * gate (legacy all-on). Only meaningful when `kautian = true`.
   * </pre>
   *
   * <code>.taigi.engine.KautianSubcollToggles kautian_subcoll = 13;</code>
   * @return The kautianSubcoll.
   */
  com.siansiansu.taigikeyboard.engine.proto.KautianSubcollToggles getKautianSubcoll();
}
