// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: nextword.proto
// Protobuf Java Version: 4.36.2

package com.siansiansu.taigikeyboard.engine.proto;

@com.google.protobuf.Generated
public interface EnginePredictionOrBuilder extends
    // @@protoc_insertion_point(interface_extends:taigi.engine.EnginePrediction)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>string text = 1;</code>
   * @return The text.
   */
  java.lang.String getText();
  /**
   * <code>string text = 1;</code>
   * @return The bytes for text.
   */
  com.google.protobuf.ByteString
      getTextBytes();

  /**
   * <pre>
   * "" == nil (Optional on iOS, nullable on Android). Filter contract
   * guarantees subtitle = "" only when roman is empty (i.e. nil case);
   * non-nil empty subtitle cannot arise because hanji is required
   * non-empty by the empty-hanji filter.
   * </pre>
   *
   * <code>string subtitle = 2;</code>
   * @return The subtitle.
   */
  java.lang.String getSubtitle();
  /**
   * <pre>
   * "" == nil (Optional on iOS, nullable on Android). Filter contract
   * guarantees subtitle = "" only when roman is empty (i.e. nil case);
   * non-nil empty subtitle cannot arise because hanji is required
   * non-empty by the empty-hanji filter.
   * </pre>
   *
   * <code>string subtitle = 2;</code>
   * @return The bytes for subtitle.
   */
  com.google.protobuf.ByteString
      getSubtitleBytes();

  /**
   * <code>string hanji = 3;</code>
   * @return The hanji.
   */
  java.lang.String getHanji();
  /**
   * <code>string hanji = 3;</code>
   * @return The bytes for hanji.
   */
  com.google.protobuf.ByteString
      getHanjiBytes();

  /**
   * <code>string tl = 4;</code>
   * @return The tl.
   */
  java.lang.String getTl();
  /**
   * <code>string tl = 4;</code>
   * @return The bytes for tl.
   */
  com.google.protobuf.ByteString
      getTlBytes();

  /**
   * <pre>
   * Merged score: min(dict_sum, DICT_SCORE_CAP 250) + user_sum, the sums
   * taken over the (hanji, tl) merge and the reading-variant fold
   * (behavioral-invariants §8). Test seam only; no platform reads it.
   * </pre>
   *
   * <code>double score = 5;</code>
   * @return The score.
   */
  double getScore();
}
