// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: user_data.proto
// Protobuf Java Version: 4.36.2

package com.siansiansu.taigikeyboard.engine.proto;

/**
 * <pre>
 * `platform` / `app_version` name the writer in the file (`ios`,
 * `android`, `macos`, `windows`, `linux`).
 * </pre>
 *
 * Protobuf type {@code taigi.engine.ExportBackup}
 */
@com.google.protobuf.Generated
public  final class ExportBackup extends
    com.google.protobuf.GeneratedMessageLite<
        ExportBackup, ExportBackup.Builder> implements
    // @@protoc_insertion_point(message_implements:taigi.engine.ExportBackup)
    ExportBackupOrBuilder {
  private ExportBackup() {
    platform_ = "";
    appVersion_ = "";
  }
  public static final int PLATFORM_FIELD_NUMBER = 1;
  private java.lang.String platform_;
  /**
   * <code>string platform = 1;</code>
   * @return The platform.
   */
  @java.lang.Override
  public java.lang.String getPlatform() {
    return platform_;
  }
  /**
   * <code>string platform = 1;</code>
   * @return The bytes for platform.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getPlatformBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(platform_);
  }
  /**
   * <code>string platform = 1;</code>
   * @param value The platform to set.
   */
  private void setPlatform(
      java.lang.String value) {
    java.util.Objects.requireNonNull(value);

    platform_ = value;
  }
  /**
   * <code>string platform = 1;</code>
   */
  private void clearPlatform() {

    platform_ = getDefaultInstance().getPlatform();
  }
  /**
   * <code>string platform = 1;</code>
   * @param value The bytes for platform to set.
   */
  private void setPlatformBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    platform_ = value.toStringUtf8();

  }

  public static final int APP_VERSION_FIELD_NUMBER = 2;
  private java.lang.String appVersion_;
  /**
   * <code>string app_version = 2;</code>
   * @return The appVersion.
   */
  @java.lang.Override
  public java.lang.String getAppVersion() {
    return appVersion_;
  }
  /**
   * <code>string app_version = 2;</code>
   * @return The bytes for appVersion.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getAppVersionBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(appVersion_);
  }
  /**
   * <code>string app_version = 2;</code>
   * @param value The appVersion to set.
   */
  private void setAppVersion(
      java.lang.String value) {
    java.util.Objects.requireNonNull(value);

    appVersion_ = value;
  }
  /**
   * <code>string app_version = 2;</code>
   */
  private void clearAppVersion() {

    appVersion_ = getDefaultInstance().getAppVersion();
  }
  /**
   * <code>string app_version = 2;</code>
   * @param value The bytes for appVersion to set.
   */
  private void setAppVersionBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    appVersion_ = value.toStringUtf8();

  }

  public static com.siansiansu.taigikeyboard.engine.proto.ExportBackup parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.siansiansu.taigikeyboard.engine.proto.ExportBackup parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.siansiansu.taigikeyboard.engine.proto.ExportBackup parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.siansiansu.taigikeyboard.engine.proto.ExportBackup parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.siansiansu.taigikeyboard.engine.proto.ExportBackup parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.siansiansu.taigikeyboard.engine.proto.ExportBackup parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.siansiansu.taigikeyboard.engine.proto.ExportBackup parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.siansiansu.taigikeyboard.engine.proto.ExportBackup parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static com.siansiansu.taigikeyboard.engine.proto.ExportBackup parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }

  public static com.siansiansu.taigikeyboard.engine.proto.ExportBackup parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static com.siansiansu.taigikeyboard.engine.proto.ExportBackup parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.siansiansu.taigikeyboard.engine.proto.ExportBackup parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }
  public static Builder newBuilder(com.siansiansu.taigikeyboard.engine.proto.ExportBackup prototype) {
    return DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * <pre>
   * `platform` / `app_version` name the writer in the file (`ios`,
   * `android`, `macos`, `windows`, `linux`).
   * </pre>
   *
   * Protobuf type {@code taigi.engine.ExportBackup}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        com.siansiansu.taigikeyboard.engine.proto.ExportBackup, Builder> implements
      // @@protoc_insertion_point(builder_implements:taigi.engine.ExportBackup)
      com.siansiansu.taigikeyboard.engine.proto.ExportBackupOrBuilder {
    // Construct using com.siansiansu.taigikeyboard.engine.proto.ExportBackup.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <code>string platform = 1;</code>
     * @return The platform.
     */
    @java.lang.Override
    public java.lang.String getPlatform() {
      return instance.getPlatform();
    }
    /**
     * <code>string platform = 1;</code>
     * @return The bytes for platform.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getPlatformBytes() {
      return instance.getPlatformBytes();
    }
    /**
     * <code>string platform = 1;</code>
     * @param value The platform to set.
     * @return This builder for chaining.
     */
    public Builder setPlatform(
        java.lang.String value) {
      copyOnWrite();
      instance.setPlatform(value);
      return this;
    }
    /**
     * <code>string platform = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearPlatform() {
      copyOnWrite();
      instance.clearPlatform();
      return this;
    }
    /**
     * <code>string platform = 1;</code>
     * @param value The bytes for platform to set.
     * @return This builder for chaining.
     */
    public Builder setPlatformBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setPlatformBytes(value);
      return this;
    }

    /**
     * <code>string app_version = 2;</code>
     * @return The appVersion.
     */
    @java.lang.Override
    public java.lang.String getAppVersion() {
      return instance.getAppVersion();
    }
    /**
     * <code>string app_version = 2;</code>
     * @return The bytes for appVersion.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getAppVersionBytes() {
      return instance.getAppVersionBytes();
    }
    /**
     * <code>string app_version = 2;</code>
     * @param value The appVersion to set.
     * @return This builder for chaining.
     */
    public Builder setAppVersion(
        java.lang.String value) {
      copyOnWrite();
      instance.setAppVersion(value);
      return this;
    }
    /**
     * <code>string app_version = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearAppVersion() {
      copyOnWrite();
      instance.clearAppVersion();
      return this;
    }
    /**
     * <code>string app_version = 2;</code>
     * @param value The bytes for appVersion to set.
     * @return This builder for chaining.
     */
    public Builder setAppVersionBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setAppVersionBytes(value);
      return this;
    }

    // @@protoc_insertion_point(builder_scope:taigi.engine.ExportBackup)
  }
  @java.lang.Override
  @java.lang.SuppressWarnings({"ThrowNull"})
  protected final java.lang.Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      java.lang.Object arg0, java.lang.Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new com.siansiansu.taigikeyboard.engine.proto.ExportBackup();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
          java.lang.Object[] objects = new java.lang.Object[] {
            "platform_",
            "appVersion_",
          };
          java.lang.String info =
              "\u0000\u0002\u0000\u0000\u0001\u0002\u0002\u0000\u0000\u0000\u0001\u0208\u0002\u0208" +
              "";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<com.siansiansu.taigikeyboard.engine.proto.ExportBackup> parser = PARSER;
        if (parser == null) {
          synchronized (com.siansiansu.taigikeyboard.engine.proto.ExportBackup.class) {
            parser = PARSER;
            if (parser == null) {
              parser =
                  new DefaultInstanceBasedParser<com.siansiansu.taigikeyboard.engine.proto.ExportBackup>(
                      DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      // SET_MEMOIZED_IS_INITIALIZED is never called for this message.
      // So it can do anything. Combine with default case for smaller codegen.
      case SET_MEMOIZED_IS_INITIALIZED:
    }
    // Should never happen. Generates tight code to throw an exception.
    throw null;
  }


  // @@protoc_insertion_point(class_scope:taigi.engine.ExportBackup)
  private static final com.siansiansu.taigikeyboard.engine.proto.ExportBackup DEFAULT_INSTANCE;
  static {
    ExportBackup defaultInstance = new ExportBackup();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
      ExportBackup.class, defaultInstance);
  }

  public static com.siansiansu.taigikeyboard.engine.proto.ExportBackup getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<ExportBackup> PARSER;

  public static com.google.protobuf.Parser<ExportBackup> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}
