// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: composing.proto
// Protobuf Java Version: 4.27.5

package com.siansiansu.taigikeyboard.engine.proto;

public interface FetchAtPosOrBuilder extends
    // @@protoc_insertion_point(interface_extends:taigi.engine.FetchAtPos)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>uint32 position = 1;</code>
   * @return The position.
   */
  int getPosition();
}
