// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: composing.proto
// Protobuf Java Version: 4.36.2

package com.siansiansu.taigikeyboard.engine.proto;

@com.google.protobuf.Generated
public interface FetchAtPosOrBuilder extends
    // @@protoc_insertion_point(interface_extends:taigi.engine.FetchAtPos)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>repeated .taigi.engine.FrequencyEntry frequency_entries = 2;</code>
   */
  java.util.List<com.siansiansu.taigikeyboard.engine.proto.FrequencyEntry>
      getFrequencyEntriesList();
  /**
   * <code>repeated .taigi.engine.FrequencyEntry frequency_entries = 2;</code>
   */
  com.siansiansu.taigikeyboard.engine.proto.FrequencyEntry getFrequencyEntries(int index);
  /**
   * <code>repeated .taigi.engine.FrequencyEntry frequency_entries = 2;</code>
   */
  int getFrequencyEntriesCount();

  /**
   * <code>int64 now_ms = 3;</code>
   * @return The nowMs.
   */
  long getNowMs();

  /**
   * <code>repeated .taigi.engine.CustomDictEntry custom_entries = 4;</code>
   */
  java.util.List<com.siansiansu.taigikeyboard.engine.proto.CustomDictEntry>
      getCustomEntriesList();
  /**
   * <code>repeated .taigi.engine.CustomDictEntry custom_entries = 4;</code>
   */
  com.siansiansu.taigikeyboard.engine.proto.CustomDictEntry getCustomEntries(int index);
  /**
   * <code>repeated .taigi.engine.CustomDictEntry custom_entries = 4;</code>
   */
  int getCustomEntriesCount();

  /**
   * <code>uint32 enabled_sources_bitmask = 5;</code>
   * @return The enabledSourcesBitmask.
   */
  int getEnabledSourcesBitmask();

  /**
   * <code>bool literal_roman_candidate_disabled = 6;</code>
   * @return The literalRomanCandidateDisabled.
   */
  boolean getLiteralRomanCandidateDisabled();

  /**
   * <pre>
   * Learned phrases (§50) — the platform's auto-learned rows whose
   * whole-buffer key equals the current raw buffer (exact match, not the
   * prefix search `custom_entries` rides). Kept apart from
   * `custom_entries` on purpose: a manual custom row overrides the walker
   * edge unconditionally, a learned row only COMPETES with the dictionary
   * rows under the same key (Codex 2026-09-20 F5). Empty = feature off /
   * un-wired build → no learned candidates.
   * </pre>
   *
   * <code>repeated .taigi.engine.LearnedEntry learned_entries = 7;</code>
   */
  java.util.List<com.siansiansu.taigikeyboard.engine.proto.LearnedEntry>
      getLearnedEntriesList();
  /**
   * <pre>
   * Learned phrases (§50) — the platform's auto-learned rows whose
   * whole-buffer key equals the current raw buffer (exact match, not the
   * prefix search `custom_entries` rides). Kept apart from
   * `custom_entries` on purpose: a manual custom row overrides the walker
   * edge unconditionally, a learned row only COMPETES with the dictionary
   * rows under the same key (Codex 2026-09-20 F5). Empty = feature off /
   * un-wired build → no learned candidates.
   * </pre>
   *
   * <code>repeated .taigi.engine.LearnedEntry learned_entries = 7;</code>
   */
  com.siansiansu.taigikeyboard.engine.proto.LearnedEntry getLearnedEntries(int index);
  /**
   * <pre>
   * Learned phrases (§50) — the platform's auto-learned rows whose
   * whole-buffer key equals the current raw buffer (exact match, not the
   * prefix search `custom_entries` rides). Kept apart from
   * `custom_entries` on purpose: a manual custom row overrides the walker
   * edge unconditionally, a learned row only COMPETES with the dictionary
   * rows under the same key (Codex 2026-09-20 F5). Empty = feature off /
   * un-wired build → no learned candidates.
   * </pre>
   *
   * <code>repeated .taigi.engine.LearnedEntry learned_entries = 7;</code>
   */
  int getLearnedEntriesCount();
}
