// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: nextword.proto
// Protobuf Java Version: 4.35.1

package com.siansiansu.taigikeyboard.engine.proto;

/**
 * <pre>
 * Engine-side filter+merge+sort+limit step. Platform calls this after
 * SQLite returns raw rows — engine groups by (hanzi, tl), scores dict
 * rows via DICT_WEIGHT and user rows via decay+learning math, sorts desc
 * by score, applies limit, then shapes via display-rule filter. On
 * generation mismatch returns predictions=[] + was_stale=true.
 *
 * COLLISION RULE on (hanzi, tl): dict contributions SUM (a learned word
 * outranking the same word from the dictionary is the design), but at most
 * ONE user contribution is accepted — the FIRST. Under the v6
 * user_association key, one predicted word can be backed by several stored
 * rows differing in the previous word's reading, and summing them would give
 * it several LEARNING_BONUS terms for being 一字多音 rather than for being
 * well-learned (behavioral-invariants.md §24).
 *
 * THEREFORE `raw` IS PRIORITY-ORDERED, NOT A SET. Callers MUST deliver user
 * rows best-evidence-first — the platform SQL orders them
 * `CASE prev_tl = query THEN 0 WHEN '' THEN 1 ELSE 2 END, count DESC,
 * last_used DESC, id ASC` — and nothing between the SQLite cursor and this
 * request may reorder them.
 * </pre>
 *
 * Protobuf type {@code taigi.engine.FilterPredictions}
 */
@com.google.protobuf.Generated
public  final class FilterPredictions extends
    com.google.protobuf.GeneratedMessageLite<
        FilterPredictions, FilterPredictions.Builder> implements
    // @@protoc_insertion_point(message_implements:taigi.engine.FilterPredictions)
    FilterPredictionsOrBuilder {
  private FilterPredictions() {
    raw_ = emptyProtobufList();
  }
  public static final int RAW_FIELD_NUMBER = 1;
  private com.google.protobuf.Internal.ProtobufList<com.siansiansu.taigikeyboard.engine.proto.RawNextWordPrediction> raw_;
  /**
   * <code>repeated .taigi.engine.RawNextWordPrediction raw = 1;</code>
   */
  @java.lang.Override
  public java.util.List<com.siansiansu.taigikeyboard.engine.proto.RawNextWordPrediction> getRawList() {
    return raw_;
  }
  /**
   * <code>repeated .taigi.engine.RawNextWordPrediction raw = 1;</code>
   */
  public java.util.List<? extends com.siansiansu.taigikeyboard.engine.proto.RawNextWordPredictionOrBuilder>
      getRawOrBuilderList() {
    return raw_;
  }
  /**
   * <code>repeated .taigi.engine.RawNextWordPrediction raw = 1;</code>
   */
  @java.lang.Override
  public int getRawCount() {
    return raw_.size();
  }
  /**
   * <code>repeated .taigi.engine.RawNextWordPrediction raw = 1;</code>
   */
  @java.lang.Override
  public com.siansiansu.taigikeyboard.engine.proto.RawNextWordPrediction getRaw(int index) {
    return raw_.get(index);
  }
  /**
   * <code>repeated .taigi.engine.RawNextWordPrediction raw = 1;</code>
   */
  public com.siansiansu.taigikeyboard.engine.proto.RawNextWordPredictionOrBuilder getRawOrBuilder(
      int index) {
    return raw_.get(index);
  }
  private void ensureRawIsMutable() {
    com.google.protobuf.Internal.ProtobufList<com.siansiansu.taigikeyboard.engine.proto.RawNextWordPrediction> tmp = raw_;
    if (!tmp.isModifiable()) {
      raw_ =
          com.google.protobuf.GeneratedMessageLite.mutableCopy(tmp);
     }
  }

  /**
   * <code>repeated .taigi.engine.RawNextWordPrediction raw = 1;</code>
   */
  @java.lang.SuppressWarnings("ReturnValueIgnored")
  private void setRaw(
      int index, com.siansiansu.taigikeyboard.engine.proto.RawNextWordPrediction value) {
    value.getClass();  // minimal bytecode null check
    ensureRawIsMutable();
    raw_.set(index, value);
  }
  /**
   * <code>repeated .taigi.engine.RawNextWordPrediction raw = 1;</code>
   */
  @java.lang.SuppressWarnings("ReturnValueIgnored")
  private void addRaw(com.siansiansu.taigikeyboard.engine.proto.RawNextWordPrediction value) {
    value.getClass();  // minimal bytecode null check
    ensureRawIsMutable();
    raw_.add(value);
  }
  /**
   * <code>repeated .taigi.engine.RawNextWordPrediction raw = 1;</code>
   */
  @java.lang.SuppressWarnings("ReturnValueIgnored")
  private void addRaw(
      int index, com.siansiansu.taigikeyboard.engine.proto.RawNextWordPrediction value) {
    value.getClass();  // minimal bytecode null check
    ensureRawIsMutable();
    raw_.add(index, value);
  }
  /**
   * <code>repeated .taigi.engine.RawNextWordPrediction raw = 1;</code>
   */
  private void addAllRaw(
      java.lang.Iterable<? extends com.siansiansu.taigikeyboard.engine.proto.RawNextWordPrediction> values) {
    ensureRawIsMutable();
    com.google.protobuf.AbstractMessageLite.addAll(
        values, raw_);
  }
  /**
   * <code>repeated .taigi.engine.RawNextWordPrediction raw = 1;</code>
   */
  private void clearRaw() {
    raw_ = emptyProtobufList();
  }
  /**
   * <code>repeated .taigi.engine.RawNextWordPrediction raw = 1;</code>
   */
  private void removeRaw(int index) {
    ensureRawIsMutable();
    raw_.remove(index);
  }

  public static final int QUERY_GENERATION_FIELD_NUMBER = 2;
  private long queryGeneration_;
  /**
   * <pre>
   * matches state.current_generation when fresh
   * </pre>
   *
   * <code>uint64 query_generation = 2;</code>
   * @return The queryGeneration.
   */
  @java.lang.Override
  public long getQueryGeneration() {
    return queryGeneration_;
  }
  /**
   * <pre>
   * matches state.current_generation when fresh
   * </pre>
   *
   * <code>uint64 query_generation = 2;</code>
   * @param value The queryGeneration to set.
   */
  private void setQueryGeneration(long value) {

    queryGeneration_ = value;
  }
  /**
   * <pre>
   * matches state.current_generation when fresh
   * </pre>
   *
   * <code>uint64 query_generation = 2;</code>
   */
  private void clearQueryGeneration() {

    queryGeneration_ = 0L;
  }

  public static final int NOW_MS_FIELD_NUMBER = 3;
  private long nowMs_;
  /**
   * <pre>
   * single decision-time clock per intent
   * </pre>
   *
   * <code>int64 now_ms = 3;</code>
   * @return The nowMs.
   */
  @java.lang.Override
  public long getNowMs() {
    return nowMs_;
  }
  /**
   * <pre>
   * single decision-time clock per intent
   * </pre>
   *
   * <code>int64 now_ms = 3;</code>
   * @param value The nowMs to set.
   */
  private void setNowMs(long value) {

    nowMs_ = value;
  }
  /**
   * <pre>
   * single decision-time clock per intent
   * </pre>
   *
   * <code>int64 now_ms = 3;</code>
   */
  private void clearNowMs() {

    nowMs_ = 0L;
  }

  public static final int LIMIT_FIELD_NUMBER = 4;
  private int limit_;
  /**
   * <pre>
   * post-merge truncation; 30 default if 0
   * </pre>
   *
   * <code>int32 limit = 4;</code>
   * @return The limit.
   */
  @java.lang.Override
  public int getLimit() {
    return limit_;
  }
  /**
   * <pre>
   * post-merge truncation; 30 default if 0
   * </pre>
   *
   * <code>int32 limit = 4;</code>
   * @param value The limit to set.
   */
  private void setLimit(int value) {

    limit_ = value;
  }
  /**
   * <pre>
   * post-merge truncation; 30 default if 0
   * </pre>
   *
   * <code>int32 limit = 4;</code>
   */
  private void clearLimit() {

    limit_ = 0;
  }

  public static com.siansiansu.taigikeyboard.engine.proto.FilterPredictions parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.siansiansu.taigikeyboard.engine.proto.FilterPredictions parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.siansiansu.taigikeyboard.engine.proto.FilterPredictions parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.siansiansu.taigikeyboard.engine.proto.FilterPredictions parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.siansiansu.taigikeyboard.engine.proto.FilterPredictions parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.siansiansu.taigikeyboard.engine.proto.FilterPredictions parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.siansiansu.taigikeyboard.engine.proto.FilterPredictions parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.siansiansu.taigikeyboard.engine.proto.FilterPredictions parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static com.siansiansu.taigikeyboard.engine.proto.FilterPredictions parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }

  public static com.siansiansu.taigikeyboard.engine.proto.FilterPredictions parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static com.siansiansu.taigikeyboard.engine.proto.FilterPredictions parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.siansiansu.taigikeyboard.engine.proto.FilterPredictions parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }
  public static Builder newBuilder(com.siansiansu.taigikeyboard.engine.proto.FilterPredictions prototype) {
    return DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * <pre>
   * Engine-side filter+merge+sort+limit step. Platform calls this after
   * SQLite returns raw rows — engine groups by (hanzi, tl), scores dict
   * rows via DICT_WEIGHT and user rows via decay+learning math, sorts desc
   * by score, applies limit, then shapes via display-rule filter. On
   * generation mismatch returns predictions=[] + was_stale=true.
   *
   * COLLISION RULE on (hanzi, tl): dict contributions SUM (a learned word
   * outranking the same word from the dictionary is the design), but at most
   * ONE user contribution is accepted — the FIRST. Under the v6
   * user_association key, one predicted word can be backed by several stored
   * rows differing in the previous word's reading, and summing them would give
   * it several LEARNING_BONUS terms for being 一字多音 rather than for being
   * well-learned (behavioral-invariants.md §24).
   *
   * THEREFORE `raw` IS PRIORITY-ORDERED, NOT A SET. Callers MUST deliver user
   * rows best-evidence-first — the platform SQL orders them
   * `CASE prev_tl = query THEN 0 WHEN '' THEN 1 ELSE 2 END, count DESC,
   * last_used DESC, id ASC` — and nothing between the SQLite cursor and this
   * request may reorder them.
   * </pre>
   *
   * Protobuf type {@code taigi.engine.FilterPredictions}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        com.siansiansu.taigikeyboard.engine.proto.FilterPredictions, Builder> implements
      // @@protoc_insertion_point(builder_implements:taigi.engine.FilterPredictions)
      com.siansiansu.taigikeyboard.engine.proto.FilterPredictionsOrBuilder {
    // Construct using com.siansiansu.taigikeyboard.engine.proto.FilterPredictions.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <code>repeated .taigi.engine.RawNextWordPrediction raw = 1;</code>
     */
    @java.lang.Override
    public java.util.List<com.siansiansu.taigikeyboard.engine.proto.RawNextWordPrediction> getRawList() {
      return java.util.Collections.unmodifiableList(
          instance.getRawList());
    }
    /**
     * <code>repeated .taigi.engine.RawNextWordPrediction raw = 1;</code>
     */
    @java.lang.Override
    public int getRawCount() {
      return instance.getRawCount();
    }/**
     * <code>repeated .taigi.engine.RawNextWordPrediction raw = 1;</code>
     */
    @java.lang.Override
    public com.siansiansu.taigikeyboard.engine.proto.RawNextWordPrediction getRaw(int index) {
      return instance.getRaw(index);
    }
    /**
     * <code>repeated .taigi.engine.RawNextWordPrediction raw = 1;</code>
     */
    public Builder setRaw(
        int index, com.siansiansu.taigikeyboard.engine.proto.RawNextWordPrediction value) {
      copyOnWrite();
      instance.setRaw(index, value);
      return this;
    }
    /**
     * <code>repeated .taigi.engine.RawNextWordPrediction raw = 1;</code>
     */
    public Builder setRaw(
        int index, com.siansiansu.taigikeyboard.engine.proto.RawNextWordPrediction.Builder builderForValue) {
      copyOnWrite();
      instance.setRaw(index,
          builderForValue.build());
      return this;
    }
    /**
     * <code>repeated .taigi.engine.RawNextWordPrediction raw = 1;</code>
     */
    public Builder addRaw(com.siansiansu.taigikeyboard.engine.proto.RawNextWordPrediction value) {
      copyOnWrite();
      instance.addRaw(value);
      return this;
    }
    /**
     * <code>repeated .taigi.engine.RawNextWordPrediction raw = 1;</code>
     */
    public Builder addRaw(
        int index, com.siansiansu.taigikeyboard.engine.proto.RawNextWordPrediction value) {
      copyOnWrite();
      instance.addRaw(index, value);
      return this;
    }
    /**
     * <code>repeated .taigi.engine.RawNextWordPrediction raw = 1;</code>
     */
    public Builder addRaw(
        com.siansiansu.taigikeyboard.engine.proto.RawNextWordPrediction.Builder builderForValue) {
      copyOnWrite();
      instance.addRaw(builderForValue.build());
      return this;
    }
    /**
     * <code>repeated .taigi.engine.RawNextWordPrediction raw = 1;</code>
     */
    public Builder addRaw(
        int index, com.siansiansu.taigikeyboard.engine.proto.RawNextWordPrediction.Builder builderForValue) {
      copyOnWrite();
      instance.addRaw(index,
          builderForValue.build());
      return this;
    }
    /**
     * <code>repeated .taigi.engine.RawNextWordPrediction raw = 1;</code>
     */
    public Builder addAllRaw(
        java.lang.Iterable<? extends com.siansiansu.taigikeyboard.engine.proto.RawNextWordPrediction> values) {
      copyOnWrite();
      instance.addAllRaw(values);
      return this;
    }
    /**
     * <code>repeated .taigi.engine.RawNextWordPrediction raw = 1;</code>
     */
    public Builder clearRaw() {
      copyOnWrite();
      instance.clearRaw();
      return this;
    }
    /**
     * <code>repeated .taigi.engine.RawNextWordPrediction raw = 1;</code>
     */
    public Builder removeRaw(int index) {
      copyOnWrite();
      instance.removeRaw(index);
      return this;
    }

    /**
     * <pre>
     * matches state.current_generation when fresh
     * </pre>
     *
     * <code>uint64 query_generation = 2;</code>
     * @return The queryGeneration.
     */
    @java.lang.Override
    public long getQueryGeneration() {
      return instance.getQueryGeneration();
    }
    /**
     * <pre>
     * matches state.current_generation when fresh
     * </pre>
     *
     * <code>uint64 query_generation = 2;</code>
     * @param value The queryGeneration to set.
     * @return This builder for chaining.
     */
    public Builder setQueryGeneration(long value) {
      copyOnWrite();
      instance.setQueryGeneration(value);
      return this;
    }
    /**
     * <pre>
     * matches state.current_generation when fresh
     * </pre>
     *
     * <code>uint64 query_generation = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearQueryGeneration() {
      copyOnWrite();
      instance.clearQueryGeneration();
      return this;
    }

    /**
     * <pre>
     * single decision-time clock per intent
     * </pre>
     *
     * <code>int64 now_ms = 3;</code>
     * @return The nowMs.
     */
    @java.lang.Override
    public long getNowMs() {
      return instance.getNowMs();
    }
    /**
     * <pre>
     * single decision-time clock per intent
     * </pre>
     *
     * <code>int64 now_ms = 3;</code>
     * @param value The nowMs to set.
     * @return This builder for chaining.
     */
    public Builder setNowMs(long value) {
      copyOnWrite();
      instance.setNowMs(value);
      return this;
    }
    /**
     * <pre>
     * single decision-time clock per intent
     * </pre>
     *
     * <code>int64 now_ms = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearNowMs() {
      copyOnWrite();
      instance.clearNowMs();
      return this;
    }

    /**
     * <pre>
     * post-merge truncation; 30 default if 0
     * </pre>
     *
     * <code>int32 limit = 4;</code>
     * @return The limit.
     */
    @java.lang.Override
    public int getLimit() {
      return instance.getLimit();
    }
    /**
     * <pre>
     * post-merge truncation; 30 default if 0
     * </pre>
     *
     * <code>int32 limit = 4;</code>
     * @param value The limit to set.
     * @return This builder for chaining.
     */
    public Builder setLimit(int value) {
      copyOnWrite();
      instance.setLimit(value);
      return this;
    }
    /**
     * <pre>
     * post-merge truncation; 30 default if 0
     * </pre>
     *
     * <code>int32 limit = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearLimit() {
      copyOnWrite();
      instance.clearLimit();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:taigi.engine.FilterPredictions)
  }
  @java.lang.Override
  @java.lang.SuppressWarnings({"ThrowNull"})
  protected final java.lang.Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      java.lang.Object arg0, java.lang.Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new com.siansiansu.taigikeyboard.engine.proto.FilterPredictions();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
          java.lang.Object[] objects = new java.lang.Object[] {
            "raw_",
            com.siansiansu.taigikeyboard.engine.proto.RawNextWordPrediction.class,
            "queryGeneration_",
            "nowMs_",
            "limit_",
          };
          java.lang.String info =
              "\u0000\u0004\u0000\u0000\u0001\u0004\u0004\u0000\u0001\u0000\u0001\u001b\u0002\u0003" +
              "\u0003\u0002\u0004\u0004";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<com.siansiansu.taigikeyboard.engine.proto.FilterPredictions> parser = PARSER;
        if (parser == null) {
          synchronized (com.siansiansu.taigikeyboard.engine.proto.FilterPredictions.class) {
            parser = PARSER;
            if (parser == null) {
              parser =
                  new DefaultInstanceBasedParser<com.siansiansu.taigikeyboard.engine.proto.FilterPredictions>(
                      DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      // SET_MEMOIZED_IS_INITIALIZED is never called for this message.
      // So it can do anything. Combine with default case for smaller codegen.
      case SET_MEMOIZED_IS_INITIALIZED:
    }
    // Should never happen. Generates tight code to throw an exception.
    throw null;
  }


  // @@protoc_insertion_point(class_scope:taigi.engine.FilterPredictions)
  private static final com.siansiansu.taigikeyboard.engine.proto.FilterPredictions DEFAULT_INSTANCE;
  static {
    FilterPredictions defaultInstance = new FilterPredictions();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
      FilterPredictions.class, defaultInstance);
  }

  public static com.siansiansu.taigikeyboard.engine.proto.FilterPredictions getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<FilterPredictions> PARSER;

  public static com.google.protobuf.Parser<FilterPredictions> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}
