// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: nextword.proto
// Protobuf Java Version: 4.35.1

package com.siansiansu.taigikeyboard.engine.proto;

@com.google.protobuf.Generated
public interface FilterPredictionsOrBuilder extends
    // @@protoc_insertion_point(interface_extends:taigi.engine.FilterPredictions)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>repeated .taigi.engine.RawNextWordPrediction raw = 1;</code>
   */
  java.util.List<com.siansiansu.taigikeyboard.engine.proto.RawNextWordPrediction>
      getRawList();
  /**
   * <code>repeated .taigi.engine.RawNextWordPrediction raw = 1;</code>
   */
  com.siansiansu.taigikeyboard.engine.proto.RawNextWordPrediction getRaw(int index);
  /**
   * <code>repeated .taigi.engine.RawNextWordPrediction raw = 1;</code>
   */
  int getRawCount();

  /**
   * <pre>
   * matches state.current_generation when fresh
   * </pre>
   *
   * <code>uint64 query_generation = 2;</code>
   * @return The queryGeneration.
   */
  long getQueryGeneration();

  /**
   * <pre>
   * single decision-time clock per intent
   * </pre>
   *
   * <code>int64 now_ms = 3;</code>
   * @return The nowMs.
   */
  long getNowMs();

  /**
   * <pre>
   * post-merge truncation; 30 default if 0
   * </pre>
   *
   * <code>int32 limit = 4;</code>
   * @return The limit.
   */
  int getLimit();
}
