// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: lexicon.proto
// Protobuf Java Version: 4.35.1

package com.siansiansu.taigikeyboard.engine.proto;

/**
 * <pre>
 * `FrequencyEntry` is the per-candidate user-frequency snapshot. Caller
 * pre-filters to candidate-relevant keys to keep the request small.
 * `display_text_key` matches `TaigiWord.displayText` (= hanji ?? roman)
 * so the engine can `find` matching entries during scoring.
 *
 * v3.6.1 R5 — user-frequency identity is the `(display_text_key,
 * canonical_tl)` PAIR (Core Principle #7). `canonical_tl` is the
 * candidate's canonical-TL reading, snapshotted BEFORE the POJ-render
 * pass (= `RawCandidate.canonical_tl`). One `display_text` (e.g. 重) now
 * carries one entry PER reading (重/tîng vs 重/tāng), so 一字多音 keep
 * separate frequency buckets. `canonical_tl == ""` is the LEGACY sentinel
 * for pre-R5 rows / old-backup imports the platform could not re-key; the
 * engine treats it as a tolerant fallback bucket consulted by ALL readings
 * of that `display_text` until each is re-learned (see
 * `ranking::FrequencyMap::get`). Empty string is the canonical legacy
 * marker — the field is NOT `optional`.
 * </pre>
 *
 * Protobuf type {@code taigi.engine.FrequencyEntry}
 */
@com.google.protobuf.Generated
public  final class FrequencyEntry extends
    com.google.protobuf.GeneratedMessageLite<
        FrequencyEntry, FrequencyEntry.Builder> implements
    // @@protoc_insertion_point(message_implements:taigi.engine.FrequencyEntry)
    FrequencyEntryOrBuilder {
  private FrequencyEntry() {
    displayTextKey_ = "";
    canonicalTl_ = "";
  }
  public static final int DISPLAY_TEXT_KEY_FIELD_NUMBER = 1;
  private java.lang.String displayTextKey_;
  /**
   * <code>string display_text_key = 1;</code>
   * @return The displayTextKey.
   */
  @java.lang.Override
  public java.lang.String getDisplayTextKey() {
    return displayTextKey_;
  }
  /**
   * <code>string display_text_key = 1;</code>
   * @return The bytes for displayTextKey.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getDisplayTextKeyBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(displayTextKey_);
  }
  /**
   * <code>string display_text_key = 1;</code>
   * @param value The displayTextKey to set.
   */
  @java.lang.SuppressWarnings("ReturnValueIgnored")
  private void setDisplayTextKey(
      java.lang.String value) {
    value.getClass();  // minimal bytecode null check

    displayTextKey_ = value;
  }
  /**
   * <code>string display_text_key = 1;</code>
   */
  private void clearDisplayTextKey() {

    displayTextKey_ = getDefaultInstance().getDisplayTextKey();
  }
  /**
   * <code>string display_text_key = 1;</code>
   * @param value The bytes for displayTextKey to set.
   */
  private void setDisplayTextKeyBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    displayTextKey_ = value.toStringUtf8();

  }

  public static final int COUNT_FIELD_NUMBER = 2;
  private int count_;
  /**
   * <code>uint32 count = 2;</code>
   * @return The count.
   */
  @java.lang.Override
  public int getCount() {
    return count_;
  }
  /**
   * <code>uint32 count = 2;</code>
   * @param value The count to set.
   */
  private void setCount(int value) {

    count_ = value;
  }
  /**
   * <code>uint32 count = 2;</code>
   */
  private void clearCount() {

    count_ = 0;
  }

  public static final int LAST_USED_MS_FIELD_NUMBER = 3;
  private long lastUsedMs_;
  /**
   * <code>int64 last_used_ms = 3;</code>
   * @return The lastUsedMs.
   */
  @java.lang.Override
  public long getLastUsedMs() {
    return lastUsedMs_;
  }
  /**
   * <code>int64 last_used_ms = 3;</code>
   * @param value The lastUsedMs to set.
   */
  private void setLastUsedMs(long value) {

    lastUsedMs_ = value;
  }
  /**
   * <code>int64 last_used_ms = 3;</code>
   */
  private void clearLastUsedMs() {

    lastUsedMs_ = 0L;
  }

  public static final int CANONICAL_TL_FIELD_NUMBER = 4;
  private java.lang.String canonicalTl_;
  /**
   * <code>string canonical_tl = 4;</code>
   * @return The canonicalTl.
   */
  @java.lang.Override
  public java.lang.String getCanonicalTl() {
    return canonicalTl_;
  }
  /**
   * <code>string canonical_tl = 4;</code>
   * @return The bytes for canonicalTl.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getCanonicalTlBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(canonicalTl_);
  }
  /**
   * <code>string canonical_tl = 4;</code>
   * @param value The canonicalTl to set.
   */
  @java.lang.SuppressWarnings("ReturnValueIgnored")
  private void setCanonicalTl(
      java.lang.String value) {
    value.getClass();  // minimal bytecode null check

    canonicalTl_ = value;
  }
  /**
   * <code>string canonical_tl = 4;</code>
   */
  private void clearCanonicalTl() {

    canonicalTl_ = getDefaultInstance().getCanonicalTl();
  }
  /**
   * <code>string canonical_tl = 4;</code>
   * @param value The bytes for canonicalTl to set.
   */
  private void setCanonicalTlBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    canonicalTl_ = value.toStringUtf8();

  }

  public static com.siansiansu.taigikeyboard.engine.proto.FrequencyEntry parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.siansiansu.taigikeyboard.engine.proto.FrequencyEntry parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.siansiansu.taigikeyboard.engine.proto.FrequencyEntry parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.siansiansu.taigikeyboard.engine.proto.FrequencyEntry parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.siansiansu.taigikeyboard.engine.proto.FrequencyEntry parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.siansiansu.taigikeyboard.engine.proto.FrequencyEntry parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.siansiansu.taigikeyboard.engine.proto.FrequencyEntry parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.siansiansu.taigikeyboard.engine.proto.FrequencyEntry parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static com.siansiansu.taigikeyboard.engine.proto.FrequencyEntry parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }

  public static com.siansiansu.taigikeyboard.engine.proto.FrequencyEntry parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static com.siansiansu.taigikeyboard.engine.proto.FrequencyEntry parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.siansiansu.taigikeyboard.engine.proto.FrequencyEntry parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }
  public static Builder newBuilder(com.siansiansu.taigikeyboard.engine.proto.FrequencyEntry prototype) {
    return DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * <pre>
   * `FrequencyEntry` is the per-candidate user-frequency snapshot. Caller
   * pre-filters to candidate-relevant keys to keep the request small.
   * `display_text_key` matches `TaigiWord.displayText` (= hanji ?? roman)
   * so the engine can `find` matching entries during scoring.
   *
   * v3.6.1 R5 — user-frequency identity is the `(display_text_key,
   * canonical_tl)` PAIR (Core Principle #7). `canonical_tl` is the
   * candidate's canonical-TL reading, snapshotted BEFORE the POJ-render
   * pass (= `RawCandidate.canonical_tl`). One `display_text` (e.g. 重) now
   * carries one entry PER reading (重/tîng vs 重/tāng), so 一字多音 keep
   * separate frequency buckets. `canonical_tl == ""` is the LEGACY sentinel
   * for pre-R5 rows / old-backup imports the platform could not re-key; the
   * engine treats it as a tolerant fallback bucket consulted by ALL readings
   * of that `display_text` until each is re-learned (see
   * `ranking::FrequencyMap::get`). Empty string is the canonical legacy
   * marker — the field is NOT `optional`.
   * </pre>
   *
   * Protobuf type {@code taigi.engine.FrequencyEntry}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        com.siansiansu.taigikeyboard.engine.proto.FrequencyEntry, Builder> implements
      // @@protoc_insertion_point(builder_implements:taigi.engine.FrequencyEntry)
      com.siansiansu.taigikeyboard.engine.proto.FrequencyEntryOrBuilder {
    // Construct using com.siansiansu.taigikeyboard.engine.proto.FrequencyEntry.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <code>string display_text_key = 1;</code>
     * @return The displayTextKey.
     */
    @java.lang.Override
    public java.lang.String getDisplayTextKey() {
      return instance.getDisplayTextKey();
    }
    /**
     * <code>string display_text_key = 1;</code>
     * @return The bytes for displayTextKey.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getDisplayTextKeyBytes() {
      return instance.getDisplayTextKeyBytes();
    }
    /**
     * <code>string display_text_key = 1;</code>
     * @param value The displayTextKey to set.
     * @return This builder for chaining.
     */
    public Builder setDisplayTextKey(
        java.lang.String value) {
      copyOnWrite();
      instance.setDisplayTextKey(value);
      return this;
    }
    /**
     * <code>string display_text_key = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearDisplayTextKey() {
      copyOnWrite();
      instance.clearDisplayTextKey();
      return this;
    }
    /**
     * <code>string display_text_key = 1;</code>
     * @param value The bytes for displayTextKey to set.
     * @return This builder for chaining.
     */
    public Builder setDisplayTextKeyBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setDisplayTextKeyBytes(value);
      return this;
    }

    /**
     * <code>uint32 count = 2;</code>
     * @return The count.
     */
    @java.lang.Override
    public int getCount() {
      return instance.getCount();
    }
    /**
     * <code>uint32 count = 2;</code>
     * @param value The count to set.
     * @return This builder for chaining.
     */
    public Builder setCount(int value) {
      copyOnWrite();
      instance.setCount(value);
      return this;
    }
    /**
     * <code>uint32 count = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearCount() {
      copyOnWrite();
      instance.clearCount();
      return this;
    }

    /**
     * <code>int64 last_used_ms = 3;</code>
     * @return The lastUsedMs.
     */
    @java.lang.Override
    public long getLastUsedMs() {
      return instance.getLastUsedMs();
    }
    /**
     * <code>int64 last_used_ms = 3;</code>
     * @param value The lastUsedMs to set.
     * @return This builder for chaining.
     */
    public Builder setLastUsedMs(long value) {
      copyOnWrite();
      instance.setLastUsedMs(value);
      return this;
    }
    /**
     * <code>int64 last_used_ms = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearLastUsedMs() {
      copyOnWrite();
      instance.clearLastUsedMs();
      return this;
    }

    /**
     * <code>string canonical_tl = 4;</code>
     * @return The canonicalTl.
     */
    @java.lang.Override
    public java.lang.String getCanonicalTl() {
      return instance.getCanonicalTl();
    }
    /**
     * <code>string canonical_tl = 4;</code>
     * @return The bytes for canonicalTl.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getCanonicalTlBytes() {
      return instance.getCanonicalTlBytes();
    }
    /**
     * <code>string canonical_tl = 4;</code>
     * @param value The canonicalTl to set.
     * @return This builder for chaining.
     */
    public Builder setCanonicalTl(
        java.lang.String value) {
      copyOnWrite();
      instance.setCanonicalTl(value);
      return this;
    }
    /**
     * <code>string canonical_tl = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearCanonicalTl() {
      copyOnWrite();
      instance.clearCanonicalTl();
      return this;
    }
    /**
     * <code>string canonical_tl = 4;</code>
     * @param value The bytes for canonicalTl to set.
     * @return This builder for chaining.
     */
    public Builder setCanonicalTlBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setCanonicalTlBytes(value);
      return this;
    }

    // @@protoc_insertion_point(builder_scope:taigi.engine.FrequencyEntry)
  }
  @java.lang.Override
  @java.lang.SuppressWarnings({"ThrowNull"})
  protected final java.lang.Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      java.lang.Object arg0, java.lang.Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new com.siansiansu.taigikeyboard.engine.proto.FrequencyEntry();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
          java.lang.Object[] objects = new java.lang.Object[] {
            "displayTextKey_",
            "count_",
            "lastUsedMs_",
            "canonicalTl_",
          };
          java.lang.String info =
              "\u0000\u0004\u0000\u0000\u0001\u0004\u0004\u0000\u0000\u0000\u0001\u0208\u0002\u000b" +
              "\u0003\u0002\u0004\u0208";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<com.siansiansu.taigikeyboard.engine.proto.FrequencyEntry> parser = PARSER;
        if (parser == null) {
          synchronized (com.siansiansu.taigikeyboard.engine.proto.FrequencyEntry.class) {
            parser = PARSER;
            if (parser == null) {
              parser =
                  new DefaultInstanceBasedParser<com.siansiansu.taigikeyboard.engine.proto.FrequencyEntry>(
                      DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      // SET_MEMOIZED_IS_INITIALIZED is never called for this message.
      // So it can do anything. Combine with default case for smaller codegen.
      case SET_MEMOIZED_IS_INITIALIZED:
    }
    // Should never happen. Generates tight code to throw an exception.
    throw null;
  }


  // @@protoc_insertion_point(class_scope:taigi.engine.FrequencyEntry)
  private static final com.siansiansu.taigikeyboard.engine.proto.FrequencyEntry DEFAULT_INSTANCE;
  static {
    FrequencyEntry defaultInstance = new FrequencyEntry();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
      FrequencyEntry.class, defaultInstance);
  }

  public static com.siansiansu.taigikeyboard.engine.proto.FrequencyEntry getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<FrequencyEntry> PARSER;

  public static com.google.protobuf.Parser<FrequencyEntry> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}
