// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: user_data.proto
// Protobuf Java Version: 4.36.2

package com.siansiansu.taigikeyboard.engine.proto;

/**
 * <pre>
 * A `roman,hanzi` CSV file's bytes, as the platform's file picker read them.
 * Rows already stored (same roman and Hanji) are skipped; the import stops
 * at the dictionary's cap without failing, so `imported` may be fewer than
 * the file's rows even with no refusal.
 * </pre>
 *
 * Protobuf type {@code taigi.engine.ImportCustomCsv}
 */
@com.google.protobuf.Generated
public  final class ImportCustomCsv extends
    com.google.protobuf.GeneratedMessageLite<
        ImportCustomCsv, ImportCustomCsv.Builder> implements
    // @@protoc_insertion_point(message_implements:taigi.engine.ImportCustomCsv)
    ImportCustomCsvOrBuilder {
  private ImportCustomCsv() {
    csv_ = com.google.protobuf.ByteString.EMPTY;
  }
  public static final int CSV_FIELD_NUMBER = 1;
  private com.google.protobuf.ByteString csv_;
  /**
   * <code>bytes csv = 1;</code>
   * @return The csv.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString getCsv() {
    return csv_;
  }
  /**
   * <code>bytes csv = 1;</code>
   * @param value The csv to set.
   */
  private void setCsv(com.google.protobuf.ByteString value) {
    java.util.Objects.requireNonNull(value);

    csv_ = value;
  }
  /**
   * <code>bytes csv = 1;</code>
   */
  private void clearCsv() {

    csv_ = getDefaultInstance().getCsv();
  }

  public static com.siansiansu.taigikeyboard.engine.proto.ImportCustomCsv parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.siansiansu.taigikeyboard.engine.proto.ImportCustomCsv parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.siansiansu.taigikeyboard.engine.proto.ImportCustomCsv parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.siansiansu.taigikeyboard.engine.proto.ImportCustomCsv parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.siansiansu.taigikeyboard.engine.proto.ImportCustomCsv parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.siansiansu.taigikeyboard.engine.proto.ImportCustomCsv parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.siansiansu.taigikeyboard.engine.proto.ImportCustomCsv parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.siansiansu.taigikeyboard.engine.proto.ImportCustomCsv parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static com.siansiansu.taigikeyboard.engine.proto.ImportCustomCsv parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }

  public static com.siansiansu.taigikeyboard.engine.proto.ImportCustomCsv parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static com.siansiansu.taigikeyboard.engine.proto.ImportCustomCsv parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.siansiansu.taigikeyboard.engine.proto.ImportCustomCsv parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }
  public static Builder newBuilder(com.siansiansu.taigikeyboard.engine.proto.ImportCustomCsv prototype) {
    return DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * <pre>
   * A `roman,hanzi` CSV file's bytes, as the platform's file picker read them.
   * Rows already stored (same roman and Hanji) are skipped; the import stops
   * at the dictionary's cap without failing, so `imported` may be fewer than
   * the file's rows even with no refusal.
   * </pre>
   *
   * Protobuf type {@code taigi.engine.ImportCustomCsv}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        com.siansiansu.taigikeyboard.engine.proto.ImportCustomCsv, Builder> implements
      // @@protoc_insertion_point(builder_implements:taigi.engine.ImportCustomCsv)
      com.siansiansu.taigikeyboard.engine.proto.ImportCustomCsvOrBuilder {
    // Construct using com.siansiansu.taigikeyboard.engine.proto.ImportCustomCsv.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <code>bytes csv = 1;</code>
     * @return The csv.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getCsv() {
      return instance.getCsv();
    }
    /**
     * <code>bytes csv = 1;</code>
     * @param value The csv to set.
     * @return This builder for chaining.
     */
    public Builder setCsv(com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setCsv(value);
      return this;
    }
    /**
     * <code>bytes csv = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearCsv() {
      copyOnWrite();
      instance.clearCsv();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:taigi.engine.ImportCustomCsv)
  }
  @java.lang.Override
  @java.lang.SuppressWarnings({"ThrowNull"})
  protected final java.lang.Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      java.lang.Object arg0, java.lang.Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new com.siansiansu.taigikeyboard.engine.proto.ImportCustomCsv();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
          java.lang.Object[] objects = new java.lang.Object[] {
            "csv_",
          };
          java.lang.String info =
              "\u0000\u0001\u0000\u0000\u0001\u0001\u0001\u0000\u0000\u0000\u0001\n";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<com.siansiansu.taigikeyboard.engine.proto.ImportCustomCsv> parser = PARSER;
        if (parser == null) {
          synchronized (com.siansiansu.taigikeyboard.engine.proto.ImportCustomCsv.class) {
            parser = PARSER;
            if (parser == null) {
              parser =
                  new DefaultInstanceBasedParser<com.siansiansu.taigikeyboard.engine.proto.ImportCustomCsv>(
                      DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      // SET_MEMOIZED_IS_INITIALIZED is never called for this message.
      // So it can do anything. Combine with default case for smaller codegen.
      case SET_MEMOIZED_IS_INITIALIZED:
    }
    // Should never happen. Generates tight code to throw an exception.
    throw null;
  }


  // @@protoc_insertion_point(class_scope:taigi.engine.ImportCustomCsv)
  private static final com.siansiansu.taigikeyboard.engine.proto.ImportCustomCsv DEFAULT_INSTANCE;
  static {
    ImportCustomCsv defaultInstance = new ImportCustomCsv();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
      ImportCustomCsv.class, defaultInstance);
  }

  public static com.siansiansu.taigikeyboard.engine.proto.ImportCustomCsv getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<ImportCustomCsv> PARSER;

  public static com.google.protobuf.Parser<ImportCustomCsv> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}
