// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: lexicon.proto
// Protobuf Java Version: 4.27.5

package com.siansiansu.taigikeyboard.engine.proto;

/**
 * <pre>
 * `InputType` is lexicon-local — only `SearchRequest` consumes it. Not
 * promoted to `envelope.proto` because no other module needs to classify
 * input by hanzi/roman/tone.
 * </pre>
 *
 * Protobuf enum {@code taigi.engine.InputType}
 */
public enum InputType
    implements com.google.protobuf.Internal.EnumLite {
  /**
   * <code>INPUT_TYPE_UNSPECIFIED = 0;</code>
   */
  INPUT_TYPE_UNSPECIFIED(0),
  /**
   * <code>INPUT_TYPE_ROMAN_NO_TONE = 1;</code>
   */
  INPUT_TYPE_ROMAN_NO_TONE(1),
  /**
   * <code>INPUT_TYPE_ROMAN_WITH_TONE = 2;</code>
   */
  INPUT_TYPE_ROMAN_WITH_TONE(2),
  /**
   * <code>INPUT_TYPE_HANZI = 3;</code>
   */
  INPUT_TYPE_HANZI(3),
  UNRECOGNIZED(-1),
  ;

  /**
   * <code>INPUT_TYPE_UNSPECIFIED = 0;</code>
   */
  public static final int INPUT_TYPE_UNSPECIFIED_VALUE = 0;
  /**
   * <code>INPUT_TYPE_ROMAN_NO_TONE = 1;</code>
   */
  public static final int INPUT_TYPE_ROMAN_NO_TONE_VALUE = 1;
  /**
   * <code>INPUT_TYPE_ROMAN_WITH_TONE = 2;</code>
   */
  public static final int INPUT_TYPE_ROMAN_WITH_TONE_VALUE = 2;
  /**
   * <code>INPUT_TYPE_HANZI = 3;</code>
   */
  public static final int INPUT_TYPE_HANZI_VALUE = 3;


  @java.lang.Override
  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @param value The number of the enum to look for.
   * @return The enum associated with the given number.
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static InputType valueOf(int value) {
    return forNumber(value);
  }

  public static InputType forNumber(int value) {
    switch (value) {
      case 0: return INPUT_TYPE_UNSPECIFIED;
      case 1: return INPUT_TYPE_ROMAN_NO_TONE;
      case 2: return INPUT_TYPE_ROMAN_WITH_TONE;
      case 3: return INPUT_TYPE_HANZI;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<InputType>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      InputType> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<InputType>() {
          @java.lang.Override
          public InputType findValueByNumber(int number) {
            return InputType.forNumber(number);
          }
        };

  public static com.google.protobuf.Internal.EnumVerifier 
      internalGetVerifier() {
    return InputTypeVerifier.INSTANCE;
  }

  private static final class InputTypeVerifier implements 
       com.google.protobuf.Internal.EnumVerifier { 
          static final com.google.protobuf.Internal.EnumVerifier           INSTANCE = new InputTypeVerifier();
          @java.lang.Override
          public boolean isInRange(int number) {
            return InputType.forNumber(number) != null;
          }
        };

  private final int value;

  private InputType(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:taigi.engine.InputType)
}

