// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: lexicon.proto
// Protobuf Java Version: 4.35.1

package com.siansiansu.taigikeyboard.engine.proto;

/**
 * <pre>
 * `InstallRequest` is the (idempotent) lexicon read-path bootstrap. The
 * platform passes absolute Bundle / filesDir paths; engine opens mmap'd
 * readers and the fst prefix index, validates magic bytes + versions, and
 * atomically swaps in the new `EngineState`. Reinstall (Android asset
 * version bump per audit D-9) reuses this method — same shape, the engine
 * is responsible for atomic-on-success swap; old state stays intact if any
 * step fails.
 *
 * Path validation: any NUL byte (`&#92;0`) or non-absolute path is rejected
 * with `LexiconError::InvalidPath` / `PathNotAbsolute` via the proto error
 * envelope. Engine NEVER panics on user-supplied paths.
 * </pre>
 *
 * Protobuf type {@code taigi.engine.InstallRequest}
 */
@com.google.protobuf.Generated
public  final class InstallRequest extends
    com.google.protobuf.GeneratedMessageLite<
        InstallRequest, InstallRequest.Builder> implements
    // @@protoc_insertion_point(message_implements:taigi.engine.InstallRequest)
    InstallRequestOrBuilder {
  private InstallRequest() {
    triePath_ = "";
    dictionaryBinPath_ = "";
    associationBinPath_ = "";
    syllableInventoryPath_ = "";
  }
  public static final int TRIE_PATH_FIELD_NUMBER = 1;
  private java.lang.String triePath_;
  /**
   * <pre>
   * absolute path to dictionary.fst
   * </pre>
   *
   * <code>string trie_path = 1;</code>
   * @return The triePath.
   */
  @java.lang.Override
  public java.lang.String getTriePath() {
    return triePath_;
  }
  /**
   * <pre>
   * absolute path to dictionary.fst
   * </pre>
   *
   * <code>string trie_path = 1;</code>
   * @return The bytes for triePath.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getTriePathBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(triePath_);
  }
  /**
   * <pre>
   * absolute path to dictionary.fst
   * </pre>
   *
   * <code>string trie_path = 1;</code>
   * @param value The triePath to set.
   */
  @java.lang.SuppressWarnings("ReturnValueIgnored")
  private void setTriePath(
      java.lang.String value) {
    value.getClass();  // minimal bytecode null check

    triePath_ = value;
  }
  /**
   * <pre>
   * absolute path to dictionary.fst
   * </pre>
   *
   * <code>string trie_path = 1;</code>
   */
  private void clearTriePath() {

    triePath_ = getDefaultInstance().getTriePath();
  }
  /**
   * <pre>
   * absolute path to dictionary.fst
   * </pre>
   *
   * <code>string trie_path = 1;</code>
   * @param value The bytes for triePath to set.
   */
  private void setTriePathBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    triePath_ = value.toStringUtf8();

  }

  public static final int DICTIONARY_BIN_PATH_FIELD_NUMBER = 2;
  private java.lang.String dictionaryBinPath_;
  /**
   * <pre>
   * absolute path to dictionary.bin (TKDB)
   * </pre>
   *
   * <code>string dictionary_bin_path = 2;</code>
   * @return The dictionaryBinPath.
   */
  @java.lang.Override
  public java.lang.String getDictionaryBinPath() {
    return dictionaryBinPath_;
  }
  /**
   * <pre>
   * absolute path to dictionary.bin (TKDB)
   * </pre>
   *
   * <code>string dictionary_bin_path = 2;</code>
   * @return The bytes for dictionaryBinPath.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getDictionaryBinPathBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(dictionaryBinPath_);
  }
  /**
   * <pre>
   * absolute path to dictionary.bin (TKDB)
   * </pre>
   *
   * <code>string dictionary_bin_path = 2;</code>
   * @param value The dictionaryBinPath to set.
   */
  @java.lang.SuppressWarnings("ReturnValueIgnored")
  private void setDictionaryBinPath(
      java.lang.String value) {
    value.getClass();  // minimal bytecode null check

    dictionaryBinPath_ = value;
  }
  /**
   * <pre>
   * absolute path to dictionary.bin (TKDB)
   * </pre>
   *
   * <code>string dictionary_bin_path = 2;</code>
   */
  private void clearDictionaryBinPath() {

    dictionaryBinPath_ = getDefaultInstance().getDictionaryBinPath();
  }
  /**
   * <pre>
   * absolute path to dictionary.bin (TKDB)
   * </pre>
   *
   * <code>string dictionary_bin_path = 2;</code>
   * @param value The bytes for dictionaryBinPath to set.
   */
  private void setDictionaryBinPathBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    dictionaryBinPath_ = value.toStringUtf8();

  }

  public static final int ASSOCIATION_BIN_PATH_FIELD_NUMBER = 3;
  private java.lang.String associationBinPath_;
  /**
   * <pre>
   * absolute path to association.bin (TKWA, bundled)
   * </pre>
   *
   * <code>string association_bin_path = 3;</code>
   * @return The associationBinPath.
   */
  @java.lang.Override
  public java.lang.String getAssociationBinPath() {
    return associationBinPath_;
  }
  /**
   * <pre>
   * absolute path to association.bin (TKWA, bundled)
   * </pre>
   *
   * <code>string association_bin_path = 3;</code>
   * @return The bytes for associationBinPath.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getAssociationBinPathBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(associationBinPath_);
  }
  /**
   * <pre>
   * absolute path to association.bin (TKWA, bundled)
   * </pre>
   *
   * <code>string association_bin_path = 3;</code>
   * @param value The associationBinPath to set.
   */
  @java.lang.SuppressWarnings("ReturnValueIgnored")
  private void setAssociationBinPath(
      java.lang.String value) {
    value.getClass();  // minimal bytecode null check

    associationBinPath_ = value;
  }
  /**
   * <pre>
   * absolute path to association.bin (TKWA, bundled)
   * </pre>
   *
   * <code>string association_bin_path = 3;</code>
   */
  private void clearAssociationBinPath() {

    associationBinPath_ = getDefaultInstance().getAssociationBinPath();
  }
  /**
   * <pre>
   * absolute path to association.bin (TKWA, bundled)
   * </pre>
   *
   * <code>string association_bin_path = 3;</code>
   * @param value The bytes for associationBinPath to set.
   */
  private void setAssociationBinPathBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    associationBinPath_ = value.toStringUtf8();

  }

  public static final int DICTIONARY_VERSION_FIELD_NUMBER = 4;
  private int dictionaryVersion_;
  /**
   * <pre>
   * platform-supplied stamp (Android: dictionary_app_version.txt; iOS: bundle build number)
   * </pre>
   *
   * <code>uint32 dictionary_version = 4;</code>
   * @return The dictionaryVersion.
   */
  @java.lang.Override
  public int getDictionaryVersion() {
    return dictionaryVersion_;
  }
  /**
   * <pre>
   * platform-supplied stamp (Android: dictionary_app_version.txt; iOS: bundle build number)
   * </pre>
   *
   * <code>uint32 dictionary_version = 4;</code>
   * @param value The dictionaryVersion to set.
   */
  private void setDictionaryVersion(int value) {

    dictionaryVersion_ = value;
  }
  /**
   * <pre>
   * platform-supplied stamp (Android: dictionary_app_version.txt; iOS: bundle build number)
   * </pre>
   *
   * <code>uint32 dictionary_version = 4;</code>
   */
  private void clearDictionaryVersion() {

    dictionaryVersion_ = 0;
  }

  public static final int SYLLABLE_INVENTORY_PATH_FIELD_NUMBER = 5;
  private java.lang.String syllableInventoryPath_;
  /**
   * <pre>
   * v3.5.8 Phase 6 — absolute path to `syllables.fst` (Phase-2 TL syllable
   * inventory). Optional on the wire: empty string skips loading and
   * `EngineState.syllable_inventory` stays `None`. Phase 7 / 8 platform
   * bundles populate this; Phase 6 only wires the field through so the
   * composing dispatch can call `tl::valid_span_endings` against the
   * installed inventory once the platform pipeline is ready.
   * </pre>
   *
   * <code>string syllable_inventory_path = 5;</code>
   * @return The syllableInventoryPath.
   */
  @java.lang.Override
  public java.lang.String getSyllableInventoryPath() {
    return syllableInventoryPath_;
  }
  /**
   * <pre>
   * v3.5.8 Phase 6 — absolute path to `syllables.fst` (Phase-2 TL syllable
   * inventory). Optional on the wire: empty string skips loading and
   * `EngineState.syllable_inventory` stays `None`. Phase 7 / 8 platform
   * bundles populate this; Phase 6 only wires the field through so the
   * composing dispatch can call `tl::valid_span_endings` against the
   * installed inventory once the platform pipeline is ready.
   * </pre>
   *
   * <code>string syllable_inventory_path = 5;</code>
   * @return The bytes for syllableInventoryPath.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getSyllableInventoryPathBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(syllableInventoryPath_);
  }
  /**
   * <pre>
   * v3.5.8 Phase 6 — absolute path to `syllables.fst` (Phase-2 TL syllable
   * inventory). Optional on the wire: empty string skips loading and
   * `EngineState.syllable_inventory` stays `None`. Phase 7 / 8 platform
   * bundles populate this; Phase 6 only wires the field through so the
   * composing dispatch can call `tl::valid_span_endings` against the
   * installed inventory once the platform pipeline is ready.
   * </pre>
   *
   * <code>string syllable_inventory_path = 5;</code>
   * @param value The syllableInventoryPath to set.
   */
  @java.lang.SuppressWarnings("ReturnValueIgnored")
  private void setSyllableInventoryPath(
      java.lang.String value) {
    value.getClass();  // minimal bytecode null check

    syllableInventoryPath_ = value;
  }
  /**
   * <pre>
   * v3.5.8 Phase 6 — absolute path to `syllables.fst` (Phase-2 TL syllable
   * inventory). Optional on the wire: empty string skips loading and
   * `EngineState.syllable_inventory` stays `None`. Phase 7 / 8 platform
   * bundles populate this; Phase 6 only wires the field through so the
   * composing dispatch can call `tl::valid_span_endings` against the
   * installed inventory once the platform pipeline is ready.
   * </pre>
   *
   * <code>string syllable_inventory_path = 5;</code>
   */
  private void clearSyllableInventoryPath() {

    syllableInventoryPath_ = getDefaultInstance().getSyllableInventoryPath();
  }
  /**
   * <pre>
   * v3.5.8 Phase 6 — absolute path to `syllables.fst` (Phase-2 TL syllable
   * inventory). Optional on the wire: empty string skips loading and
   * `EngineState.syllable_inventory` stays `None`. Phase 7 / 8 platform
   * bundles populate this; Phase 6 only wires the field through so the
   * composing dispatch can call `tl::valid_span_endings` against the
   * installed inventory once the platform pipeline is ready.
   * </pre>
   *
   * <code>string syllable_inventory_path = 5;</code>
   * @param value The bytes for syllableInventoryPath to set.
   */
  private void setSyllableInventoryPathBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    syllableInventoryPath_ = value.toStringUtf8();

  }

  public static com.siansiansu.taigikeyboard.engine.proto.InstallRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.siansiansu.taigikeyboard.engine.proto.InstallRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.siansiansu.taigikeyboard.engine.proto.InstallRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.siansiansu.taigikeyboard.engine.proto.InstallRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.siansiansu.taigikeyboard.engine.proto.InstallRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.siansiansu.taigikeyboard.engine.proto.InstallRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.siansiansu.taigikeyboard.engine.proto.InstallRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.siansiansu.taigikeyboard.engine.proto.InstallRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static com.siansiansu.taigikeyboard.engine.proto.InstallRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }

  public static com.siansiansu.taigikeyboard.engine.proto.InstallRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static com.siansiansu.taigikeyboard.engine.proto.InstallRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.siansiansu.taigikeyboard.engine.proto.InstallRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }
  public static Builder newBuilder(com.siansiansu.taigikeyboard.engine.proto.InstallRequest prototype) {
    return DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * <pre>
   * `InstallRequest` is the (idempotent) lexicon read-path bootstrap. The
   * platform passes absolute Bundle / filesDir paths; engine opens mmap'd
   * readers and the fst prefix index, validates magic bytes + versions, and
   * atomically swaps in the new `EngineState`. Reinstall (Android asset
   * version bump per audit D-9) reuses this method — same shape, the engine
   * is responsible for atomic-on-success swap; old state stays intact if any
   * step fails.
   *
   * Path validation: any NUL byte (`&#92;0`) or non-absolute path is rejected
   * with `LexiconError::InvalidPath` / `PathNotAbsolute` via the proto error
   * envelope. Engine NEVER panics on user-supplied paths.
   * </pre>
   *
   * Protobuf type {@code taigi.engine.InstallRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        com.siansiansu.taigikeyboard.engine.proto.InstallRequest, Builder> implements
      // @@protoc_insertion_point(builder_implements:taigi.engine.InstallRequest)
      com.siansiansu.taigikeyboard.engine.proto.InstallRequestOrBuilder {
    // Construct using com.siansiansu.taigikeyboard.engine.proto.InstallRequest.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <pre>
     * absolute path to dictionary.fst
     * </pre>
     *
     * <code>string trie_path = 1;</code>
     * @return The triePath.
     */
    @java.lang.Override
    public java.lang.String getTriePath() {
      return instance.getTriePath();
    }
    /**
     * <pre>
     * absolute path to dictionary.fst
     * </pre>
     *
     * <code>string trie_path = 1;</code>
     * @return The bytes for triePath.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getTriePathBytes() {
      return instance.getTriePathBytes();
    }
    /**
     * <pre>
     * absolute path to dictionary.fst
     * </pre>
     *
     * <code>string trie_path = 1;</code>
     * @param value The triePath to set.
     * @return This builder for chaining.
     */
    public Builder setTriePath(
        java.lang.String value) {
      copyOnWrite();
      instance.setTriePath(value);
      return this;
    }
    /**
     * <pre>
     * absolute path to dictionary.fst
     * </pre>
     *
     * <code>string trie_path = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearTriePath() {
      copyOnWrite();
      instance.clearTriePath();
      return this;
    }
    /**
     * <pre>
     * absolute path to dictionary.fst
     * </pre>
     *
     * <code>string trie_path = 1;</code>
     * @param value The bytes for triePath to set.
     * @return This builder for chaining.
     */
    public Builder setTriePathBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setTriePathBytes(value);
      return this;
    }

    /**
     * <pre>
     * absolute path to dictionary.bin (TKDB)
     * </pre>
     *
     * <code>string dictionary_bin_path = 2;</code>
     * @return The dictionaryBinPath.
     */
    @java.lang.Override
    public java.lang.String getDictionaryBinPath() {
      return instance.getDictionaryBinPath();
    }
    /**
     * <pre>
     * absolute path to dictionary.bin (TKDB)
     * </pre>
     *
     * <code>string dictionary_bin_path = 2;</code>
     * @return The bytes for dictionaryBinPath.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getDictionaryBinPathBytes() {
      return instance.getDictionaryBinPathBytes();
    }
    /**
     * <pre>
     * absolute path to dictionary.bin (TKDB)
     * </pre>
     *
     * <code>string dictionary_bin_path = 2;</code>
     * @param value The dictionaryBinPath to set.
     * @return This builder for chaining.
     */
    public Builder setDictionaryBinPath(
        java.lang.String value) {
      copyOnWrite();
      instance.setDictionaryBinPath(value);
      return this;
    }
    /**
     * <pre>
     * absolute path to dictionary.bin (TKDB)
     * </pre>
     *
     * <code>string dictionary_bin_path = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearDictionaryBinPath() {
      copyOnWrite();
      instance.clearDictionaryBinPath();
      return this;
    }
    /**
     * <pre>
     * absolute path to dictionary.bin (TKDB)
     * </pre>
     *
     * <code>string dictionary_bin_path = 2;</code>
     * @param value The bytes for dictionaryBinPath to set.
     * @return This builder for chaining.
     */
    public Builder setDictionaryBinPathBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setDictionaryBinPathBytes(value);
      return this;
    }

    /**
     * <pre>
     * absolute path to association.bin (TKWA, bundled)
     * </pre>
     *
     * <code>string association_bin_path = 3;</code>
     * @return The associationBinPath.
     */
    @java.lang.Override
    public java.lang.String getAssociationBinPath() {
      return instance.getAssociationBinPath();
    }
    /**
     * <pre>
     * absolute path to association.bin (TKWA, bundled)
     * </pre>
     *
     * <code>string association_bin_path = 3;</code>
     * @return The bytes for associationBinPath.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getAssociationBinPathBytes() {
      return instance.getAssociationBinPathBytes();
    }
    /**
     * <pre>
     * absolute path to association.bin (TKWA, bundled)
     * </pre>
     *
     * <code>string association_bin_path = 3;</code>
     * @param value The associationBinPath to set.
     * @return This builder for chaining.
     */
    public Builder setAssociationBinPath(
        java.lang.String value) {
      copyOnWrite();
      instance.setAssociationBinPath(value);
      return this;
    }
    /**
     * <pre>
     * absolute path to association.bin (TKWA, bundled)
     * </pre>
     *
     * <code>string association_bin_path = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearAssociationBinPath() {
      copyOnWrite();
      instance.clearAssociationBinPath();
      return this;
    }
    /**
     * <pre>
     * absolute path to association.bin (TKWA, bundled)
     * </pre>
     *
     * <code>string association_bin_path = 3;</code>
     * @param value The bytes for associationBinPath to set.
     * @return This builder for chaining.
     */
    public Builder setAssociationBinPathBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setAssociationBinPathBytes(value);
      return this;
    }

    /**
     * <pre>
     * platform-supplied stamp (Android: dictionary_app_version.txt; iOS: bundle build number)
     * </pre>
     *
     * <code>uint32 dictionary_version = 4;</code>
     * @return The dictionaryVersion.
     */
    @java.lang.Override
    public int getDictionaryVersion() {
      return instance.getDictionaryVersion();
    }
    /**
     * <pre>
     * platform-supplied stamp (Android: dictionary_app_version.txt; iOS: bundle build number)
     * </pre>
     *
     * <code>uint32 dictionary_version = 4;</code>
     * @param value The dictionaryVersion to set.
     * @return This builder for chaining.
     */
    public Builder setDictionaryVersion(int value) {
      copyOnWrite();
      instance.setDictionaryVersion(value);
      return this;
    }
    /**
     * <pre>
     * platform-supplied stamp (Android: dictionary_app_version.txt; iOS: bundle build number)
     * </pre>
     *
     * <code>uint32 dictionary_version = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearDictionaryVersion() {
      copyOnWrite();
      instance.clearDictionaryVersion();
      return this;
    }

    /**
     * <pre>
     * v3.5.8 Phase 6 — absolute path to `syllables.fst` (Phase-2 TL syllable
     * inventory). Optional on the wire: empty string skips loading and
     * `EngineState.syllable_inventory` stays `None`. Phase 7 / 8 platform
     * bundles populate this; Phase 6 only wires the field through so the
     * composing dispatch can call `tl::valid_span_endings` against the
     * installed inventory once the platform pipeline is ready.
     * </pre>
     *
     * <code>string syllable_inventory_path = 5;</code>
     * @return The syllableInventoryPath.
     */
    @java.lang.Override
    public java.lang.String getSyllableInventoryPath() {
      return instance.getSyllableInventoryPath();
    }
    /**
     * <pre>
     * v3.5.8 Phase 6 — absolute path to `syllables.fst` (Phase-2 TL syllable
     * inventory). Optional on the wire: empty string skips loading and
     * `EngineState.syllable_inventory` stays `None`. Phase 7 / 8 platform
     * bundles populate this; Phase 6 only wires the field through so the
     * composing dispatch can call `tl::valid_span_endings` against the
     * installed inventory once the platform pipeline is ready.
     * </pre>
     *
     * <code>string syllable_inventory_path = 5;</code>
     * @return The bytes for syllableInventoryPath.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getSyllableInventoryPathBytes() {
      return instance.getSyllableInventoryPathBytes();
    }
    /**
     * <pre>
     * v3.5.8 Phase 6 — absolute path to `syllables.fst` (Phase-2 TL syllable
     * inventory). Optional on the wire: empty string skips loading and
     * `EngineState.syllable_inventory` stays `None`. Phase 7 / 8 platform
     * bundles populate this; Phase 6 only wires the field through so the
     * composing dispatch can call `tl::valid_span_endings` against the
     * installed inventory once the platform pipeline is ready.
     * </pre>
     *
     * <code>string syllable_inventory_path = 5;</code>
     * @param value The syllableInventoryPath to set.
     * @return This builder for chaining.
     */
    public Builder setSyllableInventoryPath(
        java.lang.String value) {
      copyOnWrite();
      instance.setSyllableInventoryPath(value);
      return this;
    }
    /**
     * <pre>
     * v3.5.8 Phase 6 — absolute path to `syllables.fst` (Phase-2 TL syllable
     * inventory). Optional on the wire: empty string skips loading and
     * `EngineState.syllable_inventory` stays `None`. Phase 7 / 8 platform
     * bundles populate this; Phase 6 only wires the field through so the
     * composing dispatch can call `tl::valid_span_endings` against the
     * installed inventory once the platform pipeline is ready.
     * </pre>
     *
     * <code>string syllable_inventory_path = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearSyllableInventoryPath() {
      copyOnWrite();
      instance.clearSyllableInventoryPath();
      return this;
    }
    /**
     * <pre>
     * v3.5.8 Phase 6 — absolute path to `syllables.fst` (Phase-2 TL syllable
     * inventory). Optional on the wire: empty string skips loading and
     * `EngineState.syllable_inventory` stays `None`. Phase 7 / 8 platform
     * bundles populate this; Phase 6 only wires the field through so the
     * composing dispatch can call `tl::valid_span_endings` against the
     * installed inventory once the platform pipeline is ready.
     * </pre>
     *
     * <code>string syllable_inventory_path = 5;</code>
     * @param value The bytes for syllableInventoryPath to set.
     * @return This builder for chaining.
     */
    public Builder setSyllableInventoryPathBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setSyllableInventoryPathBytes(value);
      return this;
    }

    // @@protoc_insertion_point(builder_scope:taigi.engine.InstallRequest)
  }
  @java.lang.Override
  @java.lang.SuppressWarnings({"ThrowNull"})
  protected final java.lang.Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      java.lang.Object arg0, java.lang.Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new com.siansiansu.taigikeyboard.engine.proto.InstallRequest();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
          java.lang.Object[] objects = new java.lang.Object[] {
            "triePath_",
            "dictionaryBinPath_",
            "associationBinPath_",
            "dictionaryVersion_",
            "syllableInventoryPath_",
          };
          java.lang.String info =
              "\u0000\u0005\u0000\u0000\u0001\u0005\u0005\u0000\u0000\u0000\u0001\u0208\u0002\u0208" +
              "\u0003\u0208\u0004\u000b\u0005\u0208";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<com.siansiansu.taigikeyboard.engine.proto.InstallRequest> parser = PARSER;
        if (parser == null) {
          synchronized (com.siansiansu.taigikeyboard.engine.proto.InstallRequest.class) {
            parser = PARSER;
            if (parser == null) {
              parser =
                  new DefaultInstanceBasedParser<com.siansiansu.taigikeyboard.engine.proto.InstallRequest>(
                      DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      // SET_MEMOIZED_IS_INITIALIZED is never called for this message.
      // So it can do anything. Combine with default case for smaller codegen.
      case SET_MEMOIZED_IS_INITIALIZED:
    }
    // Should never happen. Generates tight code to throw an exception.
    throw null;
  }


  // @@protoc_insertion_point(class_scope:taigi.engine.InstallRequest)
  private static final com.siansiansu.taigikeyboard.engine.proto.InstallRequest DEFAULT_INSTANCE;
  static {
    InstallRequest defaultInstance = new InstallRequest();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
      InstallRequest.class, defaultInstance);
  }

  public static com.siansiansu.taigikeyboard.engine.proto.InstallRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<InstallRequest> PARSER;

  public static com.google.protobuf.Parser<InstallRequest> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}
