// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: lexicon.proto
// Protobuf Java Version: 4.27.5

package com.siansiansu.taigikeyboard.engine.proto;

/**
 * <pre>
 * `InstallResponse` carries diagnostic counts. Platform diagnostic surfaces
 * log these to confirm install success.
 * </pre>
 *
 * Protobuf type {@code taigi.engine.InstallResponse}
 */
public  final class InstallResponse extends
    com.google.protobuf.GeneratedMessageLite<
        InstallResponse, InstallResponse.Builder> implements
    // @@protoc_insertion_point(message_implements:taigi.engine.InstallResponse)
    InstallResponseOrBuilder {
  private InstallResponse() {
  }
  public static final int DICTIONARY_RECORD_COUNT_FIELD_NUMBER = 1;
  private long dictionaryRecordCount_;
  /**
   * <code>uint64 dictionary_record_count = 1;</code>
   * @return The dictionaryRecordCount.
   */
  @java.lang.Override
  public long getDictionaryRecordCount() {
    return dictionaryRecordCount_;
  }
  /**
   * <code>uint64 dictionary_record_count = 1;</code>
   * @param value The dictionaryRecordCount to set.
   */
  private void setDictionaryRecordCount(long value) {
    
    dictionaryRecordCount_ = value;
  }
  /**
   * <code>uint64 dictionary_record_count = 1;</code>
   */
  private void clearDictionaryRecordCount() {

    dictionaryRecordCount_ = 0L;
  }

  public static final int PREFIX_INDEX_ENTRY_COUNT_FIELD_NUMBER = 2;
  private long prefixIndexEntryCount_;
  /**
   * <code>uint64 prefix_index_entry_count = 2;</code>
   * @return The prefixIndexEntryCount.
   */
  @java.lang.Override
  public long getPrefixIndexEntryCount() {
    return prefixIndexEntryCount_;
  }
  /**
   * <code>uint64 prefix_index_entry_count = 2;</code>
   * @param value The prefixIndexEntryCount to set.
   */
  private void setPrefixIndexEntryCount(long value) {
    
    prefixIndexEntryCount_ = value;
  }
  /**
   * <code>uint64 prefix_index_entry_count = 2;</code>
   */
  private void clearPrefixIndexEntryCount() {

    prefixIndexEntryCount_ = 0L;
  }

  public static com.siansiansu.taigikeyboard.engine.proto.InstallResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.siansiansu.taigikeyboard.engine.proto.InstallResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.siansiansu.taigikeyboard.engine.proto.InstallResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.siansiansu.taigikeyboard.engine.proto.InstallResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.siansiansu.taigikeyboard.engine.proto.InstallResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.siansiansu.taigikeyboard.engine.proto.InstallResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.siansiansu.taigikeyboard.engine.proto.InstallResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.siansiansu.taigikeyboard.engine.proto.InstallResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static com.siansiansu.taigikeyboard.engine.proto.InstallResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }

  public static com.siansiansu.taigikeyboard.engine.proto.InstallResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static com.siansiansu.taigikeyboard.engine.proto.InstallResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.siansiansu.taigikeyboard.engine.proto.InstallResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }
  public static Builder newBuilder(com.siansiansu.taigikeyboard.engine.proto.InstallResponse prototype) {
    return DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * <pre>
   * `InstallResponse` carries diagnostic counts. Platform diagnostic surfaces
   * log these to confirm install success.
   * </pre>
   *
   * Protobuf type {@code taigi.engine.InstallResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        com.siansiansu.taigikeyboard.engine.proto.InstallResponse, Builder> implements
      // @@protoc_insertion_point(builder_implements:taigi.engine.InstallResponse)
      com.siansiansu.taigikeyboard.engine.proto.InstallResponseOrBuilder {
    // Construct using com.siansiansu.taigikeyboard.engine.proto.InstallResponse.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <code>uint64 dictionary_record_count = 1;</code>
     * @return The dictionaryRecordCount.
     */
    @java.lang.Override
    public long getDictionaryRecordCount() {
      return instance.getDictionaryRecordCount();
    }
    /**
     * <code>uint64 dictionary_record_count = 1;</code>
     * @param value The dictionaryRecordCount to set.
     * @return This builder for chaining.
     */
    public Builder setDictionaryRecordCount(long value) {
      copyOnWrite();
      instance.setDictionaryRecordCount(value);
      return this;
    }
    /**
     * <code>uint64 dictionary_record_count = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearDictionaryRecordCount() {
      copyOnWrite();
      instance.clearDictionaryRecordCount();
      return this;
    }

    /**
     * <code>uint64 prefix_index_entry_count = 2;</code>
     * @return The prefixIndexEntryCount.
     */
    @java.lang.Override
    public long getPrefixIndexEntryCount() {
      return instance.getPrefixIndexEntryCount();
    }
    /**
     * <code>uint64 prefix_index_entry_count = 2;</code>
     * @param value The prefixIndexEntryCount to set.
     * @return This builder for chaining.
     */
    public Builder setPrefixIndexEntryCount(long value) {
      copyOnWrite();
      instance.setPrefixIndexEntryCount(value);
      return this;
    }
    /**
     * <code>uint64 prefix_index_entry_count = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearPrefixIndexEntryCount() {
      copyOnWrite();
      instance.clearPrefixIndexEntryCount();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:taigi.engine.InstallResponse)
  }
  @java.lang.Override
  @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
  protected final java.lang.Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      java.lang.Object arg0, java.lang.Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new com.siansiansu.taigikeyboard.engine.proto.InstallResponse();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
          java.lang.Object[] objects = new java.lang.Object[] {
            "dictionaryRecordCount_",
            "prefixIndexEntryCount_",
          };
          java.lang.String info =
              "\u0000\u0002\u0000\u0000\u0001\u0002\u0002\u0000\u0000\u0000\u0001\u0003\u0002\u0003" +
              "";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      // fall through
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<com.siansiansu.taigikeyboard.engine.proto.InstallResponse> parser = PARSER;
        if (parser == null) {
          synchronized (com.siansiansu.taigikeyboard.engine.proto.InstallResponse.class) {
            parser = PARSER;
            if (parser == null) {
              parser =
                  new DefaultInstanceBasedParser<com.siansiansu.taigikeyboard.engine.proto.InstallResponse>(
                      DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
    }
    case GET_MEMOIZED_IS_INITIALIZED: {
      return (byte) 1;
    }
    case SET_MEMOIZED_IS_INITIALIZED: {
      return null;
    }
    }
    throw new UnsupportedOperationException();
  }


  // @@protoc_insertion_point(class_scope:taigi.engine.InstallResponse)
  private static final com.siansiansu.taigikeyboard.engine.proto.InstallResponse DEFAULT_INSTANCE;
  static {
    InstallResponse defaultInstance = new InstallResponse();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
      InstallResponse.class, defaultInstance);
  }

  public static com.siansiansu.taigikeyboard.engine.proto.InstallResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<InstallResponse> PARSER;

  public static com.google.protobuf.Parser<InstallResponse> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

