// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: lexicon.proto
// Protobuf Java Version: 4.36.0

package com.siansiansu.taigikeyboard.engine.proto;

/**
 * Protobuf type {@code taigi.engine.LexiconResponse}
 */
@com.google.protobuf.Generated
public  final class LexiconResponse extends
    com.google.protobuf.GeneratedMessageLite<
        LexiconResponse, LexiconResponse.Builder> implements
    // @@protoc_insertion_point(message_implements:taigi.engine.LexiconResponse)
    LexiconResponseOrBuilder {
  private LexiconResponse() {
  }
  private int resultCase_ = 0;
  private java.lang.Object result_;
  public enum ResultCase
      implements com.google.protobuf.AbstractMessageLite.InternalOneOfEnum {
    PROCESS_CANDIDATES_RESULT(10),
    INSTALL_RESULT(11),
    SEARCH_RESULT(12),
    SEARCH_WITH_SOURCES_RESULT(13),
    SEARCH_BY_HANZI_RESULT(14),
    ASSOC_LOOKUP_RESULT(15),
    CLASSIFY_INPUT_RESULT(16),
    IS_HANZI_RESULT(17),
    DICTIONARY_FILTERS_RESULT(18),
    RESULT_NOT_SET(0);
    private final int value;
    private ResultCase(int value) {
      this.value = value;
    }
    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static ResultCase valueOf(int value) {
      return forNumber(value);
    }

    public static ResultCase forNumber(int value) {
      switch (value) {
        case 10: return PROCESS_CANDIDATES_RESULT;
        case 11: return INSTALL_RESULT;
        case 12: return SEARCH_RESULT;
        case 13: return SEARCH_WITH_SOURCES_RESULT;
        case 14: return SEARCH_BY_HANZI_RESULT;
        case 15: return ASSOC_LOOKUP_RESULT;
        case 16: return CLASSIFY_INPUT_RESULT;
        case 17: return IS_HANZI_RESULT;
        case 18: return DICTIONARY_FILTERS_RESULT;
        case 0: return RESULT_NOT_SET;
        default: return null;
      }
    }
    @java.lang.Override public int getNumber() {
      return this.value;
    }
  };

  @java.lang.Override
  public ResultCase
  getResultCase() {
    return ResultCase.forNumber(
        resultCase_);
  }

  private void clearResult() {
    resultCase_ = 0;
    result_ = null;
  }

  public static final int PROCESS_CANDIDATES_RESULT_FIELD_NUMBER = 10;
  /**
   * <code>.taigi.engine.ProcessCandidatesResponse process_candidates_result = 10;</code>
   */
  @java.lang.Override
  public boolean hasProcessCandidatesResult() {
    return resultCase_ == 10;
  }
  /**
   * <code>.taigi.engine.ProcessCandidatesResponse process_candidates_result = 10;</code>
   */
  @java.lang.Override
  public com.siansiansu.taigikeyboard.engine.proto.ProcessCandidatesResponse getProcessCandidatesResult() {
    if (resultCase_ == 10) {
       return (com.siansiansu.taigikeyboard.engine.proto.ProcessCandidatesResponse) result_;
    }
    return com.siansiansu.taigikeyboard.engine.proto.ProcessCandidatesResponse.getDefaultInstance();
  }
  /**
   * <code>.taigi.engine.ProcessCandidatesResponse process_candidates_result = 10;</code>
   */
  private void setProcessCandidatesResult(com.siansiansu.taigikeyboard.engine.proto.ProcessCandidatesResponse value) {
    java.util.Objects.requireNonNull(value);
    result_ = value;
    resultCase_ = 10;
  }
  /**
   * <code>.taigi.engine.ProcessCandidatesResponse process_candidates_result = 10;</code>
   */
  private void mergeProcessCandidatesResult(com.siansiansu.taigikeyboard.engine.proto.ProcessCandidatesResponse value) {
    java.util.Objects.requireNonNull(value);
    if (resultCase_ == 10 &&
        result_ != com.siansiansu.taigikeyboard.engine.proto.ProcessCandidatesResponse.getDefaultInstance()) {
      result_ = com.siansiansu.taigikeyboard.engine.proto.ProcessCandidatesResponse.newBuilder((com.siansiansu.taigikeyboard.engine.proto.ProcessCandidatesResponse) result_)
          .mergeFrom(value).buildPartial();
    } else {
      result_ = value;
    }
    resultCase_ = 10;
  }
  /**
   * <code>.taigi.engine.ProcessCandidatesResponse process_candidates_result = 10;</code>
   */
  private void clearProcessCandidatesResult() {
    if (resultCase_ == 10) {
      resultCase_ = 0;
      result_ = null;
    }
  }

  public static final int INSTALL_RESULT_FIELD_NUMBER = 11;
  /**
   * <code>.taigi.engine.InstallResponse install_result = 11;</code>
   */
  @java.lang.Override
  public boolean hasInstallResult() {
    return resultCase_ == 11;
  }
  /**
   * <code>.taigi.engine.InstallResponse install_result = 11;</code>
   */
  @java.lang.Override
  public com.siansiansu.taigikeyboard.engine.proto.InstallResponse getInstallResult() {
    if (resultCase_ == 11) {
       return (com.siansiansu.taigikeyboard.engine.proto.InstallResponse) result_;
    }
    return com.siansiansu.taigikeyboard.engine.proto.InstallResponse.getDefaultInstance();
  }
  /**
   * <code>.taigi.engine.InstallResponse install_result = 11;</code>
   */
  private void setInstallResult(com.siansiansu.taigikeyboard.engine.proto.InstallResponse value) {
    java.util.Objects.requireNonNull(value);
    result_ = value;
    resultCase_ = 11;
  }
  /**
   * <code>.taigi.engine.InstallResponse install_result = 11;</code>
   */
  private void mergeInstallResult(com.siansiansu.taigikeyboard.engine.proto.InstallResponse value) {
    java.util.Objects.requireNonNull(value);
    if (resultCase_ == 11 &&
        result_ != com.siansiansu.taigikeyboard.engine.proto.InstallResponse.getDefaultInstance()) {
      result_ = com.siansiansu.taigikeyboard.engine.proto.InstallResponse.newBuilder((com.siansiansu.taigikeyboard.engine.proto.InstallResponse) result_)
          .mergeFrom(value).buildPartial();
    } else {
      result_ = value;
    }
    resultCase_ = 11;
  }
  /**
   * <code>.taigi.engine.InstallResponse install_result = 11;</code>
   */
  private void clearInstallResult() {
    if (resultCase_ == 11) {
      resultCase_ = 0;
      result_ = null;
    }
  }

  public static final int SEARCH_RESULT_FIELD_NUMBER = 12;
  /**
   * <code>.taigi.engine.SearchResponse search_result = 12;</code>
   */
  @java.lang.Override
  public boolean hasSearchResult() {
    return resultCase_ == 12;
  }
  /**
   * <code>.taigi.engine.SearchResponse search_result = 12;</code>
   */
  @java.lang.Override
  public com.siansiansu.taigikeyboard.engine.proto.SearchResponse getSearchResult() {
    if (resultCase_ == 12) {
       return (com.siansiansu.taigikeyboard.engine.proto.SearchResponse) result_;
    }
    return com.siansiansu.taigikeyboard.engine.proto.SearchResponse.getDefaultInstance();
  }
  /**
   * <code>.taigi.engine.SearchResponse search_result = 12;</code>
   */
  private void setSearchResult(com.siansiansu.taigikeyboard.engine.proto.SearchResponse value) {
    java.util.Objects.requireNonNull(value);
    result_ = value;
    resultCase_ = 12;
  }
  /**
   * <code>.taigi.engine.SearchResponse search_result = 12;</code>
   */
  private void mergeSearchResult(com.siansiansu.taigikeyboard.engine.proto.SearchResponse value) {
    java.util.Objects.requireNonNull(value);
    if (resultCase_ == 12 &&
        result_ != com.siansiansu.taigikeyboard.engine.proto.SearchResponse.getDefaultInstance()) {
      result_ = com.siansiansu.taigikeyboard.engine.proto.SearchResponse.newBuilder((com.siansiansu.taigikeyboard.engine.proto.SearchResponse) result_)
          .mergeFrom(value).buildPartial();
    } else {
      result_ = value;
    }
    resultCase_ = 12;
  }
  /**
   * <code>.taigi.engine.SearchResponse search_result = 12;</code>
   */
  private void clearSearchResult() {
    if (resultCase_ == 12) {
      resultCase_ = 0;
      result_ = null;
    }
  }

  public static final int SEARCH_WITH_SOURCES_RESULT_FIELD_NUMBER = 13;
  /**
   * <code>.taigi.engine.SearchWithSourcesResponse search_with_sources_result = 13;</code>
   */
  @java.lang.Override
  public boolean hasSearchWithSourcesResult() {
    return resultCase_ == 13;
  }
  /**
   * <code>.taigi.engine.SearchWithSourcesResponse search_with_sources_result = 13;</code>
   */
  @java.lang.Override
  public com.siansiansu.taigikeyboard.engine.proto.SearchWithSourcesResponse getSearchWithSourcesResult() {
    if (resultCase_ == 13) {
       return (com.siansiansu.taigikeyboard.engine.proto.SearchWithSourcesResponse) result_;
    }
    return com.siansiansu.taigikeyboard.engine.proto.SearchWithSourcesResponse.getDefaultInstance();
  }
  /**
   * <code>.taigi.engine.SearchWithSourcesResponse search_with_sources_result = 13;</code>
   */
  private void setSearchWithSourcesResult(com.siansiansu.taigikeyboard.engine.proto.SearchWithSourcesResponse value) {
    java.util.Objects.requireNonNull(value);
    result_ = value;
    resultCase_ = 13;
  }
  /**
   * <code>.taigi.engine.SearchWithSourcesResponse search_with_sources_result = 13;</code>
   */
  private void mergeSearchWithSourcesResult(com.siansiansu.taigikeyboard.engine.proto.SearchWithSourcesResponse value) {
    java.util.Objects.requireNonNull(value);
    if (resultCase_ == 13 &&
        result_ != com.siansiansu.taigikeyboard.engine.proto.SearchWithSourcesResponse.getDefaultInstance()) {
      result_ = com.siansiansu.taigikeyboard.engine.proto.SearchWithSourcesResponse.newBuilder((com.siansiansu.taigikeyboard.engine.proto.SearchWithSourcesResponse) result_)
          .mergeFrom(value).buildPartial();
    } else {
      result_ = value;
    }
    resultCase_ = 13;
  }
  /**
   * <code>.taigi.engine.SearchWithSourcesResponse search_with_sources_result = 13;</code>
   */
  private void clearSearchWithSourcesResult() {
    if (resultCase_ == 13) {
      resultCase_ = 0;
      result_ = null;
    }
  }

  public static final int SEARCH_BY_HANZI_RESULT_FIELD_NUMBER = 14;
  /**
   * <code>.taigi.engine.SearchByHanziResponse search_by_hanzi_result = 14;</code>
   */
  @java.lang.Override
  public boolean hasSearchByHanziResult() {
    return resultCase_ == 14;
  }
  /**
   * <code>.taigi.engine.SearchByHanziResponse search_by_hanzi_result = 14;</code>
   */
  @java.lang.Override
  public com.siansiansu.taigikeyboard.engine.proto.SearchByHanziResponse getSearchByHanziResult() {
    if (resultCase_ == 14) {
       return (com.siansiansu.taigikeyboard.engine.proto.SearchByHanziResponse) result_;
    }
    return com.siansiansu.taigikeyboard.engine.proto.SearchByHanziResponse.getDefaultInstance();
  }
  /**
   * <code>.taigi.engine.SearchByHanziResponse search_by_hanzi_result = 14;</code>
   */
  private void setSearchByHanziResult(com.siansiansu.taigikeyboard.engine.proto.SearchByHanziResponse value) {
    java.util.Objects.requireNonNull(value);
    result_ = value;
    resultCase_ = 14;
  }
  /**
   * <code>.taigi.engine.SearchByHanziResponse search_by_hanzi_result = 14;</code>
   */
  private void mergeSearchByHanziResult(com.siansiansu.taigikeyboard.engine.proto.SearchByHanziResponse value) {
    java.util.Objects.requireNonNull(value);
    if (resultCase_ == 14 &&
        result_ != com.siansiansu.taigikeyboard.engine.proto.SearchByHanziResponse.getDefaultInstance()) {
      result_ = com.siansiansu.taigikeyboard.engine.proto.SearchByHanziResponse.newBuilder((com.siansiansu.taigikeyboard.engine.proto.SearchByHanziResponse) result_)
          .mergeFrom(value).buildPartial();
    } else {
      result_ = value;
    }
    resultCase_ = 14;
  }
  /**
   * <code>.taigi.engine.SearchByHanziResponse search_by_hanzi_result = 14;</code>
   */
  private void clearSearchByHanziResult() {
    if (resultCase_ == 14) {
      resultCase_ = 0;
      result_ = null;
    }
  }

  public static final int ASSOC_LOOKUP_RESULT_FIELD_NUMBER = 15;
  /**
   * <code>.taigi.engine.AssocLookupResponse assoc_lookup_result = 15;</code>
   */
  @java.lang.Override
  public boolean hasAssocLookupResult() {
    return resultCase_ == 15;
  }
  /**
   * <code>.taigi.engine.AssocLookupResponse assoc_lookup_result = 15;</code>
   */
  @java.lang.Override
  public com.siansiansu.taigikeyboard.engine.proto.AssocLookupResponse getAssocLookupResult() {
    if (resultCase_ == 15) {
       return (com.siansiansu.taigikeyboard.engine.proto.AssocLookupResponse) result_;
    }
    return com.siansiansu.taigikeyboard.engine.proto.AssocLookupResponse.getDefaultInstance();
  }
  /**
   * <code>.taigi.engine.AssocLookupResponse assoc_lookup_result = 15;</code>
   */
  private void setAssocLookupResult(com.siansiansu.taigikeyboard.engine.proto.AssocLookupResponse value) {
    java.util.Objects.requireNonNull(value);
    result_ = value;
    resultCase_ = 15;
  }
  /**
   * <code>.taigi.engine.AssocLookupResponse assoc_lookup_result = 15;</code>
   */
  private void mergeAssocLookupResult(com.siansiansu.taigikeyboard.engine.proto.AssocLookupResponse value) {
    java.util.Objects.requireNonNull(value);
    if (resultCase_ == 15 &&
        result_ != com.siansiansu.taigikeyboard.engine.proto.AssocLookupResponse.getDefaultInstance()) {
      result_ = com.siansiansu.taigikeyboard.engine.proto.AssocLookupResponse.newBuilder((com.siansiansu.taigikeyboard.engine.proto.AssocLookupResponse) result_)
          .mergeFrom(value).buildPartial();
    } else {
      result_ = value;
    }
    resultCase_ = 15;
  }
  /**
   * <code>.taigi.engine.AssocLookupResponse assoc_lookup_result = 15;</code>
   */
  private void clearAssocLookupResult() {
    if (resultCase_ == 15) {
      resultCase_ = 0;
      result_ = null;
    }
  }

  public static final int CLASSIFY_INPUT_RESULT_FIELD_NUMBER = 16;
  /**
   * <code>.taigi.engine.ClassifyInputResponse classify_input_result = 16;</code>
   */
  @java.lang.Override
  public boolean hasClassifyInputResult() {
    return resultCase_ == 16;
  }
  /**
   * <code>.taigi.engine.ClassifyInputResponse classify_input_result = 16;</code>
   */
  @java.lang.Override
  public com.siansiansu.taigikeyboard.engine.proto.ClassifyInputResponse getClassifyInputResult() {
    if (resultCase_ == 16) {
       return (com.siansiansu.taigikeyboard.engine.proto.ClassifyInputResponse) result_;
    }
    return com.siansiansu.taigikeyboard.engine.proto.ClassifyInputResponse.getDefaultInstance();
  }
  /**
   * <code>.taigi.engine.ClassifyInputResponse classify_input_result = 16;</code>
   */
  private void setClassifyInputResult(com.siansiansu.taigikeyboard.engine.proto.ClassifyInputResponse value) {
    java.util.Objects.requireNonNull(value);
    result_ = value;
    resultCase_ = 16;
  }
  /**
   * <code>.taigi.engine.ClassifyInputResponse classify_input_result = 16;</code>
   */
  private void mergeClassifyInputResult(com.siansiansu.taigikeyboard.engine.proto.ClassifyInputResponse value) {
    java.util.Objects.requireNonNull(value);
    if (resultCase_ == 16 &&
        result_ != com.siansiansu.taigikeyboard.engine.proto.ClassifyInputResponse.getDefaultInstance()) {
      result_ = com.siansiansu.taigikeyboard.engine.proto.ClassifyInputResponse.newBuilder((com.siansiansu.taigikeyboard.engine.proto.ClassifyInputResponse) result_)
          .mergeFrom(value).buildPartial();
    } else {
      result_ = value;
    }
    resultCase_ = 16;
  }
  /**
   * <code>.taigi.engine.ClassifyInputResponse classify_input_result = 16;</code>
   */
  private void clearClassifyInputResult() {
    if (resultCase_ == 16) {
      resultCase_ = 0;
      result_ = null;
    }
  }

  public static final int IS_HANZI_RESULT_FIELD_NUMBER = 17;
  /**
   * <code>.taigi.engine.IsHanziResponse is_hanzi_result = 17;</code>
   */
  @java.lang.Override
  public boolean hasIsHanziResult() {
    return resultCase_ == 17;
  }
  /**
   * <code>.taigi.engine.IsHanziResponse is_hanzi_result = 17;</code>
   */
  @java.lang.Override
  public com.siansiansu.taigikeyboard.engine.proto.IsHanziResponse getIsHanziResult() {
    if (resultCase_ == 17) {
       return (com.siansiansu.taigikeyboard.engine.proto.IsHanziResponse) result_;
    }
    return com.siansiansu.taigikeyboard.engine.proto.IsHanziResponse.getDefaultInstance();
  }
  /**
   * <code>.taigi.engine.IsHanziResponse is_hanzi_result = 17;</code>
   */
  private void setIsHanziResult(com.siansiansu.taigikeyboard.engine.proto.IsHanziResponse value) {
    java.util.Objects.requireNonNull(value);
    result_ = value;
    resultCase_ = 17;
  }
  /**
   * <code>.taigi.engine.IsHanziResponse is_hanzi_result = 17;</code>
   */
  private void mergeIsHanziResult(com.siansiansu.taigikeyboard.engine.proto.IsHanziResponse value) {
    java.util.Objects.requireNonNull(value);
    if (resultCase_ == 17 &&
        result_ != com.siansiansu.taigikeyboard.engine.proto.IsHanziResponse.getDefaultInstance()) {
      result_ = com.siansiansu.taigikeyboard.engine.proto.IsHanziResponse.newBuilder((com.siansiansu.taigikeyboard.engine.proto.IsHanziResponse) result_)
          .mergeFrom(value).buildPartial();
    } else {
      result_ = value;
    }
    resultCase_ = 17;
  }
  /**
   * <code>.taigi.engine.IsHanziResponse is_hanzi_result = 17;</code>
   */
  private void clearIsHanziResult() {
    if (resultCase_ == 17) {
      resultCase_ = 0;
      result_ = null;
    }
  }

  public static final int DICTIONARY_FILTERS_RESULT_FIELD_NUMBER = 18;
  /**
   * <code>.taigi.engine.DictionaryFiltersResponse dictionary_filters_result = 18;</code>
   */
  @java.lang.Override
  public boolean hasDictionaryFiltersResult() {
    return resultCase_ == 18;
  }
  /**
   * <code>.taigi.engine.DictionaryFiltersResponse dictionary_filters_result = 18;</code>
   */
  @java.lang.Override
  public com.siansiansu.taigikeyboard.engine.proto.DictionaryFiltersResponse getDictionaryFiltersResult() {
    if (resultCase_ == 18) {
       return (com.siansiansu.taigikeyboard.engine.proto.DictionaryFiltersResponse) result_;
    }
    return com.siansiansu.taigikeyboard.engine.proto.DictionaryFiltersResponse.getDefaultInstance();
  }
  /**
   * <code>.taigi.engine.DictionaryFiltersResponse dictionary_filters_result = 18;</code>
   */
  private void setDictionaryFiltersResult(com.siansiansu.taigikeyboard.engine.proto.DictionaryFiltersResponse value) {
    java.util.Objects.requireNonNull(value);
    result_ = value;
    resultCase_ = 18;
  }
  /**
   * <code>.taigi.engine.DictionaryFiltersResponse dictionary_filters_result = 18;</code>
   */
  private void mergeDictionaryFiltersResult(com.siansiansu.taigikeyboard.engine.proto.DictionaryFiltersResponse value) {
    java.util.Objects.requireNonNull(value);
    if (resultCase_ == 18 &&
        result_ != com.siansiansu.taigikeyboard.engine.proto.DictionaryFiltersResponse.getDefaultInstance()) {
      result_ = com.siansiansu.taigikeyboard.engine.proto.DictionaryFiltersResponse.newBuilder((com.siansiansu.taigikeyboard.engine.proto.DictionaryFiltersResponse) result_)
          .mergeFrom(value).buildPartial();
    } else {
      result_ = value;
    }
    resultCase_ = 18;
  }
  /**
   * <code>.taigi.engine.DictionaryFiltersResponse dictionary_filters_result = 18;</code>
   */
  private void clearDictionaryFiltersResult() {
    if (resultCase_ == 18) {
      resultCase_ = 0;
      result_ = null;
    }
  }

  public static com.siansiansu.taigikeyboard.engine.proto.LexiconResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.siansiansu.taigikeyboard.engine.proto.LexiconResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.siansiansu.taigikeyboard.engine.proto.LexiconResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.siansiansu.taigikeyboard.engine.proto.LexiconResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.siansiansu.taigikeyboard.engine.proto.LexiconResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.siansiansu.taigikeyboard.engine.proto.LexiconResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.siansiansu.taigikeyboard.engine.proto.LexiconResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.siansiansu.taigikeyboard.engine.proto.LexiconResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static com.siansiansu.taigikeyboard.engine.proto.LexiconResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }

  public static com.siansiansu.taigikeyboard.engine.proto.LexiconResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static com.siansiansu.taigikeyboard.engine.proto.LexiconResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.siansiansu.taigikeyboard.engine.proto.LexiconResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }
  public static Builder newBuilder(com.siansiansu.taigikeyboard.engine.proto.LexiconResponse prototype) {
    return DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * Protobuf type {@code taigi.engine.LexiconResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        com.siansiansu.taigikeyboard.engine.proto.LexiconResponse, Builder> implements
      // @@protoc_insertion_point(builder_implements:taigi.engine.LexiconResponse)
      com.siansiansu.taigikeyboard.engine.proto.LexiconResponseOrBuilder {
    // Construct using com.siansiansu.taigikeyboard.engine.proto.LexiconResponse.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }

    @java.lang.Override
    public ResultCase
        getResultCase() {
      return instance.getResultCase();
    }

    public Builder clearResult() {
      copyOnWrite();
      instance.clearResult();
      return this;
    }


    /**
     * <code>.taigi.engine.ProcessCandidatesResponse process_candidates_result = 10;</code>
     */
    @java.lang.Override
    public boolean hasProcessCandidatesResult() {
      return instance.hasProcessCandidatesResult();
    }
    /**
     * <code>.taigi.engine.ProcessCandidatesResponse process_candidates_result = 10;</code>
     */
    @java.lang.Override
    public com.siansiansu.taigikeyboard.engine.proto.ProcessCandidatesResponse getProcessCandidatesResult() {
      return instance.getProcessCandidatesResult();
    }
    /**
     * <code>.taigi.engine.ProcessCandidatesResponse process_candidates_result = 10;</code>
     */
    public Builder setProcessCandidatesResult(com.siansiansu.taigikeyboard.engine.proto.ProcessCandidatesResponse value) {
      copyOnWrite();
      instance.setProcessCandidatesResult(value);
      return this;
    }
    /**
     * <code>.taigi.engine.ProcessCandidatesResponse process_candidates_result = 10;</code>
     */
    public Builder setProcessCandidatesResult(
        com.siansiansu.taigikeyboard.engine.proto.ProcessCandidatesResponse.Builder builderForValue) {
      copyOnWrite();
      instance.setProcessCandidatesResult(builderForValue.build());
      return this;
    }
    /**
     * <code>.taigi.engine.ProcessCandidatesResponse process_candidates_result = 10;</code>
     */
    public Builder mergeProcessCandidatesResult(com.siansiansu.taigikeyboard.engine.proto.ProcessCandidatesResponse value) {
      copyOnWrite();
      instance.mergeProcessCandidatesResult(value);
      return this;
    }
    /**
     * <code>.taigi.engine.ProcessCandidatesResponse process_candidates_result = 10;</code>
     */
    public Builder clearProcessCandidatesResult() {
      copyOnWrite();
      instance.clearProcessCandidatesResult();
      return this;
    }

    /**
     * <code>.taigi.engine.InstallResponse install_result = 11;</code>
     */
    @java.lang.Override
    public boolean hasInstallResult() {
      return instance.hasInstallResult();
    }
    /**
     * <code>.taigi.engine.InstallResponse install_result = 11;</code>
     */
    @java.lang.Override
    public com.siansiansu.taigikeyboard.engine.proto.InstallResponse getInstallResult() {
      return instance.getInstallResult();
    }
    /**
     * <code>.taigi.engine.InstallResponse install_result = 11;</code>
     */
    public Builder setInstallResult(com.siansiansu.taigikeyboard.engine.proto.InstallResponse value) {
      copyOnWrite();
      instance.setInstallResult(value);
      return this;
    }
    /**
     * <code>.taigi.engine.InstallResponse install_result = 11;</code>
     */
    public Builder setInstallResult(
        com.siansiansu.taigikeyboard.engine.proto.InstallResponse.Builder builderForValue) {
      copyOnWrite();
      instance.setInstallResult(builderForValue.build());
      return this;
    }
    /**
     * <code>.taigi.engine.InstallResponse install_result = 11;</code>
     */
    public Builder mergeInstallResult(com.siansiansu.taigikeyboard.engine.proto.InstallResponse value) {
      copyOnWrite();
      instance.mergeInstallResult(value);
      return this;
    }
    /**
     * <code>.taigi.engine.InstallResponse install_result = 11;</code>
     */
    public Builder clearInstallResult() {
      copyOnWrite();
      instance.clearInstallResult();
      return this;
    }

    /**
     * <code>.taigi.engine.SearchResponse search_result = 12;</code>
     */
    @java.lang.Override
    public boolean hasSearchResult() {
      return instance.hasSearchResult();
    }
    /**
     * <code>.taigi.engine.SearchResponse search_result = 12;</code>
     */
    @java.lang.Override
    public com.siansiansu.taigikeyboard.engine.proto.SearchResponse getSearchResult() {
      return instance.getSearchResult();
    }
    /**
     * <code>.taigi.engine.SearchResponse search_result = 12;</code>
     */
    public Builder setSearchResult(com.siansiansu.taigikeyboard.engine.proto.SearchResponse value) {
      copyOnWrite();
      instance.setSearchResult(value);
      return this;
    }
    /**
     * <code>.taigi.engine.SearchResponse search_result = 12;</code>
     */
    public Builder setSearchResult(
        com.siansiansu.taigikeyboard.engine.proto.SearchResponse.Builder builderForValue) {
      copyOnWrite();
      instance.setSearchResult(builderForValue.build());
      return this;
    }
    /**
     * <code>.taigi.engine.SearchResponse search_result = 12;</code>
     */
    public Builder mergeSearchResult(com.siansiansu.taigikeyboard.engine.proto.SearchResponse value) {
      copyOnWrite();
      instance.mergeSearchResult(value);
      return this;
    }
    /**
     * <code>.taigi.engine.SearchResponse search_result = 12;</code>
     */
    public Builder clearSearchResult() {
      copyOnWrite();
      instance.clearSearchResult();
      return this;
    }

    /**
     * <code>.taigi.engine.SearchWithSourcesResponse search_with_sources_result = 13;</code>
     */
    @java.lang.Override
    public boolean hasSearchWithSourcesResult() {
      return instance.hasSearchWithSourcesResult();
    }
    /**
     * <code>.taigi.engine.SearchWithSourcesResponse search_with_sources_result = 13;</code>
     */
    @java.lang.Override
    public com.siansiansu.taigikeyboard.engine.proto.SearchWithSourcesResponse getSearchWithSourcesResult() {
      return instance.getSearchWithSourcesResult();
    }
    /**
     * <code>.taigi.engine.SearchWithSourcesResponse search_with_sources_result = 13;</code>
     */
    public Builder setSearchWithSourcesResult(com.siansiansu.taigikeyboard.engine.proto.SearchWithSourcesResponse value) {
      copyOnWrite();
      instance.setSearchWithSourcesResult(value);
      return this;
    }
    /**
     * <code>.taigi.engine.SearchWithSourcesResponse search_with_sources_result = 13;</code>
     */
    public Builder setSearchWithSourcesResult(
        com.siansiansu.taigikeyboard.engine.proto.SearchWithSourcesResponse.Builder builderForValue) {
      copyOnWrite();
      instance.setSearchWithSourcesResult(builderForValue.build());
      return this;
    }
    /**
     * <code>.taigi.engine.SearchWithSourcesResponse search_with_sources_result = 13;</code>
     */
    public Builder mergeSearchWithSourcesResult(com.siansiansu.taigikeyboard.engine.proto.SearchWithSourcesResponse value) {
      copyOnWrite();
      instance.mergeSearchWithSourcesResult(value);
      return this;
    }
    /**
     * <code>.taigi.engine.SearchWithSourcesResponse search_with_sources_result = 13;</code>
     */
    public Builder clearSearchWithSourcesResult() {
      copyOnWrite();
      instance.clearSearchWithSourcesResult();
      return this;
    }

    /**
     * <code>.taigi.engine.SearchByHanziResponse search_by_hanzi_result = 14;</code>
     */
    @java.lang.Override
    public boolean hasSearchByHanziResult() {
      return instance.hasSearchByHanziResult();
    }
    /**
     * <code>.taigi.engine.SearchByHanziResponse search_by_hanzi_result = 14;</code>
     */
    @java.lang.Override
    public com.siansiansu.taigikeyboard.engine.proto.SearchByHanziResponse getSearchByHanziResult() {
      return instance.getSearchByHanziResult();
    }
    /**
     * <code>.taigi.engine.SearchByHanziResponse search_by_hanzi_result = 14;</code>
     */
    public Builder setSearchByHanziResult(com.siansiansu.taigikeyboard.engine.proto.SearchByHanziResponse value) {
      copyOnWrite();
      instance.setSearchByHanziResult(value);
      return this;
    }
    /**
     * <code>.taigi.engine.SearchByHanziResponse search_by_hanzi_result = 14;</code>
     */
    public Builder setSearchByHanziResult(
        com.siansiansu.taigikeyboard.engine.proto.SearchByHanziResponse.Builder builderForValue) {
      copyOnWrite();
      instance.setSearchByHanziResult(builderForValue.build());
      return this;
    }
    /**
     * <code>.taigi.engine.SearchByHanziResponse search_by_hanzi_result = 14;</code>
     */
    public Builder mergeSearchByHanziResult(com.siansiansu.taigikeyboard.engine.proto.SearchByHanziResponse value) {
      copyOnWrite();
      instance.mergeSearchByHanziResult(value);
      return this;
    }
    /**
     * <code>.taigi.engine.SearchByHanziResponse search_by_hanzi_result = 14;</code>
     */
    public Builder clearSearchByHanziResult() {
      copyOnWrite();
      instance.clearSearchByHanziResult();
      return this;
    }

    /**
     * <code>.taigi.engine.AssocLookupResponse assoc_lookup_result = 15;</code>
     */
    @java.lang.Override
    public boolean hasAssocLookupResult() {
      return instance.hasAssocLookupResult();
    }
    /**
     * <code>.taigi.engine.AssocLookupResponse assoc_lookup_result = 15;</code>
     */
    @java.lang.Override
    public com.siansiansu.taigikeyboard.engine.proto.AssocLookupResponse getAssocLookupResult() {
      return instance.getAssocLookupResult();
    }
    /**
     * <code>.taigi.engine.AssocLookupResponse assoc_lookup_result = 15;</code>
     */
    public Builder setAssocLookupResult(com.siansiansu.taigikeyboard.engine.proto.AssocLookupResponse value) {
      copyOnWrite();
      instance.setAssocLookupResult(value);
      return this;
    }
    /**
     * <code>.taigi.engine.AssocLookupResponse assoc_lookup_result = 15;</code>
     */
    public Builder setAssocLookupResult(
        com.siansiansu.taigikeyboard.engine.proto.AssocLookupResponse.Builder builderForValue) {
      copyOnWrite();
      instance.setAssocLookupResult(builderForValue.build());
      return this;
    }
    /**
     * <code>.taigi.engine.AssocLookupResponse assoc_lookup_result = 15;</code>
     */
    public Builder mergeAssocLookupResult(com.siansiansu.taigikeyboard.engine.proto.AssocLookupResponse value) {
      copyOnWrite();
      instance.mergeAssocLookupResult(value);
      return this;
    }
    /**
     * <code>.taigi.engine.AssocLookupResponse assoc_lookup_result = 15;</code>
     */
    public Builder clearAssocLookupResult() {
      copyOnWrite();
      instance.clearAssocLookupResult();
      return this;
    }

    /**
     * <code>.taigi.engine.ClassifyInputResponse classify_input_result = 16;</code>
     */
    @java.lang.Override
    public boolean hasClassifyInputResult() {
      return instance.hasClassifyInputResult();
    }
    /**
     * <code>.taigi.engine.ClassifyInputResponse classify_input_result = 16;</code>
     */
    @java.lang.Override
    public com.siansiansu.taigikeyboard.engine.proto.ClassifyInputResponse getClassifyInputResult() {
      return instance.getClassifyInputResult();
    }
    /**
     * <code>.taigi.engine.ClassifyInputResponse classify_input_result = 16;</code>
     */
    public Builder setClassifyInputResult(com.siansiansu.taigikeyboard.engine.proto.ClassifyInputResponse value) {
      copyOnWrite();
      instance.setClassifyInputResult(value);
      return this;
    }
    /**
     * <code>.taigi.engine.ClassifyInputResponse classify_input_result = 16;</code>
     */
    public Builder setClassifyInputResult(
        com.siansiansu.taigikeyboard.engine.proto.ClassifyInputResponse.Builder builderForValue) {
      copyOnWrite();
      instance.setClassifyInputResult(builderForValue.build());
      return this;
    }
    /**
     * <code>.taigi.engine.ClassifyInputResponse classify_input_result = 16;</code>
     */
    public Builder mergeClassifyInputResult(com.siansiansu.taigikeyboard.engine.proto.ClassifyInputResponse value) {
      copyOnWrite();
      instance.mergeClassifyInputResult(value);
      return this;
    }
    /**
     * <code>.taigi.engine.ClassifyInputResponse classify_input_result = 16;</code>
     */
    public Builder clearClassifyInputResult() {
      copyOnWrite();
      instance.clearClassifyInputResult();
      return this;
    }

    /**
     * <code>.taigi.engine.IsHanziResponse is_hanzi_result = 17;</code>
     */
    @java.lang.Override
    public boolean hasIsHanziResult() {
      return instance.hasIsHanziResult();
    }
    /**
     * <code>.taigi.engine.IsHanziResponse is_hanzi_result = 17;</code>
     */
    @java.lang.Override
    public com.siansiansu.taigikeyboard.engine.proto.IsHanziResponse getIsHanziResult() {
      return instance.getIsHanziResult();
    }
    /**
     * <code>.taigi.engine.IsHanziResponse is_hanzi_result = 17;</code>
     */
    public Builder setIsHanziResult(com.siansiansu.taigikeyboard.engine.proto.IsHanziResponse value) {
      copyOnWrite();
      instance.setIsHanziResult(value);
      return this;
    }
    /**
     * <code>.taigi.engine.IsHanziResponse is_hanzi_result = 17;</code>
     */
    public Builder setIsHanziResult(
        com.siansiansu.taigikeyboard.engine.proto.IsHanziResponse.Builder builderForValue) {
      copyOnWrite();
      instance.setIsHanziResult(builderForValue.build());
      return this;
    }
    /**
     * <code>.taigi.engine.IsHanziResponse is_hanzi_result = 17;</code>
     */
    public Builder mergeIsHanziResult(com.siansiansu.taigikeyboard.engine.proto.IsHanziResponse value) {
      copyOnWrite();
      instance.mergeIsHanziResult(value);
      return this;
    }
    /**
     * <code>.taigi.engine.IsHanziResponse is_hanzi_result = 17;</code>
     */
    public Builder clearIsHanziResult() {
      copyOnWrite();
      instance.clearIsHanziResult();
      return this;
    }

    /**
     * <code>.taigi.engine.DictionaryFiltersResponse dictionary_filters_result = 18;</code>
     */
    @java.lang.Override
    public boolean hasDictionaryFiltersResult() {
      return instance.hasDictionaryFiltersResult();
    }
    /**
     * <code>.taigi.engine.DictionaryFiltersResponse dictionary_filters_result = 18;</code>
     */
    @java.lang.Override
    public com.siansiansu.taigikeyboard.engine.proto.DictionaryFiltersResponse getDictionaryFiltersResult() {
      return instance.getDictionaryFiltersResult();
    }
    /**
     * <code>.taigi.engine.DictionaryFiltersResponse dictionary_filters_result = 18;</code>
     */
    public Builder setDictionaryFiltersResult(com.siansiansu.taigikeyboard.engine.proto.DictionaryFiltersResponse value) {
      copyOnWrite();
      instance.setDictionaryFiltersResult(value);
      return this;
    }
    /**
     * <code>.taigi.engine.DictionaryFiltersResponse dictionary_filters_result = 18;</code>
     */
    public Builder setDictionaryFiltersResult(
        com.siansiansu.taigikeyboard.engine.proto.DictionaryFiltersResponse.Builder builderForValue) {
      copyOnWrite();
      instance.setDictionaryFiltersResult(builderForValue.build());
      return this;
    }
    /**
     * <code>.taigi.engine.DictionaryFiltersResponse dictionary_filters_result = 18;</code>
     */
    public Builder mergeDictionaryFiltersResult(com.siansiansu.taigikeyboard.engine.proto.DictionaryFiltersResponse value) {
      copyOnWrite();
      instance.mergeDictionaryFiltersResult(value);
      return this;
    }
    /**
     * <code>.taigi.engine.DictionaryFiltersResponse dictionary_filters_result = 18;</code>
     */
    public Builder clearDictionaryFiltersResult() {
      copyOnWrite();
      instance.clearDictionaryFiltersResult();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:taigi.engine.LexiconResponse)
  }
  @java.lang.Override
  @java.lang.SuppressWarnings({"ThrowNull"})
  protected final java.lang.Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      java.lang.Object arg0, java.lang.Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new com.siansiansu.taigikeyboard.engine.proto.LexiconResponse();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
          java.lang.Object[] objects = new java.lang.Object[] {
            "result_",
            "resultCase_",
            com.siansiansu.taigikeyboard.engine.proto.ProcessCandidatesResponse.class,
            com.siansiansu.taigikeyboard.engine.proto.InstallResponse.class,
            com.siansiansu.taigikeyboard.engine.proto.SearchResponse.class,
            com.siansiansu.taigikeyboard.engine.proto.SearchWithSourcesResponse.class,
            com.siansiansu.taigikeyboard.engine.proto.SearchByHanziResponse.class,
            com.siansiansu.taigikeyboard.engine.proto.AssocLookupResponse.class,
            com.siansiansu.taigikeyboard.engine.proto.ClassifyInputResponse.class,
            com.siansiansu.taigikeyboard.engine.proto.IsHanziResponse.class,
            com.siansiansu.taigikeyboard.engine.proto.DictionaryFiltersResponse.class,
          };
          java.lang.String info =
              "\u0000\t\u0001\u0000\n\u0012\t\u0000\u0000\u0000\n<\u0000\u000b<\u0000\f<\u0000\r" +
              "<\u0000\u000e<\u0000\u000f<\u0000\u0010<\u0000\u0011<\u0000\u0012<\u0000";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<com.siansiansu.taigikeyboard.engine.proto.LexiconResponse> parser = PARSER;
        if (parser == null) {
          synchronized (com.siansiansu.taigikeyboard.engine.proto.LexiconResponse.class) {
            parser = PARSER;
            if (parser == null) {
              parser =
                  new DefaultInstanceBasedParser<com.siansiansu.taigikeyboard.engine.proto.LexiconResponse>(
                      DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      // SET_MEMOIZED_IS_INITIALIZED is never called for this message.
      // So it can do anything. Combine with default case for smaller codegen.
      case SET_MEMOIZED_IS_INITIALIZED:
    }
    // Should never happen. Generates tight code to throw an exception.
    throw null;
  }


  // @@protoc_insertion_point(class_scope:taigi.engine.LexiconResponse)
  private static final com.siansiansu.taigikeyboard.engine.proto.LexiconResponse DEFAULT_INSTANCE;
  static {
    LexiconResponse defaultInstance = new LexiconResponse();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
      LexiconResponse.class, defaultInstance);
  }

  public static com.siansiansu.taigikeyboard.engine.proto.LexiconResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<LexiconResponse> PARSER;

  public static com.google.protobuf.Parser<LexiconResponse> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}
