// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: lexicon.proto
// Protobuf Java Version: 4.27.5

package com.siansiansu.taigikeyboard.engine.proto;

/**
 * Protobuf type {@code taigi.engine.LexiconRequest}
 */
public  final class LexiconRequest extends
    com.google.protobuf.GeneratedMessageLite<
        LexiconRequest, LexiconRequest.Builder> implements
    // @@protoc_insertion_point(message_implements:taigi.engine.LexiconRequest)
    LexiconRequestOrBuilder {
  private LexiconRequest() {
  }
  private int methodCase_ = 0;
  private java.lang.Object method_;
  public enum MethodCase {
    PROCESS_CANDIDATES(10),
    METHOD_NOT_SET(0);
    private final int value;
    private MethodCase(int value) {
      this.value = value;
    }
    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static MethodCase valueOf(int value) {
      return forNumber(value);
    }

    public static MethodCase forNumber(int value) {
      switch (value) {
        case 10: return PROCESS_CANDIDATES;
        case 0: return METHOD_NOT_SET;
        default: return null;
      }
    }
    public int getNumber() {
      return this.value;
    }
  };

  @java.lang.Override
  public MethodCase
  getMethodCase() {
    return MethodCase.forNumber(
        methodCase_);
  }

  private void clearMethod() {
    methodCase_ = 0;
    method_ = null;
  }

  public static final int PROCESS_CANDIDATES_FIELD_NUMBER = 10;
  /**
   * <code>.taigi.engine.ProcessCandidatesRequest process_candidates = 10;</code>
   */
  @java.lang.Override
  public boolean hasProcessCandidates() {
    return methodCase_ == 10;
  }
  /**
   * <code>.taigi.engine.ProcessCandidatesRequest process_candidates = 10;</code>
   */
  @java.lang.Override
  public com.siansiansu.taigikeyboard.engine.proto.ProcessCandidatesRequest getProcessCandidates() {
    if (methodCase_ == 10) {
       return (com.siansiansu.taigikeyboard.engine.proto.ProcessCandidatesRequest) method_;
    }
    return com.siansiansu.taigikeyboard.engine.proto.ProcessCandidatesRequest.getDefaultInstance();
  }
  /**
   * <code>.taigi.engine.ProcessCandidatesRequest process_candidates = 10;</code>
   */
  private void setProcessCandidates(com.siansiansu.taigikeyboard.engine.proto.ProcessCandidatesRequest value) {
    value.getClass();
  method_ = value;
    methodCase_ = 10;
  }
  /**
   * <code>.taigi.engine.ProcessCandidatesRequest process_candidates = 10;</code>
   */
  private void mergeProcessCandidates(com.siansiansu.taigikeyboard.engine.proto.ProcessCandidatesRequest value) {
    value.getClass();
  if (methodCase_ == 10 &&
        method_ != com.siansiansu.taigikeyboard.engine.proto.ProcessCandidatesRequest.getDefaultInstance()) {
      method_ = com.siansiansu.taigikeyboard.engine.proto.ProcessCandidatesRequest.newBuilder((com.siansiansu.taigikeyboard.engine.proto.ProcessCandidatesRequest) method_)
          .mergeFrom(value).buildPartial();
    } else {
      method_ = value;
    }
    methodCase_ = 10;
  }
  /**
   * <code>.taigi.engine.ProcessCandidatesRequest process_candidates = 10;</code>
   */
  private void clearProcessCandidates() {
    if (methodCase_ == 10) {
      methodCase_ = 0;
      method_ = null;
    }
  }

  public static com.siansiansu.taigikeyboard.engine.proto.LexiconRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.siansiansu.taigikeyboard.engine.proto.LexiconRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.siansiansu.taigikeyboard.engine.proto.LexiconRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.siansiansu.taigikeyboard.engine.proto.LexiconRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.siansiansu.taigikeyboard.engine.proto.LexiconRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.siansiansu.taigikeyboard.engine.proto.LexiconRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.siansiansu.taigikeyboard.engine.proto.LexiconRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.siansiansu.taigikeyboard.engine.proto.LexiconRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static com.siansiansu.taigikeyboard.engine.proto.LexiconRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }

  public static com.siansiansu.taigikeyboard.engine.proto.LexiconRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static com.siansiansu.taigikeyboard.engine.proto.LexiconRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.siansiansu.taigikeyboard.engine.proto.LexiconRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }
  public static Builder newBuilder(com.siansiansu.taigikeyboard.engine.proto.LexiconRequest prototype) {
    return DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * Protobuf type {@code taigi.engine.LexiconRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        com.siansiansu.taigikeyboard.engine.proto.LexiconRequest, Builder> implements
      // @@protoc_insertion_point(builder_implements:taigi.engine.LexiconRequest)
      com.siansiansu.taigikeyboard.engine.proto.LexiconRequestOrBuilder {
    // Construct using com.siansiansu.taigikeyboard.engine.proto.LexiconRequest.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }

    @java.lang.Override
    public MethodCase
        getMethodCase() {
      return instance.getMethodCase();
    }

    public Builder clearMethod() {
      copyOnWrite();
      instance.clearMethod();
      return this;
    }


    /**
     * <code>.taigi.engine.ProcessCandidatesRequest process_candidates = 10;</code>
     */
    @java.lang.Override
    public boolean hasProcessCandidates() {
      return instance.hasProcessCandidates();
    }
    /**
     * <code>.taigi.engine.ProcessCandidatesRequest process_candidates = 10;</code>
     */
    @java.lang.Override
    public com.siansiansu.taigikeyboard.engine.proto.ProcessCandidatesRequest getProcessCandidates() {
      return instance.getProcessCandidates();
    }
    /**
     * <code>.taigi.engine.ProcessCandidatesRequest process_candidates = 10;</code>
     */
    public Builder setProcessCandidates(com.siansiansu.taigikeyboard.engine.proto.ProcessCandidatesRequest value) {
      copyOnWrite();
      instance.setProcessCandidates(value);
      return this;
    }
    /**
     * <code>.taigi.engine.ProcessCandidatesRequest process_candidates = 10;</code>
     */
    public Builder setProcessCandidates(
        com.siansiansu.taigikeyboard.engine.proto.ProcessCandidatesRequest.Builder builderForValue) {
      copyOnWrite();
      instance.setProcessCandidates(builderForValue.build());
      return this;
    }
    /**
     * <code>.taigi.engine.ProcessCandidatesRequest process_candidates = 10;</code>
     */
    public Builder mergeProcessCandidates(com.siansiansu.taigikeyboard.engine.proto.ProcessCandidatesRequest value) {
      copyOnWrite();
      instance.mergeProcessCandidates(value);
      return this;
    }
    /**
     * <code>.taigi.engine.ProcessCandidatesRequest process_candidates = 10;</code>
     */
    public Builder clearProcessCandidates() {
      copyOnWrite();
      instance.clearProcessCandidates();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:taigi.engine.LexiconRequest)
  }
  @java.lang.Override
  @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
  protected final java.lang.Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      java.lang.Object arg0, java.lang.Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new com.siansiansu.taigikeyboard.engine.proto.LexiconRequest();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
          java.lang.Object[] objects = new java.lang.Object[] {
            "method_",
            "methodCase_",
            com.siansiansu.taigikeyboard.engine.proto.ProcessCandidatesRequest.class,
          };
          java.lang.String info =
              "\u0000\u0001\u0001\u0000\n\n\u0001\u0000\u0000\u0000\n<\u0000";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      // fall through
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<com.siansiansu.taigikeyboard.engine.proto.LexiconRequest> parser = PARSER;
        if (parser == null) {
          synchronized (com.siansiansu.taigikeyboard.engine.proto.LexiconRequest.class) {
            parser = PARSER;
            if (parser == null) {
              parser =
                  new DefaultInstanceBasedParser<com.siansiansu.taigikeyboard.engine.proto.LexiconRequest>(
                      DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
    }
    case GET_MEMOIZED_IS_INITIALIZED: {
      return (byte) 1;
    }
    case SET_MEMOIZED_IS_INITIALIZED: {
      return null;
    }
    }
    throw new UnsupportedOperationException();
  }


  // @@protoc_insertion_point(class_scope:taigi.engine.LexiconRequest)
  private static final com.siansiansu.taigikeyboard.engine.proto.LexiconRequest DEFAULT_INSTANCE;
  static {
    LexiconRequest defaultInstance = new LexiconRequest();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
      LexiconRequest.class, defaultInstance);
  }

  public static com.siansiansu.taigikeyboard.engine.proto.LexiconRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<LexiconRequest> PARSER;

  public static com.google.protobuf.Parser<LexiconRequest> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

