// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: composing.proto
// Protobuf Java Version: 4.36.0

package com.siansiansu.taigikeyboard.engine.proto;

/**
 * <pre>
 * Desktop only — step the caret inside the pending tail one Unicode scalar
 * value left or right (`⌥←` / `⌥→` on macOS, `Ctrl+←` / `Ctrl+→` on Windows). The
 * buffer does not change, so the response carries `UpdatePreedit` (with the
 * new `caret_utf16`) and NO `PerformAutocomplete`: candidates, highlight and
 * page stay. At either edge of the pending tail — the caret never enters a
 * nailed segment — the request is a no-op with no effects. Every mutator
 * then edits at the caret: `Append` inserts there, `DeleteBackward` /
 * `ReplaceLast` act on the character before it, `TelexKey` on the chunk
 * before it. Mobile never sends this, so its caret stays at the end and
 * every mutator behaves as before.
 * </pre>
 *
 * Protobuf type {@code taigi.engine.MoveCaret}
 */
@com.google.protobuf.Generated
public  final class MoveCaret extends
    com.google.protobuf.GeneratedMessageLite<
        MoveCaret, MoveCaret.Builder> implements
    // @@protoc_insertion_point(message_implements:taigi.engine.MoveCaret)
    MoveCaretOrBuilder {
  private MoveCaret() {
  }
  public static final int DIRECTION_FIELD_NUMBER = 1;
  private int direction_;
  /**
   * <code>.taigi.engine.CaretDirection direction = 1;</code>
   * @return The enum numeric value on the wire for direction.
   */
  @java.lang.Override
  public int getDirectionValue() {
    return direction_;
  }
  /**
   * <code>.taigi.engine.CaretDirection direction = 1;</code>
   * @return The direction.
   */
  @java.lang.Override
  public com.siansiansu.taigikeyboard.engine.proto.CaretDirection getDirection() {
    com.siansiansu.taigikeyboard.engine.proto.CaretDirection result = com.siansiansu.taigikeyboard.engine.proto.CaretDirection.forNumber(direction_);
    return result == null ? com.siansiansu.taigikeyboard.engine.proto.CaretDirection.UNRECOGNIZED : result;
  }
  /**
   * <code>.taigi.engine.CaretDirection direction = 1;</code>
   * @param value The enum numeric value on the wire for direction to set.
   */
  private void setDirectionValue(int value) {
      direction_ = value;
  }
  /**
   * <code>.taigi.engine.CaretDirection direction = 1;</code>
   * @param value The direction to set.
   * @throws IllegalArgumentException if UNRECOGNIZED is provided.
   */
  private void setDirection(com.siansiansu.taigikeyboard.engine.proto.CaretDirection value) {
    direction_ = value.getNumber();

  }
  /**
   * <code>.taigi.engine.CaretDirection direction = 1;</code>
   */
  private void clearDirection() {

    direction_ = 0;
  }

  public static com.siansiansu.taigikeyboard.engine.proto.MoveCaret parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.siansiansu.taigikeyboard.engine.proto.MoveCaret parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.siansiansu.taigikeyboard.engine.proto.MoveCaret parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.siansiansu.taigikeyboard.engine.proto.MoveCaret parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.siansiansu.taigikeyboard.engine.proto.MoveCaret parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.siansiansu.taigikeyboard.engine.proto.MoveCaret parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.siansiansu.taigikeyboard.engine.proto.MoveCaret parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.siansiansu.taigikeyboard.engine.proto.MoveCaret parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static com.siansiansu.taigikeyboard.engine.proto.MoveCaret parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }

  public static com.siansiansu.taigikeyboard.engine.proto.MoveCaret parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static com.siansiansu.taigikeyboard.engine.proto.MoveCaret parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.siansiansu.taigikeyboard.engine.proto.MoveCaret parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }
  public static Builder newBuilder(com.siansiansu.taigikeyboard.engine.proto.MoveCaret prototype) {
    return DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * <pre>
   * Desktop only — step the caret inside the pending tail one Unicode scalar
   * value left or right (`⌥←` / `⌥→` on macOS, `Ctrl+←` / `Ctrl+→` on Windows). The
   * buffer does not change, so the response carries `UpdatePreedit` (with the
   * new `caret_utf16`) and NO `PerformAutocomplete`: candidates, highlight and
   * page stay. At either edge of the pending tail — the caret never enters a
   * nailed segment — the request is a no-op with no effects. Every mutator
   * then edits at the caret: `Append` inserts there, `DeleteBackward` /
   * `ReplaceLast` act on the character before it, `TelexKey` on the chunk
   * before it. Mobile never sends this, so its caret stays at the end and
   * every mutator behaves as before.
   * </pre>
   *
   * Protobuf type {@code taigi.engine.MoveCaret}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        com.siansiansu.taigikeyboard.engine.proto.MoveCaret, Builder> implements
      // @@protoc_insertion_point(builder_implements:taigi.engine.MoveCaret)
      com.siansiansu.taigikeyboard.engine.proto.MoveCaretOrBuilder {
    // Construct using com.siansiansu.taigikeyboard.engine.proto.MoveCaret.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <code>.taigi.engine.CaretDirection direction = 1;</code>
     * @return The enum numeric value on the wire for direction.
     */
    @java.lang.Override
    public int getDirectionValue() {
      return instance.getDirectionValue();
    }
    /**
     * <code>.taigi.engine.CaretDirection direction = 1;</code>
     * @param value The direction to set.
     * @throws IllegalArgumentException if UNRECOGNIZED is provided.
     * @return This builder for chaining.
     */
    public Builder setDirectionValue(int value) {
      copyOnWrite();
      instance.setDirectionValue(value);
      return this;
    }
    /**
     * <code>.taigi.engine.CaretDirection direction = 1;</code>
     * @return The direction.
     */
    @java.lang.Override
    public com.siansiansu.taigikeyboard.engine.proto.CaretDirection getDirection() {
      return instance.getDirection();
    }
    /**
     * <code>.taigi.engine.CaretDirection direction = 1;</code>
     * @param value The enum numeric value on the wire for direction to set.
     * @return This builder for chaining.
     */
    public Builder setDirection(com.siansiansu.taigikeyboard.engine.proto.CaretDirection value) {
      copyOnWrite();
      instance.setDirection(value);
      return this;
    }
    /**
     * <code>.taigi.engine.CaretDirection direction = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearDirection() {
      copyOnWrite();
      instance.clearDirection();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:taigi.engine.MoveCaret)
  }
  @java.lang.Override
  @java.lang.SuppressWarnings({"ThrowNull"})
  protected final java.lang.Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      java.lang.Object arg0, java.lang.Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new com.siansiansu.taigikeyboard.engine.proto.MoveCaret();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
          java.lang.Object[] objects = new java.lang.Object[] {
            "direction_",
          };
          java.lang.String info =
              "\u0000\u0001\u0000\u0000\u0001\u0001\u0001\u0000\u0000\u0000\u0001\f";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<com.siansiansu.taigikeyboard.engine.proto.MoveCaret> parser = PARSER;
        if (parser == null) {
          synchronized (com.siansiansu.taigikeyboard.engine.proto.MoveCaret.class) {
            parser = PARSER;
            if (parser == null) {
              parser =
                  new DefaultInstanceBasedParser<com.siansiansu.taigikeyboard.engine.proto.MoveCaret>(
                      DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      // SET_MEMOIZED_IS_INITIALIZED is never called for this message.
      // So it can do anything. Combine with default case for smaller codegen.
      case SET_MEMOIZED_IS_INITIALIZED:
    }
    // Should never happen. Generates tight code to throw an exception.
    throw null;
  }


  // @@protoc_insertion_point(class_scope:taigi.engine.MoveCaret)
  private static final com.siansiansu.taigikeyboard.engine.proto.MoveCaret DEFAULT_INSTANCE;
  static {
    MoveCaret defaultInstance = new MoveCaret();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
      MoveCaret.class, defaultInstance);
  }

  public static com.siansiansu.taigikeyboard.engine.proto.MoveCaret getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<MoveCaret> PARSER;

  public static com.google.protobuf.Parser<MoveCaret> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}
