// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: composing.proto
// Protobuf Java Version: 4.36.0

package com.siansiansu.taigikeyboard.engine.proto;

/**
 * <pre>
 * Mid-commit handshake during continuous-input. Maps to
 * `NextWordRequest::UpdateLastSelectedWord(text, roman, now_ms)` on the
 * platform side. `text` is the committed segment's display (e.g., "紙"),
 * `roman` is the segment's raw input (e.g., "tsua"). Emitted only inside
 * `Phase::Continuous` mid-commit branches.
 * </pre>
 *
 * Protobuf type {@code taigi.engine.NextWordUpdateLastSelectedWord}
 */
@com.google.protobuf.Generated
public  final class NextWordUpdateLastSelectedWord extends
    com.google.protobuf.GeneratedMessageLite<
        NextWordUpdateLastSelectedWord, NextWordUpdateLastSelectedWord.Builder> implements
    // @@protoc_insertion_point(message_implements:taigi.engine.NextWordUpdateLastSelectedWord)
    NextWordUpdateLastSelectedWordOrBuilder {
  private NextWordUpdateLastSelectedWord() {
    text_ = "";
    roman_ = "";
  }
  public static final int TEXT_FIELD_NUMBER = 1;
  private java.lang.String text_;
  /**
   * <code>string text = 1;</code>
   * @return The text.
   */
  @java.lang.Override
  public java.lang.String getText() {
    return text_;
  }
  /**
   * <code>string text = 1;</code>
   * @return The bytes for text.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getTextBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(text_);
  }
  /**
   * <code>string text = 1;</code>
   * @param value The text to set.
   */
  private void setText(
      java.lang.String value) {
    java.util.Objects.requireNonNull(value);

    text_ = value;
  }
  /**
   * <code>string text = 1;</code>
   */
  private void clearText() {

    text_ = getDefaultInstance().getText();
  }
  /**
   * <code>string text = 1;</code>
   * @param value The bytes for text to set.
   */
  private void setTextBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    text_ = value.toStringUtf8();

  }

  public static final int ROMAN_FIELD_NUMBER = 2;
  private java.lang.String roman_;
  /**
   * <code>string roman = 2;</code>
   * @return The roman.
   */
  @java.lang.Override
  public java.lang.String getRoman() {
    return roman_;
  }
  /**
   * <code>string roman = 2;</code>
   * @return The bytes for roman.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getRomanBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(roman_);
  }
  /**
   * <code>string roman = 2;</code>
   * @param value The roman to set.
   */
  private void setRoman(
      java.lang.String value) {
    java.util.Objects.requireNonNull(value);

    roman_ = value;
  }
  /**
   * <code>string roman = 2;</code>
   */
  private void clearRoman() {

    roman_ = getDefaultInstance().getRoman();
  }
  /**
   * <code>string roman = 2;</code>
   * @param value The bytes for roman to set.
   */
  private void setRomanBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    roman_ = value.toStringUtf8();

  }

  public static com.siansiansu.taigikeyboard.engine.proto.NextWordUpdateLastSelectedWord parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.siansiansu.taigikeyboard.engine.proto.NextWordUpdateLastSelectedWord parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.siansiansu.taigikeyboard.engine.proto.NextWordUpdateLastSelectedWord parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.siansiansu.taigikeyboard.engine.proto.NextWordUpdateLastSelectedWord parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.siansiansu.taigikeyboard.engine.proto.NextWordUpdateLastSelectedWord parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.siansiansu.taigikeyboard.engine.proto.NextWordUpdateLastSelectedWord parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.siansiansu.taigikeyboard.engine.proto.NextWordUpdateLastSelectedWord parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.siansiansu.taigikeyboard.engine.proto.NextWordUpdateLastSelectedWord parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static com.siansiansu.taigikeyboard.engine.proto.NextWordUpdateLastSelectedWord parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }

  public static com.siansiansu.taigikeyboard.engine.proto.NextWordUpdateLastSelectedWord parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static com.siansiansu.taigikeyboard.engine.proto.NextWordUpdateLastSelectedWord parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.siansiansu.taigikeyboard.engine.proto.NextWordUpdateLastSelectedWord parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }
  public static Builder newBuilder(com.siansiansu.taigikeyboard.engine.proto.NextWordUpdateLastSelectedWord prototype) {
    return DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * <pre>
   * Mid-commit handshake during continuous-input. Maps to
   * `NextWordRequest::UpdateLastSelectedWord(text, roman, now_ms)` on the
   * platform side. `text` is the committed segment's display (e.g., "紙"),
   * `roman` is the segment's raw input (e.g., "tsua"). Emitted only inside
   * `Phase::Continuous` mid-commit branches.
   * </pre>
   *
   * Protobuf type {@code taigi.engine.NextWordUpdateLastSelectedWord}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        com.siansiansu.taigikeyboard.engine.proto.NextWordUpdateLastSelectedWord, Builder> implements
      // @@protoc_insertion_point(builder_implements:taigi.engine.NextWordUpdateLastSelectedWord)
      com.siansiansu.taigikeyboard.engine.proto.NextWordUpdateLastSelectedWordOrBuilder {
    // Construct using com.siansiansu.taigikeyboard.engine.proto.NextWordUpdateLastSelectedWord.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <code>string text = 1;</code>
     * @return The text.
     */
    @java.lang.Override
    public java.lang.String getText() {
      return instance.getText();
    }
    /**
     * <code>string text = 1;</code>
     * @return The bytes for text.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getTextBytes() {
      return instance.getTextBytes();
    }
    /**
     * <code>string text = 1;</code>
     * @param value The text to set.
     * @return This builder for chaining.
     */
    public Builder setText(
        java.lang.String value) {
      copyOnWrite();
      instance.setText(value);
      return this;
    }
    /**
     * <code>string text = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearText() {
      copyOnWrite();
      instance.clearText();
      return this;
    }
    /**
     * <code>string text = 1;</code>
     * @param value The bytes for text to set.
     * @return This builder for chaining.
     */
    public Builder setTextBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setTextBytes(value);
      return this;
    }

    /**
     * <code>string roman = 2;</code>
     * @return The roman.
     */
    @java.lang.Override
    public java.lang.String getRoman() {
      return instance.getRoman();
    }
    /**
     * <code>string roman = 2;</code>
     * @return The bytes for roman.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getRomanBytes() {
      return instance.getRomanBytes();
    }
    /**
     * <code>string roman = 2;</code>
     * @param value The roman to set.
     * @return This builder for chaining.
     */
    public Builder setRoman(
        java.lang.String value) {
      copyOnWrite();
      instance.setRoman(value);
      return this;
    }
    /**
     * <code>string roman = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearRoman() {
      copyOnWrite();
      instance.clearRoman();
      return this;
    }
    /**
     * <code>string roman = 2;</code>
     * @param value The bytes for roman to set.
     * @return This builder for chaining.
     */
    public Builder setRomanBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setRomanBytes(value);
      return this;
    }

    // @@protoc_insertion_point(builder_scope:taigi.engine.NextWordUpdateLastSelectedWord)
  }
  @java.lang.Override
  @java.lang.SuppressWarnings({"ThrowNull"})
  protected final java.lang.Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      java.lang.Object arg0, java.lang.Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new com.siansiansu.taigikeyboard.engine.proto.NextWordUpdateLastSelectedWord();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
          java.lang.Object[] objects = new java.lang.Object[] {
            "text_",
            "roman_",
          };
          java.lang.String info =
              "\u0000\u0002\u0000\u0000\u0001\u0002\u0002\u0000\u0000\u0000\u0001\u0208\u0002\u0208" +
              "";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<com.siansiansu.taigikeyboard.engine.proto.NextWordUpdateLastSelectedWord> parser = PARSER;
        if (parser == null) {
          synchronized (com.siansiansu.taigikeyboard.engine.proto.NextWordUpdateLastSelectedWord.class) {
            parser = PARSER;
            if (parser == null) {
              parser =
                  new DefaultInstanceBasedParser<com.siansiansu.taigikeyboard.engine.proto.NextWordUpdateLastSelectedWord>(
                      DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      // SET_MEMOIZED_IS_INITIALIZED is never called for this message.
      // So it can do anything. Combine with default case for smaller codegen.
      case SET_MEMOIZED_IS_INITIALIZED:
    }
    // Should never happen. Generates tight code to throw an exception.
    throw null;
  }


  // @@protoc_insertion_point(class_scope:taigi.engine.NextWordUpdateLastSelectedWord)
  private static final com.siansiansu.taigikeyboard.engine.proto.NextWordUpdateLastSelectedWord DEFAULT_INSTANCE;
  static {
    NextWordUpdateLastSelectedWord defaultInstance = new NextWordUpdateLastSelectedWord();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
      NextWordUpdateLastSelectedWord.class, defaultInstance);
  }

  public static com.siansiansu.taigikeyboard.engine.proto.NextWordUpdateLastSelectedWord getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<NextWordUpdateLastSelectedWord> PARSER;

  public static com.google.protobuf.Parser<NextWordUpdateLastSelectedWord> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}
