// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: nextword.proto
// Protobuf Java Version: 4.27.5

package com.siansiansu.taigikeyboard.engine.proto;

public interface NextWordRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:taigi.engine.NextWordRequest)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <pre>
   * State-mutating intents — return DecideResult.
   * </pre>
   *
   * <code>.taigi.engine.WordSelected word_selected = 10;</code>
   * @return Whether the wordSelected field is set.
   */
  boolean hasWordSelected();
  /**
   * <pre>
   * State-mutating intents — return DecideResult.
   * </pre>
   *
   * <code>.taigi.engine.WordSelected word_selected = 10;</code>
   * @return The wordSelected.
   */
  com.siansiansu.taigikeyboard.engine.proto.WordSelected getWordSelected();

  /**
   * <code>.taigi.engine.Backspace backspace = 11;</code>
   * @return Whether the backspace field is set.
   */
  boolean hasBackspace();
  /**
   * <code>.taigi.engine.Backspace backspace = 11;</code>
   * @return The backspace.
   */
  com.siansiansu.taigikeyboard.engine.proto.Backspace getBackspace();

  /**
   * <code>.taigi.engine.ContextTimeoutFired context_timeout_fired = 12;</code>
   * @return Whether the contextTimeoutFired field is set.
   */
  boolean hasContextTimeoutFired();
  /**
   * <code>.taigi.engine.ContextTimeoutFired context_timeout_fired = 12;</code>
   * @return The contextTimeoutFired.
   */
  com.siansiansu.taigikeyboard.engine.proto.ContextTimeoutFired getContextTimeoutFired();

  /**
   * <code>.taigi.engine.ClearForNewComposing clear_for_new_composing = 13;</code>
   * @return Whether the clearForNewComposing field is set.
   */
  boolean hasClearForNewComposing();
  /**
   * <code>.taigi.engine.ClearForNewComposing clear_for_new_composing = 13;</code>
   * @return The clearForNewComposing.
   */
  com.siansiansu.taigikeyboard.engine.proto.ClearForNewComposing getClearForNewComposing();

  /**
   * <code>.taigi.engine.ResetFull reset_full = 14;</code>
   * @return Whether the resetFull field is set.
   */
  boolean hasResetFull();
  /**
   * <code>.taigi.engine.ResetFull reset_full = 14;</code>
   * @return The resetFull.
   */
  com.siansiansu.taigikeyboard.engine.proto.ResetFull getResetFull();

  /**
   * <pre>
   * Android-only Space-path intent (audit §5 #5). iOS wrappers never
   * emit this; Rust engine accepts generically. Mutates
   * last_selected_*&#47;lastSelectionTimeMs without bumping
   * current_generation, no timer effects, emits compound-only
   * RecordCompoundAssociations effect (no prev→this bigram).
   * </pre>
   *
   * <code>.taigi.engine.UpdateLastSelectedWord update_last_selected_word = 15;</code>
   * @return Whether the updateLastSelectedWord field is set.
   */
  boolean hasUpdateLastSelectedWord();
  /**
   * <pre>
   * Android-only Space-path intent (audit §5 #5). iOS wrappers never
   * emit this; Rust engine accepts generically. Mutates
   * last_selected_*&#47;lastSelectionTimeMs without bumping
   * current_generation, no timer effects, emits compound-only
   * RecordCompoundAssociations effect (no prev→this bigram).
   * </pre>
   *
   * <code>.taigi.engine.UpdateLastSelectedWord update_last_selected_word = 15;</code>
   * @return The updateLastSelectedWord.
   */
  com.siansiansu.taigikeyboard.engine.proto.UpdateLastSelectedWord getUpdateLastSelectedWord();

  /**
   * <pre>
   * Platform-driven UI visibility update. After the platform renders the
   * result of an async predict() call (or clears it on empty result), it
   * pushes the resulting visibility back to the engine via this intent so
   * subsequent ClearForNewComposing / sentence-end / context-timeout /
   * ResetFull paths can correctly emit ClearPredictionsUI when there is
   * UI to clear. Mutates state.is_showing only — does NOT bump
   * current_generation (the in-flight query that produced the rendered
   * result already won the race; later intents will bump as usual).
   * Returns DecideResult with empty effects + snapshot of state.
   * </pre>
   *
   * <code>.taigi.engine.SetIsShowing set_is_showing = 16;</code>
   * @return Whether the setIsShowing field is set.
   */
  boolean hasSetIsShowing();
  /**
   * <pre>
   * Platform-driven UI visibility update. After the platform renders the
   * result of an async predict() call (or clears it on empty result), it
   * pushes the resulting visibility back to the engine via this intent so
   * subsequent ClearForNewComposing / sentence-end / context-timeout /
   * ResetFull paths can correctly emit ClearPredictionsUI when there is
   * UI to clear. Mutates state.is_showing only — does NOT bump
   * current_generation (the in-flight query that produced the rendered
   * result already won the race; later intents will bump as usual).
   * Returns DecideResult with empty effects + snapshot of state.
   * </pre>
   *
   * <code>.taigi.engine.SetIsShowing set_is_showing = 16;</code>
   * @return The setIsShowing.
   */
  com.siansiansu.taigikeyboard.engine.proto.SetIsShowing getSetIsShowing();

  /**
   * <pre>
   * Pure post-query filter+merge+sort+limit — return FilterResult
   * (handles stale-gen drop).
   * </pre>
   *
   * <code>.taigi.engine.FilterPredictions filter_predictions = 20;</code>
   * @return Whether the filterPredictions field is set.
   */
  boolean hasFilterPredictions();
  /**
   * <pre>
   * Pure post-query filter+merge+sort+limit — return FilterResult
   * (handles stale-gen drop).
   * </pre>
   *
   * <code>.taigi.engine.FilterPredictions filter_predictions = 20;</code>
   * @return The filterPredictions.
   */
  com.siansiansu.taigikeyboard.engine.proto.FilterPredictions getFilterPredictions();

  /**
   * <pre>
   * Stateless candidate reorder helper (NextWord-derived first-char set).
   * Pure function; engine state untouched. Routes through standard
   * EngineHandle::handle path (brief mutex acquire — no observable cost).
   * </pre>
   *
   * <code>.taigi.engine.BoostCandidates boost_candidates = 21;</code>
   * @return Whether the boostCandidates field is set.
   */
  boolean hasBoostCandidates();
  /**
   * <pre>
   * Stateless candidate reorder helper (NextWord-derived first-char set).
   * Pure function; engine state untouched. Routes through standard
   * EngineHandle::handle path (brief mutex acquire — no observable cost).
   * </pre>
   *
   * <code>.taigi.engine.BoostCandidates boost_candidates = 21;</code>
   * @return The boostCandidates.
   */
  com.siansiansu.taigikeyboard.engine.proto.BoostCandidates getBoostCandidates();

  /**
   * <pre>
   * Pure read — return StateSnapshot.
   * </pre>
   *
   * <code>.taigi.engine.NextWordQueryState query_state = 30;</code>
   * @return Whether the queryState field is set.
   */
  boolean hasQueryState();
  /**
   * <pre>
   * Pure read — return StateSnapshot.
   * </pre>
   *
   * <code>.taigi.engine.NextWordQueryState query_state = 30;</code>
   * @return The queryState.
   */
  com.siansiansu.taigikeyboard.engine.proto.NextWordQueryState getQueryState();

  public com.siansiansu.taigikeyboard.engine.proto.NextWordRequest.MethodCase getMethodCase();
}
