// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: phonetics.proto
// Protobuf Java Version: 4.36.0

package com.siansiansu.taigikeyboard.engine.proto;

/**
 * <pre>
 * `NormalizeTone` reads `AppConfig.input_mode` (POJ / TL) and
 * `AppConfig.oo_doubletap_enabled` / `nn_doubletap_enabled` from envelope's
 * per-request `config_snapshot`. Engine never caches settings.
 * </pre>
 *
 * Protobuf type {@code taigi.engine.NormalizeTone}
 */
@com.google.protobuf.Generated
public  final class NormalizeTone extends
    com.google.protobuf.GeneratedMessageLite<
        NormalizeTone, NormalizeTone.Builder> implements
    // @@protoc_insertion_point(message_implements:taigi.engine.NormalizeTone)
    NormalizeToneOrBuilder {
  private NormalizeTone() {
    input_ = "";
  }
  public static final int INPUT_FIELD_NUMBER = 1;
  private java.lang.String input_;
  /**
   * <code>string input = 1;</code>
   * @return The input.
   */
  @java.lang.Override
  public java.lang.String getInput() {
    return input_;
  }
  /**
   * <code>string input = 1;</code>
   * @return The bytes for input.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getInputBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(input_);
  }
  /**
   * <code>string input = 1;</code>
   * @param value The input to set.
   */
  private void setInput(
      java.lang.String value) {
    java.util.Objects.requireNonNull(value);

    input_ = value;
  }
  /**
   * <code>string input = 1;</code>
   */
  private void clearInput() {

    input_ = getDefaultInstance().getInput();
  }
  /**
   * <code>string input = 1;</code>
   * @param value The bytes for input to set.
   */
  private void setInputBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    input_ = value.toStringUtf8();

  }

  public static com.siansiansu.taigikeyboard.engine.proto.NormalizeTone parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.siansiansu.taigikeyboard.engine.proto.NormalizeTone parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.siansiansu.taigikeyboard.engine.proto.NormalizeTone parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.siansiansu.taigikeyboard.engine.proto.NormalizeTone parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.siansiansu.taigikeyboard.engine.proto.NormalizeTone parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.siansiansu.taigikeyboard.engine.proto.NormalizeTone parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.siansiansu.taigikeyboard.engine.proto.NormalizeTone parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.siansiansu.taigikeyboard.engine.proto.NormalizeTone parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static com.siansiansu.taigikeyboard.engine.proto.NormalizeTone parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }

  public static com.siansiansu.taigikeyboard.engine.proto.NormalizeTone parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static com.siansiansu.taigikeyboard.engine.proto.NormalizeTone parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.siansiansu.taigikeyboard.engine.proto.NormalizeTone parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }
  public static Builder newBuilder(com.siansiansu.taigikeyboard.engine.proto.NormalizeTone prototype) {
    return DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * <pre>
   * `NormalizeTone` reads `AppConfig.input_mode` (POJ / TL) and
   * `AppConfig.oo_doubletap_enabled` / `nn_doubletap_enabled` from envelope's
   * per-request `config_snapshot`. Engine never caches settings.
   * </pre>
   *
   * Protobuf type {@code taigi.engine.NormalizeTone}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        com.siansiansu.taigikeyboard.engine.proto.NormalizeTone, Builder> implements
      // @@protoc_insertion_point(builder_implements:taigi.engine.NormalizeTone)
      com.siansiansu.taigikeyboard.engine.proto.NormalizeToneOrBuilder {
    // Construct using com.siansiansu.taigikeyboard.engine.proto.NormalizeTone.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <code>string input = 1;</code>
     * @return The input.
     */
    @java.lang.Override
    public java.lang.String getInput() {
      return instance.getInput();
    }
    /**
     * <code>string input = 1;</code>
     * @return The bytes for input.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getInputBytes() {
      return instance.getInputBytes();
    }
    /**
     * <code>string input = 1;</code>
     * @param value The input to set.
     * @return This builder for chaining.
     */
    public Builder setInput(
        java.lang.String value) {
      copyOnWrite();
      instance.setInput(value);
      return this;
    }
    /**
     * <code>string input = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearInput() {
      copyOnWrite();
      instance.clearInput();
      return this;
    }
    /**
     * <code>string input = 1;</code>
     * @param value The bytes for input to set.
     * @return This builder for chaining.
     */
    public Builder setInputBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setInputBytes(value);
      return this;
    }

    // @@protoc_insertion_point(builder_scope:taigi.engine.NormalizeTone)
  }
  @java.lang.Override
  @java.lang.SuppressWarnings({"ThrowNull"})
  protected final java.lang.Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      java.lang.Object arg0, java.lang.Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new com.siansiansu.taigikeyboard.engine.proto.NormalizeTone();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
          java.lang.Object[] objects = new java.lang.Object[] {
            "input_",
          };
          java.lang.String info =
              "\u0000\u0001\u0000\u0000\u0001\u0001\u0001\u0000\u0000\u0000\u0001\u0208";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<com.siansiansu.taigikeyboard.engine.proto.NormalizeTone> parser = PARSER;
        if (parser == null) {
          synchronized (com.siansiansu.taigikeyboard.engine.proto.NormalizeTone.class) {
            parser = PARSER;
            if (parser == null) {
              parser =
                  new DefaultInstanceBasedParser<com.siansiansu.taigikeyboard.engine.proto.NormalizeTone>(
                      DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      // SET_MEMOIZED_IS_INITIALIZED is never called for this message.
      // So it can do anything. Combine with default case for smaller codegen.
      case SET_MEMOIZED_IS_INITIALIZED:
    }
    // Should never happen. Generates tight code to throw an exception.
    throw null;
  }


  // @@protoc_insertion_point(class_scope:taigi.engine.NormalizeTone)
  private static final com.siansiansu.taigikeyboard.engine.proto.NormalizeTone DEFAULT_INSTANCE;
  static {
    NormalizeTone defaultInstance = new NormalizeTone();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
      NormalizeTone.class, defaultInstance);
  }

  public static com.siansiansu.taigikeyboard.engine.proto.NormalizeTone getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<NormalizeTone> PARSER;

  public static com.google.protobuf.Parser<NormalizeTone> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}
