// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: phonetics.proto
// Protobuf Java Version: 4.35.1

package com.siansiansu.taigikeyboard.engine.proto;

@com.google.protobuf.Generated
public interface OptionalStringResultOrBuilder extends
    // @@protoc_insertion_point(interface_extends:taigi.engine.OptionalStringResult)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>string output = 1;</code>
   * @return The output.
   */
  java.lang.String getOutput();
  /**
   * <code>string output = 1;</code>
   * @return The bytes for output.
   */
  com.google.protobuf.ByteString
      getOutputBytes();

  /**
   * <code>bool present = 2;</code>
   * @return The present.
   */
  boolean getPresent();
}
