// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: nextword.proto
// Protobuf Java Version: 4.36.2

package com.siansiansu.taigikeyboard.engine.proto;

/**
 * <pre>
 * One next-word query: engine/dispatch looks up the bundled bigrams for the
 * last character of `word` (source mask from `toggles`, 2 x limit rows),
 * follows them with the rows its own `user_association.db` holds after
 * `word` / `roman` (best-evidence-first, never reordered), and runs
 * FilterPredictions. An empty `word` filters nothing. A bundled-lookup
 * failure (lexicon not installed) drops only the dict rows.
 * </pre>
 *
 * Protobuf type {@code taigi.engine.PredictNext}
 */
@com.google.protobuf.Generated
public  final class PredictNext extends
    com.google.protobuf.GeneratedMessageLite<
        PredictNext, PredictNext.Builder> implements
    // @@protoc_insertion_point(message_implements:taigi.engine.PredictNext)
    PredictNextOrBuilder {
  private PredictNext() {
    word_ = "";
    roman_ = "";
  }
  private int bitField0_;
  public static final int WORD_FIELD_NUMBER = 1;
  private java.lang.String word_;
  /**
   * <code>string word = 1;</code>
   * @return The word.
   */
  @java.lang.Override
  public java.lang.String getWord() {
    return word_;
  }
  /**
   * <code>string word = 1;</code>
   * @return The bytes for word.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getWordBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(word_);
  }
  /**
   * <code>string word = 1;</code>
   * @param value The word to set.
   */
  private void setWord(
      java.lang.String value) {
    java.util.Objects.requireNonNull(value);

    word_ = value;
  }
  /**
   * <code>string word = 1;</code>
   */
  private void clearWord() {

    word_ = getDefaultInstance().getWord();
  }
  /**
   * <code>string word = 1;</code>
   * @param value The bytes for word to set.
   */
  private void setWordBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    word_ = value.toStringUtf8();

  }

  public static final int TOGGLES_FIELD_NUMBER = 3;
  private com.siansiansu.taigikeyboard.engine.proto.DictionaryToggles toggles_;
  /**
   * <code>.taigi.engine.DictionaryToggles toggles = 3;</code>
   */
  @java.lang.Override
  public boolean hasToggles() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>.taigi.engine.DictionaryToggles toggles = 3;</code>
   */
  @java.lang.Override
  public com.siansiansu.taigikeyboard.engine.proto.DictionaryToggles getToggles() {
    return toggles_ == null ? com.siansiansu.taigikeyboard.engine.proto.DictionaryToggles.getDefaultInstance() : toggles_;
  }
  /**
   * <code>.taigi.engine.DictionaryToggles toggles = 3;</code>
   */
  private void setToggles(com.siansiansu.taigikeyboard.engine.proto.DictionaryToggles value) {
    java.util.Objects.requireNonNull(value);
    toggles_ = value;
    bitField0_ |= 0x00000001;
  }
  /**
   * <code>.taigi.engine.DictionaryToggles toggles = 3;</code>
   */
  @java.lang.SuppressWarnings("ReferenceEquality")
  private void mergeToggles(com.siansiansu.taigikeyboard.engine.proto.DictionaryToggles value) {
    java.util.Objects.requireNonNull(value);
    if (toggles_ != null &&
        toggles_ != com.siansiansu.taigikeyboard.engine.proto.DictionaryToggles.getDefaultInstance()) {
      toggles_ =
        com.siansiansu.taigikeyboard.engine.proto.DictionaryToggles.newBuilder(toggles_).mergeFrom(value).buildPartial();
    } else {
      toggles_ = value;
    }
    bitField0_ |= 0x00000001;
  }
  /**
   * <code>.taigi.engine.DictionaryToggles toggles = 3;</code>
   */
  private void clearToggles() {
    toggles_ = null;
    bitField0_ = (bitField0_ & ~0x00000001);
  }

  public static final int QUERY_GENERATION_FIELD_NUMBER = 4;
  private long queryGeneration_;
  /**
   * <code>uint64 query_generation = 4;</code>
   * @return The queryGeneration.
   */
  @java.lang.Override
  public long getQueryGeneration() {
    return queryGeneration_;
  }
  /**
   * <code>uint64 query_generation = 4;</code>
   * @param value The queryGeneration to set.
   */
  private void setQueryGeneration(long value) {

    queryGeneration_ = value;
  }
  /**
   * <code>uint64 query_generation = 4;</code>
   */
  private void clearQueryGeneration() {

    queryGeneration_ = 0L;
  }

  public static final int NOW_MS_FIELD_NUMBER = 5;
  private long nowMs_;
  /**
   * <code>int64 now_ms = 5;</code>
   * @return The nowMs.
   */
  @java.lang.Override
  public long getNowMs() {
    return nowMs_;
  }
  /**
   * <code>int64 now_ms = 5;</code>
   * @param value The nowMs to set.
   */
  private void setNowMs(long value) {

    nowMs_ = value;
  }
  /**
   * <code>int64 now_ms = 5;</code>
   */
  private void clearNowMs() {

    nowMs_ = 0L;
  }

  public static final int LIMIT_FIELD_NUMBER = 6;
  private int limit_;
  /**
   * <pre>
   * 30 default if 0
   * </pre>
   *
   * <code>int32 limit = 6;</code>
   * @return The limit.
   */
  @java.lang.Override
  public int getLimit() {
    return limit_;
  }
  /**
   * <pre>
   * 30 default if 0
   * </pre>
   *
   * <code>int32 limit = 6;</code>
   * @param value The limit to set.
   */
  private void setLimit(int value) {

    limit_ = value;
  }
  /**
   * <pre>
   * 30 default if 0
   * </pre>
   *
   * <code>int32 limit = 6;</code>
   */
  private void clearLimit() {

    limit_ = 0;
  }

  public static final int ROMAN_FIELD_NUMBER = 7;
  private java.lang.String roman_;
  /**
   * <pre>
   * The committed word's canonical TL — the `prev_tl` tier key of the user
   * rows' order (§24).
   * </pre>
   *
   * <code>string roman = 7;</code>
   * @return The roman.
   */
  @java.lang.Override
  public java.lang.String getRoman() {
    return roman_;
  }
  /**
   * <pre>
   * The committed word's canonical TL — the `prev_tl` tier key of the user
   * rows' order (§24).
   * </pre>
   *
   * <code>string roman = 7;</code>
   * @return The bytes for roman.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getRomanBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(roman_);
  }
  /**
   * <pre>
   * The committed word's canonical TL — the `prev_tl` tier key of the user
   * rows' order (§24).
   * </pre>
   *
   * <code>string roman = 7;</code>
   * @param value The roman to set.
   */
  private void setRoman(
      java.lang.String value) {
    java.util.Objects.requireNonNull(value);

    roman_ = value;
  }
  /**
   * <pre>
   * The committed word's canonical TL — the `prev_tl` tier key of the user
   * rows' order (§24).
   * </pre>
   *
   * <code>string roman = 7;</code>
   */
  private void clearRoman() {

    roman_ = getDefaultInstance().getRoman();
  }
  /**
   * <pre>
   * The committed word's canonical TL — the `prev_tl` tier key of the user
   * rows' order (§24).
   * </pre>
   *
   * <code>string roman = 7;</code>
   * @param value The bytes for roman to set.
   */
  private void setRomanBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    roman_ = value.toStringUtf8();

  }

  public static com.siansiansu.taigikeyboard.engine.proto.PredictNext parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.siansiansu.taigikeyboard.engine.proto.PredictNext parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.siansiansu.taigikeyboard.engine.proto.PredictNext parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.siansiansu.taigikeyboard.engine.proto.PredictNext parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.siansiansu.taigikeyboard.engine.proto.PredictNext parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.siansiansu.taigikeyboard.engine.proto.PredictNext parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.siansiansu.taigikeyboard.engine.proto.PredictNext parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.siansiansu.taigikeyboard.engine.proto.PredictNext parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static com.siansiansu.taigikeyboard.engine.proto.PredictNext parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }

  public static com.siansiansu.taigikeyboard.engine.proto.PredictNext parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static com.siansiansu.taigikeyboard.engine.proto.PredictNext parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.siansiansu.taigikeyboard.engine.proto.PredictNext parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }
  public static Builder newBuilder(com.siansiansu.taigikeyboard.engine.proto.PredictNext prototype) {
    return DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * <pre>
   * One next-word query: engine/dispatch looks up the bundled bigrams for the
   * last character of `word` (source mask from `toggles`, 2 x limit rows),
   * follows them with the rows its own `user_association.db` holds after
   * `word` / `roman` (best-evidence-first, never reordered), and runs
   * FilterPredictions. An empty `word` filters nothing. A bundled-lookup
   * failure (lexicon not installed) drops only the dict rows.
   * </pre>
   *
   * Protobuf type {@code taigi.engine.PredictNext}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        com.siansiansu.taigikeyboard.engine.proto.PredictNext, Builder> implements
      // @@protoc_insertion_point(builder_implements:taigi.engine.PredictNext)
      com.siansiansu.taigikeyboard.engine.proto.PredictNextOrBuilder {
    // Construct using com.siansiansu.taigikeyboard.engine.proto.PredictNext.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <code>string word = 1;</code>
     * @return The word.
     */
    @java.lang.Override
    public java.lang.String getWord() {
      return instance.getWord();
    }
    /**
     * <code>string word = 1;</code>
     * @return The bytes for word.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getWordBytes() {
      return instance.getWordBytes();
    }
    /**
     * <code>string word = 1;</code>
     * @param value The word to set.
     * @return This builder for chaining.
     */
    public Builder setWord(
        java.lang.String value) {
      copyOnWrite();
      instance.setWord(value);
      return this;
    }
    /**
     * <code>string word = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearWord() {
      copyOnWrite();
      instance.clearWord();
      return this;
    }
    /**
     * <code>string word = 1;</code>
     * @param value The bytes for word to set.
     * @return This builder for chaining.
     */
    public Builder setWordBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setWordBytes(value);
      return this;
    }

    /**
     * <code>.taigi.engine.DictionaryToggles toggles = 3;</code>
     */
    @java.lang.Override
    public boolean hasToggles() {
      return instance.hasToggles();
    }
    /**
     * <code>.taigi.engine.DictionaryToggles toggles = 3;</code>
     */
    @java.lang.Override
    public com.siansiansu.taigikeyboard.engine.proto.DictionaryToggles getToggles() {
      return instance.getToggles();
    }
    /**
     * <code>.taigi.engine.DictionaryToggles toggles = 3;</code>
     */
    public Builder setToggles(com.siansiansu.taigikeyboard.engine.proto.DictionaryToggles value) {
      copyOnWrite();
      instance.setToggles(value);
      return this;
      }
    /**
     * <code>.taigi.engine.DictionaryToggles toggles = 3;</code>
     */
    public Builder setToggles(
        com.siansiansu.taigikeyboard.engine.proto.DictionaryToggles.Builder builderForValue) {
      copyOnWrite();
      instance.setToggles(builderForValue.build());
      return this;
    }
    /**
     * <code>.taigi.engine.DictionaryToggles toggles = 3;</code>
     */
    public Builder mergeToggles(com.siansiansu.taigikeyboard.engine.proto.DictionaryToggles value) {
      copyOnWrite();
      instance.mergeToggles(value);
      return this;
    }
    /**
     * <code>.taigi.engine.DictionaryToggles toggles = 3;</code>
     */
    public Builder clearToggles() {  copyOnWrite();
      instance.clearToggles();
      return this;
    }

    /**
     * <code>uint64 query_generation = 4;</code>
     * @return The queryGeneration.
     */
    @java.lang.Override
    public long getQueryGeneration() {
      return instance.getQueryGeneration();
    }
    /**
     * <code>uint64 query_generation = 4;</code>
     * @param value The queryGeneration to set.
     * @return This builder for chaining.
     */
    public Builder setQueryGeneration(long value) {
      copyOnWrite();
      instance.setQueryGeneration(value);
      return this;
    }
    /**
     * <code>uint64 query_generation = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearQueryGeneration() {
      copyOnWrite();
      instance.clearQueryGeneration();
      return this;
    }

    /**
     * <code>int64 now_ms = 5;</code>
     * @return The nowMs.
     */
    @java.lang.Override
    public long getNowMs() {
      return instance.getNowMs();
    }
    /**
     * <code>int64 now_ms = 5;</code>
     * @param value The nowMs to set.
     * @return This builder for chaining.
     */
    public Builder setNowMs(long value) {
      copyOnWrite();
      instance.setNowMs(value);
      return this;
    }
    /**
     * <code>int64 now_ms = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearNowMs() {
      copyOnWrite();
      instance.clearNowMs();
      return this;
    }

    /**
     * <pre>
     * 30 default if 0
     * </pre>
     *
     * <code>int32 limit = 6;</code>
     * @return The limit.
     */
    @java.lang.Override
    public int getLimit() {
      return instance.getLimit();
    }
    /**
     * <pre>
     * 30 default if 0
     * </pre>
     *
     * <code>int32 limit = 6;</code>
     * @param value The limit to set.
     * @return This builder for chaining.
     */
    public Builder setLimit(int value) {
      copyOnWrite();
      instance.setLimit(value);
      return this;
    }
    /**
     * <pre>
     * 30 default if 0
     * </pre>
     *
     * <code>int32 limit = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearLimit() {
      copyOnWrite();
      instance.clearLimit();
      return this;
    }

    /**
     * <pre>
     * The committed word's canonical TL — the `prev_tl` tier key of the user
     * rows' order (§24).
     * </pre>
     *
     * <code>string roman = 7;</code>
     * @return The roman.
     */
    @java.lang.Override
    public java.lang.String getRoman() {
      return instance.getRoman();
    }
    /**
     * <pre>
     * The committed word's canonical TL — the `prev_tl` tier key of the user
     * rows' order (§24).
     * </pre>
     *
     * <code>string roman = 7;</code>
     * @return The bytes for roman.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getRomanBytes() {
      return instance.getRomanBytes();
    }
    /**
     * <pre>
     * The committed word's canonical TL — the `prev_tl` tier key of the user
     * rows' order (§24).
     * </pre>
     *
     * <code>string roman = 7;</code>
     * @param value The roman to set.
     * @return This builder for chaining.
     */
    public Builder setRoman(
        java.lang.String value) {
      copyOnWrite();
      instance.setRoman(value);
      return this;
    }
    /**
     * <pre>
     * The committed word's canonical TL — the `prev_tl` tier key of the user
     * rows' order (§24).
     * </pre>
     *
     * <code>string roman = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearRoman() {
      copyOnWrite();
      instance.clearRoman();
      return this;
    }
    /**
     * <pre>
     * The committed word's canonical TL — the `prev_tl` tier key of the user
     * rows' order (§24).
     * </pre>
     *
     * <code>string roman = 7;</code>
     * @param value The bytes for roman to set.
     * @return This builder for chaining.
     */
    public Builder setRomanBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setRomanBytes(value);
      return this;
    }

    // @@protoc_insertion_point(builder_scope:taigi.engine.PredictNext)
  }
  @java.lang.Override
  @java.lang.SuppressWarnings({"ThrowNull"})
  protected final java.lang.Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      java.lang.Object arg0, java.lang.Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new com.siansiansu.taigikeyboard.engine.proto.PredictNext();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
          java.lang.Object[] objects = new java.lang.Object[] {
            "bitField0_",
            "word_",
            "toggles_",
            "queryGeneration_",
            "nowMs_",
            "limit_",
            "roman_",
          };
          java.lang.String info =
              "\u0000\u0006\u0000\u0001\u0001\u0007\u0006\u0000\u0000\u0000\u0001\u0208\u0003\u1009" +
              "\u0000\u0004\u0003\u0005\u0002\u0006\u0004\u0007\u0208";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<com.siansiansu.taigikeyboard.engine.proto.PredictNext> parser = PARSER;
        if (parser == null) {
          synchronized (com.siansiansu.taigikeyboard.engine.proto.PredictNext.class) {
            parser = PARSER;
            if (parser == null) {
              parser =
                  new DefaultInstanceBasedParser<com.siansiansu.taigikeyboard.engine.proto.PredictNext>(
                      DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      // SET_MEMOIZED_IS_INITIALIZED is never called for this message.
      // So it can do anything. Combine with default case for smaller codegen.
      case SET_MEMOIZED_IS_INITIALIZED:
    }
    // Should never happen. Generates tight code to throw an exception.
    throw null;
  }


  // @@protoc_insertion_point(class_scope:taigi.engine.PredictNext)
  private static final com.siansiansu.taigikeyboard.engine.proto.PredictNext DEFAULT_INSTANCE;
  static {
    PredictNext defaultInstance = new PredictNext();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
      PredictNext.class, defaultInstance);
  }

  public static com.siansiansu.taigikeyboard.engine.proto.PredictNext getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<PredictNext> PARSER;

  public static com.google.protobuf.Parser<PredictNext> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}
