// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: lexicon.proto
// Protobuf Java Version: 4.35.1

package com.siansiansu.taigikeyboard.engine.proto;

@com.google.protobuf.Generated
public interface ProcessCandidatesRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:taigi.engine.ProcessCandidatesRequest)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>repeated .taigi.engine.TaigiWord raw = 1;</code>
   */
  java.util.List<com.siansiansu.taigikeyboard.engine.proto.TaigiWord>
      getRawList();
  /**
   * <code>repeated .taigi.engine.TaigiWord raw = 1;</code>
   */
  com.siansiansu.taigikeyboard.engine.proto.TaigiWord getRaw(int index);
  /**
   * <code>repeated .taigi.engine.TaigiWord raw = 1;</code>
   */
  int getRawCount();

  /**
   * <code>string normalized_input = 2;</code>
   * @return The normalizedInput.
   */
  java.lang.String getNormalizedInput();
  /**
   * <code>string normalized_input = 2;</code>
   * @return The bytes for normalizedInput.
   */
  com.google.protobuf.ByteString
      getNormalizedInputBytes();

  /**
   * <code>bool tps_dedup_enabled = 4;</code>
   * @return The tpsDedupEnabled.
   */
  boolean getTpsDedupEnabled();

  /**
   * <code>repeated .taigi.engine.FrequencyEntry freq = 5;</code>
   */
  java.util.List<com.siansiansu.taigikeyboard.engine.proto.FrequencyEntry>
      getFreqList();
  /**
   * <code>repeated .taigi.engine.FrequencyEntry freq = 5;</code>
   */
  com.siansiansu.taigikeyboard.engine.proto.FrequencyEntry getFreq(int index);
  /**
   * <code>repeated .taigi.engine.FrequencyEntry freq = 5;</code>
   */
  int getFreqCount();

  /**
   * <code>int64 now_ms = 6;</code>
   * @return The nowMs.
   */
  long getNowMs();

  /**
   * <code>bool include_breakdown = 7;</code>
   * @return The includeBreakdown.
   */
  boolean getIncludeBreakdown();

  /**
   * <pre>
   * `merge_order_only = true` skips score + sort and returns the
   * dedup result directly in input (merged) order. Replaces iOS
   * `LexiconService` cold-start fallback that previously used Swift
   * `CandidateProcessor.removeDuplicates` + `removeDisplayDuplicates`.
   * Output `breakdown` is always empty when this flag is set —
   * there is no scoring to break down. `now_ms` and `freq` are
   * ignored. `tps_dedup_enabled` still gates the display dedup pass
   * (must run AFTER the engine dedup, same ordering invariant as
   * the score path).
   * </pre>
   *
   * <code>bool merge_order_only = 8;</code>
   * @return The mergeOrderOnly.
   */
  boolean getMergeOrderOnly();
}
