// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: user_data.proto
// Protobuf Java Version: 4.36.2

package com.siansiansu.taigikeyboard.engine.proto;

@com.google.protobuf.Generated
public interface RecordUsageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:taigi.engine.RecordUsage)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>string display_text = 1;</code>
   * @return The displayText.
   */
  java.lang.String getDisplayText();
  /**
   * <code>string display_text = 1;</code>
   * @return The bytes for displayText.
   */
  com.google.protobuf.ByteString
      getDisplayTextBytes();

  /**
   * <code>string canonical_tl = 2;</code>
   * @return The canonicalTl.
   */
  java.lang.String getCanonicalTl();
  /**
   * <code>string canonical_tl = 2;</code>
   * @return The bytes for canonicalTl.
   */
  com.google.protobuf.ByteString
      getCanonicalTlBytes();

  /**
   * <pre>
   * The picked candidate's Hanji, when it has one (a learned phrase can
   * only be touched by its Hanji); absent for a Hanji-less pick.
   * </pre>
   *
   * <code>optional string hanji = 3;</code>
   * @return Whether the hanji field is set.
   */
  boolean hasHanji();
  /**
   * <pre>
   * The picked candidate's Hanji, when it has one (a learned phrase can
   * only be touched by its Hanji); absent for a Hanji-less pick.
   * </pre>
   *
   * <code>optional string hanji = 3;</code>
   * @return The hanji.
   */
  java.lang.String getHanji();
  /**
   * <pre>
   * The picked candidate's Hanji, when it has one (a learned phrase can
   * only be touched by its Hanji); absent for a Hanji-less pick.
   * </pre>
   *
   * <code>optional string hanji = 3;</code>
   * @return The bytes for hanji.
   */
  com.google.protobuf.ByteString
      getHanjiBytes();

  /**
   * <pre>
   * The desktop's frequency-recording setting, OFF: no count is kept, the
   * learned-phrase touch still is (it is learning data, always on — §50).
   * Negative so an un-wired build records, as the phones always do.
   * </pre>
   *
   * <code>bool frequency_recording_disabled = 4;</code>
   * @return The frequencyRecordingDisabled.
   */
  boolean getFrequencyRecordingDisabled();
}
