// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: composing.proto
// Protobuf Java Version: 4.27.5

package com.siansiansu.taigikeyboard.engine.proto;

public interface ReplaceLastOrBuilder extends
    // @@protoc_insertion_point(interface_extends:taigi.engine.ReplaceLast)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>string replacement = 1;</code>
   * @return The replacement.
   */
  java.lang.String getReplacement();
  /**
   * <code>string replacement = 1;</code>
   * @return The bytes for replacement.
   */
  com.google.protobuf.ByteString
      getReplacementBytes();
}
