// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: composing.proto
// Protobuf Java Version: 4.36.0

package com.siansiansu.taigikeyboard.engine.proto;

@com.google.protobuf.Generated
public interface ResetAutocompleteOrBuilder extends
    // @@protoc_insertion_point(interface_extends:taigi.engine.ResetAutocomplete)
    com.google.protobuf.MessageLiteOrBuilder {
}
