// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: nextword.proto
// Protobuf Java Version: 4.35.1

package com.siansiansu.taigikeyboard.engine.proto;

@com.google.protobuf.Generated
public interface StateSnapshotOrBuilder extends
    // @@protoc_insertion_point(interface_extends:taigi.engine.StateSnapshot)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <pre>
   * "" == nil
   * </pre>
   *
   * <code>string last_selected_word = 1;</code>
   * @return The lastSelectedWord.
   */
  java.lang.String getLastSelectedWord();
  /**
   * <pre>
   * "" == nil
   * </pre>
   *
   * <code>string last_selected_word = 1;</code>
   * @return The bytes for lastSelectedWord.
   */
  com.google.protobuf.ByteString
      getLastSelectedWordBytes();

  /**
   * <code>bool is_showing = 2;</code>
   * @return The isShowing.
   */
  boolean getIsShowing();

  /**
   * <code>uint64 current_generation = 3;</code>
   * @return The currentGeneration.
   */
  long getCurrentGeneration();
}
