// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: phonetics.proto
// Protobuf Java Version: 4.36.0

package com.siansiansu.taigikeyboard.engine.proto;

/**
 * <pre>
 * `ToneVariationsResult` is the callout init-pull payload. Maps the base
 * char (e.g. "a") to its toned variations list (e.g. ["á", "à", "â", ...]).
 * </pre>
 *
 * Protobuf type {@code taigi.engine.ToneVariationsResult}
 */
@com.google.protobuf.Generated
public  final class ToneVariationsResult extends
    com.google.protobuf.GeneratedMessageLite<
        ToneVariationsResult, ToneVariationsResult.Builder> implements
    // @@protoc_insertion_point(message_implements:taigi.engine.ToneVariationsResult)
    ToneVariationsResultOrBuilder {
  private ToneVariationsResult() {
  }
  public static final int POJ_VARIATIONS_FIELD_NUMBER = 1;
  private static final class PojVariationsDefaultEntryHolder {
    static final com.google.protobuf.MapEntryLite<
        java.lang.String, com.siansiansu.taigikeyboard.engine.proto.ToneVariationList> defaultEntry =
            com.google.protobuf.MapEntryLite
            .<java.lang.String, com.siansiansu.taigikeyboard.engine.proto.ToneVariationList>newDefaultInstance(
                com.google.protobuf.WireFormat.FieldType.STRING,
                "",
                com.google.protobuf.WireFormat.FieldType.MESSAGE,
                com.siansiansu.taigikeyboard.engine.proto.ToneVariationList.getDefaultInstance());
  }
  private com.google.protobuf.MapFieldLite<
      java.lang.String, com.siansiansu.taigikeyboard.engine.proto.ToneVariationList> pojVariations_ =
          com.google.protobuf.MapFieldLite.emptyMapField();
  private com.google.protobuf.MapFieldLite<java.lang.String, com.siansiansu.taigikeyboard.engine.proto.ToneVariationList>
  internalGetPojVariations() {
    return pojVariations_;
  }
  private com.google.protobuf.MapFieldLite<java.lang.String, com.siansiansu.taigikeyboard.engine.proto.ToneVariationList>
  internalGetMutablePojVariations() {
    if (!pojVariations_.isMutable()) {
      pojVariations_ = pojVariations_.mutableCopy();
    }
    return pojVariations_;
  }
  @java.lang.Override

  public int getPojVariationsCount() {
    return internalGetPojVariations().size();
  }
  /**
   * <code>map&lt;string, .taigi.engine.ToneVariationList&gt; poj_variations = 1;</code>
   */
  @java.lang.Override

  public boolean containsPojVariations(
      java.lang.String key) {
    java.util.Objects.requireNonNull(key);
    return internalGetPojVariations().containsKey(key);
  }
  /**
   * Use {@link #getPojVariationsMap()} instead.
   */
  @java.lang.Override
  @java.lang.Deprecated
  public java.util.Map<java.lang.String, com.siansiansu.taigikeyboard.engine.proto.ToneVariationList> getPojVariations() {
    return getPojVariationsMap();
  }
  /**
   * <code>map&lt;string, .taigi.engine.ToneVariationList&gt; poj_variations = 1;</code>
   */
  @java.lang.Override

  public java.util.Map<java.lang.String, com.siansiansu.taigikeyboard.engine.proto.ToneVariationList> getPojVariationsMap() {
    return java.util.Collections.unmodifiableMap(
        internalGetPojVariations());
  }
  /**
   * <code>map&lt;string, .taigi.engine.ToneVariationList&gt; poj_variations = 1;</code>
   */
  @java.lang.Override

  public /* nullable */
com.siansiansu.taigikeyboard.engine.proto.ToneVariationList getPojVariationsOrDefault(
      java.lang.String key,
      /* nullable */
com.siansiansu.taigikeyboard.engine.proto.ToneVariationList defaultValue) {
    java.util.Objects.requireNonNull(key);
    java.util.Map<java.lang.String, com.siansiansu.taigikeyboard.engine.proto.ToneVariationList> map =
        internalGetPojVariations();
    com.siansiansu.taigikeyboard.engine.proto.ToneVariationList v = map.get(key);
    return v != null ? v : defaultValue;
  }
  /**
   * <code>map&lt;string, .taigi.engine.ToneVariationList&gt; poj_variations = 1;</code>
   */
  @java.lang.Override

  public com.siansiansu.taigikeyboard.engine.proto.ToneVariationList getPojVariationsOrThrow(
      java.lang.String key) {
    java.util.Objects.requireNonNull(key);
    java.util.Map<java.lang.String, com.siansiansu.taigikeyboard.engine.proto.ToneVariationList> map =
        internalGetPojVariations();
    com.siansiansu.taigikeyboard.engine.proto.ToneVariationList v = map.get(key);
    if (v == null) {
      throw new java.lang.IllegalArgumentException();
    }
    return v;
  }
  /**
   * <code>map&lt;string, .taigi.engine.ToneVariationList&gt; poj_variations = 1;</code>
   */
  private java.util.Map<java.lang.String, com.siansiansu.taigikeyboard.engine.proto.ToneVariationList>
  getMutablePojVariationsMap() {
    return internalGetMutablePojVariations();
  }

  public static final int TL_VARIATIONS_FIELD_NUMBER = 2;
  private static final class TlVariationsDefaultEntryHolder {
    static final com.google.protobuf.MapEntryLite<
        java.lang.String, com.siansiansu.taigikeyboard.engine.proto.ToneVariationList> defaultEntry =
            com.google.protobuf.MapEntryLite
            .<java.lang.String, com.siansiansu.taigikeyboard.engine.proto.ToneVariationList>newDefaultInstance(
                com.google.protobuf.WireFormat.FieldType.STRING,
                "",
                com.google.protobuf.WireFormat.FieldType.MESSAGE,
                com.siansiansu.taigikeyboard.engine.proto.ToneVariationList.getDefaultInstance());
  }
  private com.google.protobuf.MapFieldLite<
      java.lang.String, com.siansiansu.taigikeyboard.engine.proto.ToneVariationList> tlVariations_ =
          com.google.protobuf.MapFieldLite.emptyMapField();
  private com.google.protobuf.MapFieldLite<java.lang.String, com.siansiansu.taigikeyboard.engine.proto.ToneVariationList>
  internalGetTlVariations() {
    return tlVariations_;
  }
  private com.google.protobuf.MapFieldLite<java.lang.String, com.siansiansu.taigikeyboard.engine.proto.ToneVariationList>
  internalGetMutableTlVariations() {
    if (!tlVariations_.isMutable()) {
      tlVariations_ = tlVariations_.mutableCopy();
    }
    return tlVariations_;
  }
  @java.lang.Override

  public int getTlVariationsCount() {
    return internalGetTlVariations().size();
  }
  /**
   * <code>map&lt;string, .taigi.engine.ToneVariationList&gt; tl_variations = 2;</code>
   */
  @java.lang.Override

  public boolean containsTlVariations(
      java.lang.String key) {
    java.util.Objects.requireNonNull(key);
    return internalGetTlVariations().containsKey(key);
  }
  /**
   * Use {@link #getTlVariationsMap()} instead.
   */
  @java.lang.Override
  @java.lang.Deprecated
  public java.util.Map<java.lang.String, com.siansiansu.taigikeyboard.engine.proto.ToneVariationList> getTlVariations() {
    return getTlVariationsMap();
  }
  /**
   * <code>map&lt;string, .taigi.engine.ToneVariationList&gt; tl_variations = 2;</code>
   */
  @java.lang.Override

  public java.util.Map<java.lang.String, com.siansiansu.taigikeyboard.engine.proto.ToneVariationList> getTlVariationsMap() {
    return java.util.Collections.unmodifiableMap(
        internalGetTlVariations());
  }
  /**
   * <code>map&lt;string, .taigi.engine.ToneVariationList&gt; tl_variations = 2;</code>
   */
  @java.lang.Override

  public /* nullable */
com.siansiansu.taigikeyboard.engine.proto.ToneVariationList getTlVariationsOrDefault(
      java.lang.String key,
      /* nullable */
com.siansiansu.taigikeyboard.engine.proto.ToneVariationList defaultValue) {
    java.util.Objects.requireNonNull(key);
    java.util.Map<java.lang.String, com.siansiansu.taigikeyboard.engine.proto.ToneVariationList> map =
        internalGetTlVariations();
    com.siansiansu.taigikeyboard.engine.proto.ToneVariationList v = map.get(key);
    return v != null ? v : defaultValue;
  }
  /**
   * <code>map&lt;string, .taigi.engine.ToneVariationList&gt; tl_variations = 2;</code>
   */
  @java.lang.Override

  public com.siansiansu.taigikeyboard.engine.proto.ToneVariationList getTlVariationsOrThrow(
      java.lang.String key) {
    java.util.Objects.requireNonNull(key);
    java.util.Map<java.lang.String, com.siansiansu.taigikeyboard.engine.proto.ToneVariationList> map =
        internalGetTlVariations();
    com.siansiansu.taigikeyboard.engine.proto.ToneVariationList v = map.get(key);
    if (v == null) {
      throw new java.lang.IllegalArgumentException();
    }
    return v;
  }
  /**
   * <code>map&lt;string, .taigi.engine.ToneVariationList&gt; tl_variations = 2;</code>
   */
  private java.util.Map<java.lang.String, com.siansiansu.taigikeyboard.engine.proto.ToneVariationList>
  getMutableTlVariationsMap() {
    return internalGetMutableTlVariations();
  }

  public static com.siansiansu.taigikeyboard.engine.proto.ToneVariationsResult parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.siansiansu.taigikeyboard.engine.proto.ToneVariationsResult parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.siansiansu.taigikeyboard.engine.proto.ToneVariationsResult parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.siansiansu.taigikeyboard.engine.proto.ToneVariationsResult parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.siansiansu.taigikeyboard.engine.proto.ToneVariationsResult parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.siansiansu.taigikeyboard.engine.proto.ToneVariationsResult parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.siansiansu.taigikeyboard.engine.proto.ToneVariationsResult parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.siansiansu.taigikeyboard.engine.proto.ToneVariationsResult parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static com.siansiansu.taigikeyboard.engine.proto.ToneVariationsResult parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }

  public static com.siansiansu.taigikeyboard.engine.proto.ToneVariationsResult parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static com.siansiansu.taigikeyboard.engine.proto.ToneVariationsResult parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.siansiansu.taigikeyboard.engine.proto.ToneVariationsResult parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }
  public static Builder newBuilder(com.siansiansu.taigikeyboard.engine.proto.ToneVariationsResult prototype) {
    return DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * <pre>
   * `ToneVariationsResult` is the callout init-pull payload. Maps the base
   * char (e.g. "a") to its toned variations list (e.g. ["á", "à", "â", ...]).
   * </pre>
   *
   * Protobuf type {@code taigi.engine.ToneVariationsResult}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        com.siansiansu.taigikeyboard.engine.proto.ToneVariationsResult, Builder> implements
      // @@protoc_insertion_point(builder_implements:taigi.engine.ToneVariationsResult)
      com.siansiansu.taigikeyboard.engine.proto.ToneVariationsResultOrBuilder {
    // Construct using com.siansiansu.taigikeyboard.engine.proto.ToneVariationsResult.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    @java.lang.Override

    public int getPojVariationsCount() {
      return instance.getPojVariationsMap().size();
    }
    /**
     * <code>map&lt;string, .taigi.engine.ToneVariationList&gt; poj_variations = 1;</code>
     */
    @java.lang.Override

    public boolean containsPojVariations(
        java.lang.String key) {
      java.util.Objects.requireNonNull(key);
      return instance.getPojVariationsMap().containsKey(key);
    }

    public Builder clearPojVariations() {
      copyOnWrite();
      instance.getMutablePojVariationsMap().clear();
      return this;
    }
    /**
     * <code>map&lt;string, .taigi.engine.ToneVariationList&gt; poj_variations = 1;</code>
     */

    public Builder removePojVariations(
        java.lang.String key) {
      java.util.Objects.requireNonNull(key);
      copyOnWrite();
      instance.getMutablePojVariationsMap().remove(key);
      return this;
    }
    /**
     * Use {@link #getPojVariationsMap()} instead.
     */
    @java.lang.Override
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, com.siansiansu.taigikeyboard.engine.proto.ToneVariationList> getPojVariations() {
      return getPojVariationsMap();
    }
    /**
     * <code>map&lt;string, .taigi.engine.ToneVariationList&gt; poj_variations = 1;</code>
     */
    @java.lang.Override
    public java.util.Map<java.lang.String, com.siansiansu.taigikeyboard.engine.proto.ToneVariationList> getPojVariationsMap() {
      return java.util.Collections.unmodifiableMap(
          instance.getPojVariationsMap());
    }
    /**
     * <code>map&lt;string, .taigi.engine.ToneVariationList&gt; poj_variations = 1;</code>
     */
    @java.lang.Override

    public /* nullable */
com.siansiansu.taigikeyboard.engine.proto.ToneVariationList getPojVariationsOrDefault(
        java.lang.String key,
        /* nullable */
com.siansiansu.taigikeyboard.engine.proto.ToneVariationList defaultValue) {
      java.util.Objects.requireNonNull(key);
      java.util.Map<java.lang.String, com.siansiansu.taigikeyboard.engine.proto.ToneVariationList> map =
          instance.getPojVariationsMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <code>map&lt;string, .taigi.engine.ToneVariationList&gt; poj_variations = 1;</code>
     */
    @java.lang.Override

    public com.siansiansu.taigikeyboard.engine.proto.ToneVariationList getPojVariationsOrThrow(
        java.lang.String key) {
      java.util.Objects.requireNonNull(key);
      java.util.Map<java.lang.String, com.siansiansu.taigikeyboard.engine.proto.ToneVariationList> map =
          instance.getPojVariationsMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }
    /**
     * <code>map&lt;string, .taigi.engine.ToneVariationList&gt; poj_variations = 1;</code>
     */
    public Builder putPojVariations(
        java.lang.String key,
        com.siansiansu.taigikeyboard.engine.proto.ToneVariationList value) {
      java.util.Objects.requireNonNull(key);
      java.util.Objects.requireNonNull(value);
      copyOnWrite();
      instance.getMutablePojVariationsMap().put(key, value);
      return this;
    }
    /**
     * <code>map&lt;string, .taigi.engine.ToneVariationList&gt; poj_variations = 1;</code>
     */
    public Builder putAllPojVariations(
        java.util.Map<java.lang.String, com.siansiansu.taigikeyboard.engine.proto.ToneVariationList> values) {
      copyOnWrite();
      instance.getMutablePojVariationsMap().putAll(values);
      return this;
    }

    @java.lang.Override

    public int getTlVariationsCount() {
      return instance.getTlVariationsMap().size();
    }
    /**
     * <code>map&lt;string, .taigi.engine.ToneVariationList&gt; tl_variations = 2;</code>
     */
    @java.lang.Override

    public boolean containsTlVariations(
        java.lang.String key) {
      java.util.Objects.requireNonNull(key);
      return instance.getTlVariationsMap().containsKey(key);
    }

    public Builder clearTlVariations() {
      copyOnWrite();
      instance.getMutableTlVariationsMap().clear();
      return this;
    }
    /**
     * <code>map&lt;string, .taigi.engine.ToneVariationList&gt; tl_variations = 2;</code>
     */

    public Builder removeTlVariations(
        java.lang.String key) {
      java.util.Objects.requireNonNull(key);
      copyOnWrite();
      instance.getMutableTlVariationsMap().remove(key);
      return this;
    }
    /**
     * Use {@link #getTlVariationsMap()} instead.
     */
    @java.lang.Override
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, com.siansiansu.taigikeyboard.engine.proto.ToneVariationList> getTlVariations() {
      return getTlVariationsMap();
    }
    /**
     * <code>map&lt;string, .taigi.engine.ToneVariationList&gt; tl_variations = 2;</code>
     */
    @java.lang.Override
    public java.util.Map<java.lang.String, com.siansiansu.taigikeyboard.engine.proto.ToneVariationList> getTlVariationsMap() {
      return java.util.Collections.unmodifiableMap(
          instance.getTlVariationsMap());
    }
    /**
     * <code>map&lt;string, .taigi.engine.ToneVariationList&gt; tl_variations = 2;</code>
     */
    @java.lang.Override

    public /* nullable */
com.siansiansu.taigikeyboard.engine.proto.ToneVariationList getTlVariationsOrDefault(
        java.lang.String key,
        /* nullable */
com.siansiansu.taigikeyboard.engine.proto.ToneVariationList defaultValue) {
      java.util.Objects.requireNonNull(key);
      java.util.Map<java.lang.String, com.siansiansu.taigikeyboard.engine.proto.ToneVariationList> map =
          instance.getTlVariationsMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <code>map&lt;string, .taigi.engine.ToneVariationList&gt; tl_variations = 2;</code>
     */
    @java.lang.Override

    public com.siansiansu.taigikeyboard.engine.proto.ToneVariationList getTlVariationsOrThrow(
        java.lang.String key) {
      java.util.Objects.requireNonNull(key);
      java.util.Map<java.lang.String, com.siansiansu.taigikeyboard.engine.proto.ToneVariationList> map =
          instance.getTlVariationsMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }
    /**
     * <code>map&lt;string, .taigi.engine.ToneVariationList&gt; tl_variations = 2;</code>
     */
    public Builder putTlVariations(
        java.lang.String key,
        com.siansiansu.taigikeyboard.engine.proto.ToneVariationList value) {
      java.util.Objects.requireNonNull(key);
      java.util.Objects.requireNonNull(value);
      copyOnWrite();
      instance.getMutableTlVariationsMap().put(key, value);
      return this;
    }
    /**
     * <code>map&lt;string, .taigi.engine.ToneVariationList&gt; tl_variations = 2;</code>
     */
    public Builder putAllTlVariations(
        java.util.Map<java.lang.String, com.siansiansu.taigikeyboard.engine.proto.ToneVariationList> values) {
      copyOnWrite();
      instance.getMutableTlVariationsMap().putAll(values);
      return this;
    }

    // @@protoc_insertion_point(builder_scope:taigi.engine.ToneVariationsResult)
  }
  @java.lang.Override
  @java.lang.SuppressWarnings({"ThrowNull"})
  protected final java.lang.Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      java.lang.Object arg0, java.lang.Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new com.siansiansu.taigikeyboard.engine.proto.ToneVariationsResult();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
          java.lang.Object[] objects = new java.lang.Object[] {
            "pojVariations_",
            PojVariationsDefaultEntryHolder.defaultEntry,
            "tlVariations_",
            TlVariationsDefaultEntryHolder.defaultEntry,
          };
          java.lang.String info =
              "\u0000\u0002\u0000\u0000\u0001\u0002\u0002\u0002\u0000\u0000\u00012\u00022";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<com.siansiansu.taigikeyboard.engine.proto.ToneVariationsResult> parser = PARSER;
        if (parser == null) {
          synchronized (com.siansiansu.taigikeyboard.engine.proto.ToneVariationsResult.class) {
            parser = PARSER;
            if (parser == null) {
              parser =
                  new DefaultInstanceBasedParser<com.siansiansu.taigikeyboard.engine.proto.ToneVariationsResult>(
                      DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      // SET_MEMOIZED_IS_INITIALIZED is never called for this message.
      // So it can do anything. Combine with default case for smaller codegen.
      case SET_MEMOIZED_IS_INITIALIZED:
    }
    // Should never happen. Generates tight code to throw an exception.
    throw null;
  }


  // @@protoc_insertion_point(class_scope:taigi.engine.ToneVariationsResult)
  private static final com.siansiansu.taigikeyboard.engine.proto.ToneVariationsResult DEFAULT_INSTANCE;
  static {
    ToneVariationsResult defaultInstance = new ToneVariationsResult();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
      ToneVariationsResult.class, defaultInstance);
  }

  public static com.siansiansu.taigikeyboard.engine.proto.ToneVariationsResult getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<ToneVariationsResult> PARSER;

  public static com.google.protobuf.Parser<ToneVariationsResult> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}
