// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: phonetics.proto
// Protobuf Java Version: 4.27.5

package com.siansiansu.taigikeyboard.engine.proto;

public interface TpsAdjustResultOrBuilder extends
    // @@protoc_insertion_point(interface_extends:taigi.engine.TpsAdjustResult)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>string adjusted = 1;</code>
   * @return The adjusted.
   */
  java.lang.String getAdjusted();
  /**
   * <code>string adjusted = 1;</code>
   * @return The bytes for adjusted.
   */
  com.google.protobuf.ByteString
      getAdjustedBytes();

  /**
   * <code>.taigi.engine.OptionalStringResult replace_last = 2;</code>
   * @return Whether the replaceLast field is set.
   */
  boolean hasReplaceLast();
  /**
   * <code>.taigi.engine.OptionalStringResult replace_last = 2;</code>
   * @return The replaceLast.
   */
  com.siansiansu.taigikeyboard.engine.proto.OptionalStringResult getReplaceLast();
}
