// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: case.proto
// Protobuf Java Version: 4.27.5

package com.siansiansu.taigikeyboard.engine.proto;

/**
 * <pre>
 * `TransformInputCase` applies the LetterCase to `text` per
 * `CaseTransformer.transformForInput` semantics:
 * - LOWERCASED: lowercase per `LowercaseToneChar`
 * - UPPERCASED: first letter upper (`UppercaseToneChar` on first), rest lower
 * - CAPS_LOCKED: full upper per `FullUppercaseToneString`
 * </pre>
 *
 * Protobuf type {@code taigi.engine.TransformInputCase}
 */
public  final class TransformInputCase extends
    com.google.protobuf.GeneratedMessageLite<
        TransformInputCase, TransformInputCase.Builder> implements
    // @@protoc_insertion_point(message_implements:taigi.engine.TransformInputCase)
    TransformInputCaseOrBuilder {
  private TransformInputCase() {
    text_ = "";
  }
  public static final int TEXT_FIELD_NUMBER = 1;
  private java.lang.String text_;
  /**
   * <code>string text = 1;</code>
   * @return The text.
   */
  @java.lang.Override
  public java.lang.String getText() {
    return text_;
  }
  /**
   * <code>string text = 1;</code>
   * @return The bytes for text.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getTextBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(text_);
  }
  /**
   * <code>string text = 1;</code>
   * @param value The text to set.
   */
  private void setText(
      java.lang.String value) {
    java.lang.Class<?> valueClass = value.getClass();

    text_ = value;
  }
  /**
   * <code>string text = 1;</code>
   */
  private void clearText() {

    text_ = getDefaultInstance().getText();
  }
  /**
   * <code>string text = 1;</code>
   * @param value The bytes for text to set.
   */
  private void setTextBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    text_ = value.toStringUtf8();

  }

  public static final int LETTER_CASE_FIELD_NUMBER = 2;
  private int letterCase_;
  /**
   * <code>.taigi.engine.LetterCase letter_case = 2;</code>
   * @return The enum numeric value on the wire for letterCase.
   */
  @java.lang.Override
  public int getLetterCaseValue() {
    return letterCase_;
  }
  /**
   * <code>.taigi.engine.LetterCase letter_case = 2;</code>
   * @return The letterCase.
   */
  @java.lang.Override
  public com.siansiansu.taigikeyboard.engine.proto.LetterCase getLetterCase() {
    com.siansiansu.taigikeyboard.engine.proto.LetterCase result = com.siansiansu.taigikeyboard.engine.proto.LetterCase.forNumber(letterCase_);
    return result == null ? com.siansiansu.taigikeyboard.engine.proto.LetterCase.UNRECOGNIZED : result;
  }
  /**
   * <code>.taigi.engine.LetterCase letter_case = 2;</code>
   * @param value The enum numeric value on the wire for letterCase to set.
   */
  private void setLetterCaseValue(int value) {
      letterCase_ = value;
  }
  /**
   * <code>.taigi.engine.LetterCase letter_case = 2;</code>
   * @param value The letterCase to set.
   */
  private void setLetterCase(com.siansiansu.taigikeyboard.engine.proto.LetterCase value) {
    letterCase_ = value.getNumber();

  }
  /**
   * <code>.taigi.engine.LetterCase letter_case = 2;</code>
   */
  private void clearLetterCase() {

    letterCase_ = 0;
  }

  public static com.siansiansu.taigikeyboard.engine.proto.TransformInputCase parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.siansiansu.taigikeyboard.engine.proto.TransformInputCase parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.siansiansu.taigikeyboard.engine.proto.TransformInputCase parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.siansiansu.taigikeyboard.engine.proto.TransformInputCase parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.siansiansu.taigikeyboard.engine.proto.TransformInputCase parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.siansiansu.taigikeyboard.engine.proto.TransformInputCase parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.siansiansu.taigikeyboard.engine.proto.TransformInputCase parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.siansiansu.taigikeyboard.engine.proto.TransformInputCase parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static com.siansiansu.taigikeyboard.engine.proto.TransformInputCase parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }

  public static com.siansiansu.taigikeyboard.engine.proto.TransformInputCase parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static com.siansiansu.taigikeyboard.engine.proto.TransformInputCase parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.siansiansu.taigikeyboard.engine.proto.TransformInputCase parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }
  public static Builder newBuilder(com.siansiansu.taigikeyboard.engine.proto.TransformInputCase prototype) {
    return DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * <pre>
   * `TransformInputCase` applies the LetterCase to `text` per
   * `CaseTransformer.transformForInput` semantics:
   * - LOWERCASED: lowercase per `LowercaseToneChar`
   * - UPPERCASED: first letter upper (`UppercaseToneChar` on first), rest lower
   * - CAPS_LOCKED: full upper per `FullUppercaseToneString`
   * </pre>
   *
   * Protobuf type {@code taigi.engine.TransformInputCase}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        com.siansiansu.taigikeyboard.engine.proto.TransformInputCase, Builder> implements
      // @@protoc_insertion_point(builder_implements:taigi.engine.TransformInputCase)
      com.siansiansu.taigikeyboard.engine.proto.TransformInputCaseOrBuilder {
    // Construct using com.siansiansu.taigikeyboard.engine.proto.TransformInputCase.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <code>string text = 1;</code>
     * @return The text.
     */
    @java.lang.Override
    public java.lang.String getText() {
      return instance.getText();
    }
    /**
     * <code>string text = 1;</code>
     * @return The bytes for text.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getTextBytes() {
      return instance.getTextBytes();
    }
    /**
     * <code>string text = 1;</code>
     * @param value The text to set.
     * @return This builder for chaining.
     */
    public Builder setText(
        java.lang.String value) {
      copyOnWrite();
      instance.setText(value);
      return this;
    }
    /**
     * <code>string text = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearText() {
      copyOnWrite();
      instance.clearText();
      return this;
    }
    /**
     * <code>string text = 1;</code>
     * @param value The bytes for text to set.
     * @return This builder for chaining.
     */
    public Builder setTextBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setTextBytes(value);
      return this;
    }

    /**
     * <code>.taigi.engine.LetterCase letter_case = 2;</code>
     * @return The enum numeric value on the wire for letterCase.
     */
    @java.lang.Override
    public int getLetterCaseValue() {
      return instance.getLetterCaseValue();
    }
    /**
     * <code>.taigi.engine.LetterCase letter_case = 2;</code>
     * @param value The letterCase to set.
     * @return This builder for chaining.
     */
    public Builder setLetterCaseValue(int value) {
      copyOnWrite();
      instance.setLetterCaseValue(value);
      return this;
    }
    /**
     * <code>.taigi.engine.LetterCase letter_case = 2;</code>
     * @return The letterCase.
     */
    @java.lang.Override
    public com.siansiansu.taigikeyboard.engine.proto.LetterCase getLetterCase() {
      return instance.getLetterCase();
    }
    /**
     * <code>.taigi.engine.LetterCase letter_case = 2;</code>
     * @param value The enum numeric value on the wire for letterCase to set.
     * @return This builder for chaining.
     */
    public Builder setLetterCase(com.siansiansu.taigikeyboard.engine.proto.LetterCase value) {
      copyOnWrite();
      instance.setLetterCase(value);
      return this;
    }
    /**
     * <code>.taigi.engine.LetterCase letter_case = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearLetterCase() {
      copyOnWrite();
      instance.clearLetterCase();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:taigi.engine.TransformInputCase)
  }
  @java.lang.Override
  @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
  protected final java.lang.Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      java.lang.Object arg0, java.lang.Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new com.siansiansu.taigikeyboard.engine.proto.TransformInputCase();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
          java.lang.Object[] objects = new java.lang.Object[] {
            "text_",
            "letterCase_",
          };
          java.lang.String info =
              "\u0000\u0002\u0000\u0000\u0001\u0002\u0002\u0000\u0000\u0000\u0001\u0208\u0002\f" +
              "";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      // fall through
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<com.siansiansu.taigikeyboard.engine.proto.TransformInputCase> parser = PARSER;
        if (parser == null) {
          synchronized (com.siansiansu.taigikeyboard.engine.proto.TransformInputCase.class) {
            parser = PARSER;
            if (parser == null) {
              parser =
                  new DefaultInstanceBasedParser<com.siansiansu.taigikeyboard.engine.proto.TransformInputCase>(
                      DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
    }
    case GET_MEMOIZED_IS_INITIALIZED: {
      return (byte) 1;
    }
    case SET_MEMOIZED_IS_INITIALIZED: {
      return null;
    }
    }
    throw new UnsupportedOperationException();
  }


  // @@protoc_insertion_point(class_scope:taigi.engine.TransformInputCase)
  private static final com.siansiansu.taigikeyboard.engine.proto.TransformInputCase DEFAULT_INSTANCE;
  static {
    TransformInputCase defaultInstance = new TransformInputCase();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
      TransformInputCase.class, defaultInstance);
  }

  public static com.siansiansu.taigikeyboard.engine.proto.TransformInputCase getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<TransformInputCase> PARSER;

  public static com.google.protobuf.Parser<TransformInputCase> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}
