// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: user_data.proto
// Protobuf Java Version: 4.36.2

package com.siansiansu.taigikeyboard.engine.proto;

/**
 * <pre>
 * Rows removed per store (0 for a store not selected, or one that failed).
 * Every selected store is attempted: one that cannot be emptied is no
 * reason to leave the others full.
 * </pre>
 *
 * Protobuf type {@code taigi.engine.UserDataReset}
 */
@com.google.protobuf.Generated
public  final class UserDataReset extends
    com.google.protobuf.GeneratedMessageLite<
        UserDataReset, UserDataReset.Builder> implements
    // @@protoc_insertion_point(message_implements:taigi.engine.UserDataReset)
    UserDataResetOrBuilder {
  private UserDataReset() {
    failures_ = emptyProtobufList();
  }
  public static final int FREQUENCY_REMOVED_FIELD_NUMBER = 1;
  private long frequencyRemoved_;
  /**
   * <code>int64 frequency_removed = 1;</code>
   * @return The frequencyRemoved.
   */
  @java.lang.Override
  public long getFrequencyRemoved() {
    return frequencyRemoved_;
  }
  /**
   * <code>int64 frequency_removed = 1;</code>
   * @param value The frequencyRemoved to set.
   */
  private void setFrequencyRemoved(long value) {

    frequencyRemoved_ = value;
  }
  /**
   * <code>int64 frequency_removed = 1;</code>
   */
  private void clearFrequencyRemoved() {

    frequencyRemoved_ = 0L;
  }

  public static final int ASSOCIATION_REMOVED_FIELD_NUMBER = 2;
  private long associationRemoved_;
  /**
   * <code>int64 association_removed = 2;</code>
   * @return The associationRemoved.
   */
  @java.lang.Override
  public long getAssociationRemoved() {
    return associationRemoved_;
  }
  /**
   * <code>int64 association_removed = 2;</code>
   * @param value The associationRemoved to set.
   */
  private void setAssociationRemoved(long value) {

    associationRemoved_ = value;
  }
  /**
   * <code>int64 association_removed = 2;</code>
   */
  private void clearAssociationRemoved() {

    associationRemoved_ = 0L;
  }

  public static final int CUSTOM_DICTIONARY_REMOVED_FIELD_NUMBER = 3;
  private long customDictionaryRemoved_;
  /**
   * <code>int64 custom_dictionary_removed = 3;</code>
   * @return The customDictionaryRemoved.
   */
  @java.lang.Override
  public long getCustomDictionaryRemoved() {
    return customDictionaryRemoved_;
  }
  /**
   * <code>int64 custom_dictionary_removed = 3;</code>
   * @param value The customDictionaryRemoved to set.
   */
  private void setCustomDictionaryRemoved(long value) {

    customDictionaryRemoved_ = value;
  }
  /**
   * <code>int64 custom_dictionary_removed = 3;</code>
   */
  private void clearCustomDictionaryRemoved() {

    customDictionaryRemoved_ = 0L;
  }

  public static final int LEARNED_PHRASES_REMOVED_FIELD_NUMBER = 4;
  private long learnedPhrasesRemoved_;
  /**
   * <code>int64 learned_phrases_removed = 4;</code>
   * @return The learnedPhrasesRemoved.
   */
  @java.lang.Override
  public long getLearnedPhrasesRemoved() {
    return learnedPhrasesRemoved_;
  }
  /**
   * <code>int64 learned_phrases_removed = 4;</code>
   * @param value The learnedPhrasesRemoved to set.
   */
  private void setLearnedPhrasesRemoved(long value) {

    learnedPhrasesRemoved_ = value;
  }
  /**
   * <code>int64 learned_phrases_removed = 4;</code>
   */
  private void clearLearnedPhrasesRemoved() {

    learnedPhrasesRemoved_ = 0L;
  }

  public static final int FAILURES_FIELD_NUMBER = 5;
  private com.google.protobuf.Internal.ProtobufList<java.lang.String> failures_;
  /**
   * <pre>
   * One line per selected store that could not be emptied, naming its file
   * (`user_frequency: &lt;error&gt;`) — English, for a diagnostic. Empty when
   * every selected store was emptied.
   * </pre>
   *
   * <code>repeated string failures = 5;</code>
   * @return A list containing the failures.
   */
  @java.lang.Override
  public java.util.List<java.lang.String> getFailuresList() {
    return failures_;
  }
  /**
   * <pre>
   * One line per selected store that could not be emptied, naming its file
   * (`user_frequency: &lt;error&gt;`) — English, for a diagnostic. Empty when
   * every selected store was emptied.
   * </pre>
   *
   * <code>repeated string failures = 5;</code>
   * @return The count of failures.
   */
  @java.lang.Override
  public int getFailuresCount() {
    return failures_.size();
  }
  /**
   * <pre>
   * One line per selected store that could not be emptied, naming its file
   * (`user_frequency: &lt;error&gt;`) — English, for a diagnostic. Empty when
   * every selected store was emptied.
   * </pre>
   *
   * <code>repeated string failures = 5;</code>
   * @param index The index of the element to return.
   * @return The failures at the given index.
   */
  @java.lang.Override
  public java.lang.String getFailures(int index) {
    return failures_.get(index);
  }
  /**
   * <pre>
   * One line per selected store that could not be emptied, naming its file
   * (`user_frequency: &lt;error&gt;`) — English, for a diagnostic. Empty when
   * every selected store was emptied.
   * </pre>
   *
   * <code>repeated string failures = 5;</code>
   * @param index The index of the value to return.
   * @return The bytes of the failures at the given index.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getFailuresBytes(int index) {
    return com.google.protobuf.ByteString.copyFromUtf8(
        failures_.get(index));
  }
  private void ensureFailuresIsMutable() {
    com.google.protobuf.Internal.ProtobufList<java.lang.String> tmp =
        failures_;  if (!tmp.isModifiable()) {
      failures_ =
          com.google.protobuf.GeneratedMessageLite.mutableCopy(tmp);
     }
  }
  /**
   * <pre>
   * One line per selected store that could not be emptied, naming its file
   * (`user_frequency: &lt;error&gt;`) — English, for a diagnostic. Empty when
   * every selected store was emptied.
   * </pre>
   *
   * <code>repeated string failures = 5;</code>
   * @param index The index to set the value at.
   * @param value The failures to set.
   */
  private void setFailures(
      int index, java.lang.String value) {
    java.util.Objects.requireNonNull(value);
    ensureFailuresIsMutable();
    failures_.set(index, value);
  }
  /**
   * <pre>
   * One line per selected store that could not be emptied, naming its file
   * (`user_frequency: &lt;error&gt;`) — English, for a diagnostic. Empty when
   * every selected store was emptied.
   * </pre>
   *
   * <code>repeated string failures = 5;</code>
   * @param value The failures to add.
   */
  private void addFailures(
      java.lang.String value) {
    java.util.Objects.requireNonNull(value);
    ensureFailuresIsMutable();
    failures_.add(value);
  }
  /**
   * <pre>
   * One line per selected store that could not be emptied, naming its file
   * (`user_frequency: &lt;error&gt;`) — English, for a diagnostic. Empty when
   * every selected store was emptied.
   * </pre>
   *
   * <code>repeated string failures = 5;</code>
   * @param values The failures to add.
   */
  private void addAllFailures(
      java.lang.Iterable<java.lang.String> values) {
    ensureFailuresIsMutable();
    com.google.protobuf.AbstractMessageLite.addAll(
        values, failures_);
  }
  /**
   * <pre>
   * One line per selected store that could not be emptied, naming its file
   * (`user_frequency: &lt;error&gt;`) — English, for a diagnostic. Empty when
   * every selected store was emptied.
   * </pre>
   *
   * <code>repeated string failures = 5;</code>
   */
  private void clearFailures() {
    failures_ = emptyProtobufList();
  }
  /**
   * <pre>
   * One line per selected store that could not be emptied, naming its file
   * (`user_frequency: &lt;error&gt;`) — English, for a diagnostic. Empty when
   * every selected store was emptied.
   * </pre>
   *
   * <code>repeated string failures = 5;</code>
   * @param value The bytes of the failures to add.
   */
  private void addFailuresBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    ensureFailuresIsMutable();
    failures_.add(value.toStringUtf8());
  }

  public static com.siansiansu.taigikeyboard.engine.proto.UserDataReset parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.siansiansu.taigikeyboard.engine.proto.UserDataReset parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.siansiansu.taigikeyboard.engine.proto.UserDataReset parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.siansiansu.taigikeyboard.engine.proto.UserDataReset parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.siansiansu.taigikeyboard.engine.proto.UserDataReset parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.siansiansu.taigikeyboard.engine.proto.UserDataReset parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.siansiansu.taigikeyboard.engine.proto.UserDataReset parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.siansiansu.taigikeyboard.engine.proto.UserDataReset parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static com.siansiansu.taigikeyboard.engine.proto.UserDataReset parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }

  public static com.siansiansu.taigikeyboard.engine.proto.UserDataReset parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static com.siansiansu.taigikeyboard.engine.proto.UserDataReset parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.siansiansu.taigikeyboard.engine.proto.UserDataReset parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }
  public static Builder newBuilder(com.siansiansu.taigikeyboard.engine.proto.UserDataReset prototype) {
    return DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * <pre>
   * Rows removed per store (0 for a store not selected, or one that failed).
   * Every selected store is attempted: one that cannot be emptied is no
   * reason to leave the others full.
   * </pre>
   *
   * Protobuf type {@code taigi.engine.UserDataReset}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        com.siansiansu.taigikeyboard.engine.proto.UserDataReset, Builder> implements
      // @@protoc_insertion_point(builder_implements:taigi.engine.UserDataReset)
      com.siansiansu.taigikeyboard.engine.proto.UserDataResetOrBuilder {
    // Construct using com.siansiansu.taigikeyboard.engine.proto.UserDataReset.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <code>int64 frequency_removed = 1;</code>
     * @return The frequencyRemoved.
     */
    @java.lang.Override
    public long getFrequencyRemoved() {
      return instance.getFrequencyRemoved();
    }
    /**
     * <code>int64 frequency_removed = 1;</code>
     * @param value The frequencyRemoved to set.
     * @return This builder for chaining.
     */
    public Builder setFrequencyRemoved(long value) {
      copyOnWrite();
      instance.setFrequencyRemoved(value);
      return this;
    }
    /**
     * <code>int64 frequency_removed = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearFrequencyRemoved() {
      copyOnWrite();
      instance.clearFrequencyRemoved();
      return this;
    }

    /**
     * <code>int64 association_removed = 2;</code>
     * @return The associationRemoved.
     */
    @java.lang.Override
    public long getAssociationRemoved() {
      return instance.getAssociationRemoved();
    }
    /**
     * <code>int64 association_removed = 2;</code>
     * @param value The associationRemoved to set.
     * @return This builder for chaining.
     */
    public Builder setAssociationRemoved(long value) {
      copyOnWrite();
      instance.setAssociationRemoved(value);
      return this;
    }
    /**
     * <code>int64 association_removed = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearAssociationRemoved() {
      copyOnWrite();
      instance.clearAssociationRemoved();
      return this;
    }

    /**
     * <code>int64 custom_dictionary_removed = 3;</code>
     * @return The customDictionaryRemoved.
     */
    @java.lang.Override
    public long getCustomDictionaryRemoved() {
      return instance.getCustomDictionaryRemoved();
    }
    /**
     * <code>int64 custom_dictionary_removed = 3;</code>
     * @param value The customDictionaryRemoved to set.
     * @return This builder for chaining.
     */
    public Builder setCustomDictionaryRemoved(long value) {
      copyOnWrite();
      instance.setCustomDictionaryRemoved(value);
      return this;
    }
    /**
     * <code>int64 custom_dictionary_removed = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearCustomDictionaryRemoved() {
      copyOnWrite();
      instance.clearCustomDictionaryRemoved();
      return this;
    }

    /**
     * <code>int64 learned_phrases_removed = 4;</code>
     * @return The learnedPhrasesRemoved.
     */
    @java.lang.Override
    public long getLearnedPhrasesRemoved() {
      return instance.getLearnedPhrasesRemoved();
    }
    /**
     * <code>int64 learned_phrases_removed = 4;</code>
     * @param value The learnedPhrasesRemoved to set.
     * @return This builder for chaining.
     */
    public Builder setLearnedPhrasesRemoved(long value) {
      copyOnWrite();
      instance.setLearnedPhrasesRemoved(value);
      return this;
    }
    /**
     * <code>int64 learned_phrases_removed = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearLearnedPhrasesRemoved() {
      copyOnWrite();
      instance.clearLearnedPhrasesRemoved();
      return this;
    }

    /**
     * <pre>
     * One line per selected store that could not be emptied, naming its file
     * (`user_frequency: &lt;error&gt;`) — English, for a diagnostic. Empty when
     * every selected store was emptied.
     * </pre>
     *
     * <code>repeated string failures = 5;</code>
     * @return A list containing the failures.
     */
    @java.lang.Override
    public java.util.List<java.lang.String>
        getFailuresList() {
      return java.util.Collections.unmodifiableList(
          instance.getFailuresList());
    }
    /**
     * <pre>
     * One line per selected store that could not be emptied, naming its file
     * (`user_frequency: &lt;error&gt;`) — English, for a diagnostic. Empty when
     * every selected store was emptied.
     * </pre>
     *
     * <code>repeated string failures = 5;</code>
     * @return The count of failures.
     */
    @java.lang.Override
    public int getFailuresCount() {
      return instance.getFailuresCount();
    }
    /**
     * <pre>
     * One line per selected store that could not be emptied, naming its file
     * (`user_frequency: &lt;error&gt;`) — English, for a diagnostic. Empty when
     * every selected store was emptied.
     * </pre>
     *
     * <code>repeated string failures = 5;</code>
     * @param index The index of the element to return.
     * @return The failures at the given index.
     */
    @java.lang.Override
    public java.lang.String getFailures(int index) {
      return instance.getFailures(index);
    }
    /**
     * <pre>
     * One line per selected store that could not be emptied, naming its file
     * (`user_frequency: &lt;error&gt;`) — English, for a diagnostic. Empty when
     * every selected store was emptied.
     * </pre>
     *
     * <code>repeated string failures = 5;</code>
     * @param index The index of the value to return.
     * @return The bytes of the failures at the given index.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getFailuresBytes(int index) {
      return instance.getFailuresBytes(index);
    }
    /**
     * <pre>
     * One line per selected store that could not be emptied, naming its file
     * (`user_frequency: &lt;error&gt;`) — English, for a diagnostic. Empty when
     * every selected store was emptied.
     * </pre>
     *
     * <code>repeated string failures = 5;</code>
     * @param index The index to set the value at.
     * @param value The failures to set.
     * @return This builder for chaining.
     */
    public Builder setFailures(
        int index, java.lang.String value) {
      copyOnWrite();
      instance.setFailures(index, value);
      return this;
    }
    /**
     * <pre>
     * One line per selected store that could not be emptied, naming its file
     * (`user_frequency: &lt;error&gt;`) — English, for a diagnostic. Empty when
     * every selected store was emptied.
     * </pre>
     *
     * <code>repeated string failures = 5;</code>
     * @param value The failures to add.
     * @return This builder for chaining.
     */
    public Builder addFailures(
        java.lang.String value) {
      copyOnWrite();
      instance.addFailures(value);
      return this;
    }
    /**
     * <pre>
     * One line per selected store that could not be emptied, naming its file
     * (`user_frequency: &lt;error&gt;`) — English, for a diagnostic. Empty when
     * every selected store was emptied.
     * </pre>
     *
     * <code>repeated string failures = 5;</code>
     * @param values The failures to add.
     * @return This builder for chaining.
     */
    public Builder addAllFailures(
        java.lang.Iterable<java.lang.String> values) {
      copyOnWrite();
      instance.addAllFailures(values);
      return this;
    }
    /**
     * <pre>
     * One line per selected store that could not be emptied, naming its file
     * (`user_frequency: &lt;error&gt;`) — English, for a diagnostic. Empty when
     * every selected store was emptied.
     * </pre>
     *
     * <code>repeated string failures = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearFailures() {
      copyOnWrite();
      instance.clearFailures();
      return this;
    }
    /**
     * <pre>
     * One line per selected store that could not be emptied, naming its file
     * (`user_frequency: &lt;error&gt;`) — English, for a diagnostic. Empty when
     * every selected store was emptied.
     * </pre>
     *
     * <code>repeated string failures = 5;</code>
     * @param value The bytes of the failures to add.
     * @return This builder for chaining.
     */
    public Builder addFailuresBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.addFailuresBytes(value);
      return this;
    }

    // @@protoc_insertion_point(builder_scope:taigi.engine.UserDataReset)
  }
  @java.lang.Override
  @java.lang.SuppressWarnings({"ThrowNull"})
  protected final java.lang.Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      java.lang.Object arg0, java.lang.Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new com.siansiansu.taigikeyboard.engine.proto.UserDataReset();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
          java.lang.Object[] objects = new java.lang.Object[] {
            "frequencyRemoved_",
            "associationRemoved_",
            "customDictionaryRemoved_",
            "learnedPhrasesRemoved_",
            "failures_",
          };
          java.lang.String info =
              "\u0000\u0005\u0000\u0000\u0001\u0005\u0005\u0000\u0001\u0000\u0001\u0002\u0002\u0002" +
              "\u0003\u0002\u0004\u0002\u0005\u021a";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<com.siansiansu.taigikeyboard.engine.proto.UserDataReset> parser = PARSER;
        if (parser == null) {
          synchronized (com.siansiansu.taigikeyboard.engine.proto.UserDataReset.class) {
            parser = PARSER;
            if (parser == null) {
              parser =
                  new DefaultInstanceBasedParser<com.siansiansu.taigikeyboard.engine.proto.UserDataReset>(
                      DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      // SET_MEMOIZED_IS_INITIALIZED is never called for this message.
      // So it can do anything. Combine with default case for smaller codegen.
      case SET_MEMOIZED_IS_INITIALIZED:
    }
    // Should never happen. Generates tight code to throw an exception.
    throw null;
  }


  // @@protoc_insertion_point(class_scope:taigi.engine.UserDataReset)
  private static final com.siansiansu.taigikeyboard.engine.proto.UserDataReset DEFAULT_INSTANCE;
  static {
    UserDataReset defaultInstance = new UserDataReset();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
      UserDataReset.class, defaultInstance);
  }

  public static com.siansiansu.taigikeyboard.engine.proto.UserDataReset getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<UserDataReset> PARSER;

  public static com.google.protobuf.Parser<UserDataReset> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}
