// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: user_data.proto
// Protobuf Java Version: 4.36.2

package com.siansiansu.taigikeyboard.engine.proto;

@com.google.protobuf.Generated
public interface UserDataResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:taigi.engine.UserDataResponse)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>.taigi.engine.UserDataOpened opened = 1;</code>
   * @return Whether the opened field is set.
   */
  boolean hasOpened();
  /**
   * <code>.taigi.engine.UserDataOpened opened = 1;</code>
   * @return The opened.
   */
  com.siansiansu.taigikeyboard.engine.proto.UserDataOpened getOpened();

  /**
   * <code>.taigi.engine.UserDataReset reset = 2;</code>
   * @return Whether the reset field is set.
   */
  boolean hasReset();
  /**
   * <code>.taigi.engine.UserDataReset reset = 2;</code>
   * @return The reset.
   */
  com.siansiansu.taigikeyboard.engine.proto.UserDataReset getReset();

  public com.siansiansu.taigikeyboard.engine.proto.UserDataResponse.ResultCase getResultCase();
}
