// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: nextword.proto
// Protobuf Java Version: 4.35.1

package com.siansiansu.taigikeyboard.engine.proto;

@com.google.protobuf.Generated
public interface WordSelectedOrBuilder extends
    // @@protoc_insertion_point(interface_extends:taigi.engine.WordSelected)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>string text = 1;</code>
   * @return The text.
   */
  java.lang.String getText();
  /**
   * <code>string text = 1;</code>
   * @return The bytes for text.
   */
  com.google.protobuf.ByteString
      getTextBytes();

  /**
   * <code>string roman = 2;</code>
   * @return The roman.
   */
  java.lang.String getRoman();
  /**
   * <code>string roman = 2;</code>
   * @return The bytes for roman.
   */
  com.google.protobuf.ByteString
      getRomanBytes();

  /**
   * <code>bool require_roman_mode = 3;</code>
   * @return The requireRomanMode.
   */
  boolean getRequireRomanMode();

  /**
   * <code>bool trigger_prediction = 4;</code>
   * @return The triggerPrediction.
   */
  boolean getTriggerPrediction();

  /**
   * <code>.taigi.engine.DecisionInput input = 5;</code>
   * @return Whether the input field is set.
   */
  boolean hasInput();
  /**
   * <code>.taigi.engine.DecisionInput input = 5;</code>
   * @return The input.
   */
  com.siansiansu.taigikeyboard.engine.proto.DecisionInput getInput();
}
