// swift-tools-version: 6.0

// SwiftPM manifest for the macOS InputMethodKit IME. There is deliberately no
// Xcode project (`.pbxproj` is user-only in this repo); `scripts/bundle-app.sh`
// assembles the `.app` from the executable this package builds.

import PackageDescription

let package = Package(
    name: "TaigiInputMethod",
    platforms: [.macOS(.v14)],
    products: [
        .executable(name: "TaigiInputMethod", targets: ["TaigiInputMethod"]),
    ],
    dependencies: [
        .package(url: "https://github.com/apple/swift-protobuf.git", from: "1.28.0"),
        // Exact pin: the USER-approved first non-Apple dependency stays
        // byte-reproducible. Its 3.x manifest is swift-tools 6.2, so resolving
        // this package now needs a Swift 6.2+ toolchain even though our own
        // manifest says 6.0.
        .package(url: "https://github.com/sindresorhus/KeyboardShortcuts.git", exact: "3.0.1"),
    ],
    targets: [
        // Prebuilt Rust shared core (`engine/swift-ffi`), regenerated by
        // `engine/scripts/build-macos-xcframework.sh`. Single `macos-arm64` slice.
        .binaryTarget(
            name: "RustTaigi",
            path: "RustEngine/RustTaigi.xcframework",
        ),

        // swift-bridge wrappers around the binary target. Swift 5 language
        // mode because two of its three files are generated and cannot be
        // annotated for strict concurrency; see RustEngine/README.md for why
        // the third one lives there too.
        .target(
            name: "RustTaigiSwift",
            dependencies: ["RustTaigi"],
            path: "RustEngine",
            exclude: ["RustTaigi.xcframework", "README.md"],
            swiftSettings: [.swiftLanguageMode(.v5)],
        ),

        // Everything except the process entry point, so tests can import it.
        .target(
            name: "TaigiInputMethodCore",
            dependencies: [
                "RustTaigiSwift",
                .product(name: "SwiftProtobuf", package: "swift-protobuf"),
                .product(name: "KeyboardShortcuts", package: "KeyboardShortcuts"),
            ],
        ),

        // Thin shell so `TaigiInputMethodCore` stays importable by tests.
        .executableTarget(
            name: "TaigiInputMethod",
            dependencies: ["TaigiInputMethodCore"],
        ),

        .testTarget(
            name: "TaigiInputMethodCoreTests",
            dependencies: ["TaigiInputMethodCore"],
        ),
    ],
)
