import XCTest
@testable import TaigiKeyboard

/// InputNormalizer 測試
/// 自動產生自 dictionary.csv（600 筆測試案例）
final class InputNormalizerTests: XCTestCase {

    // MARK: - Test Data

    /// tl（帶調符）-> tl_num
    private let tlCases: [(input: String, expected: String)] = [
            ("khan-gû-hue", "khan1gu5hue1"),
            ("mī-thai", "mi7thai1"),
            ("pian-ji̍p", "pian1jip8"),
            ("bí-king", "bi2king1"),
            ("lián-tsînn", "lian2tsinn5"),
            ("tông-gân", "tong5gan5"),
            ("lī-káu-ê-hng", "li7kau2e5hng1"),
            ("kûn-bah", "kun5bah4"),
            ("phah-kha-tshng-phé", "phah4kha1tshng1phe2"),
            ("tī-sè", "ti7se3"),
            ("lîm-tsùn-kia̍t", "lim5tsun3kiat8"),
            ("khàng-suann-piah", "khang3suann1piah4"),
            ("to-á", "to1a2"),
            ("ko-nóo", "ko1noo2"),
            ("kong-bûn-su", "kong1bun5su1"),
            ("pîng-pōo-tshenn-hûn", "ping5poo7tshenn1hun5"),
            ("kūn-tsuí", "kun7tsui2"),
            ("tiâu-tio̍h", "tiau5tioh8"),
            ("huán-kuan", "huan2kuan1"),
            ("tsàu-pńg", "tsau3png2"),
            ("tsām-tso̍h", "tsam7tsoh8"),
            ("tsiânn-lia̍p-tsí", "tsiann5liap8tsi2"),
            ("khuà-tshián", "khua3tshian2"),
            ("ngôo-lô-kok", "ngoo5lo5kok4"),
            ("lâng-tha̍h-lâng", "lang5thah8lang5"),
            ("sió-lâm-mn̂g", "sio2lam5mng5"),
            ("tsia̍h-báu-miâ", "tsiah8bau2mia5"),
            ("ha̍k-kài", "hak8kai3"),
            ("hong-suí-thâu", "hong1sui2thau5"),
            ("hn̄g-hn̄g", "hng7hng7"),
            ("jip-kàu", "jip4kau3"),
            ("gî-sim-tāng", "gi5sim1tang7"),
            ("kî-û", "ki5u5"),
            ("kim-pńg", "kim1png2"),
            ("si̍t-bu̍t-jîn", "sit8but8jin5"),
            ("thua-thìng", "thua1thing3"),
            ("hîng-khòo", "hing5khoo3"),
            ("tíng-á-gî", "ting2a2gi5"),
            ("siā-huē", "sia7hue7"),
            ("hó-pí", "ho2pi2"),
            ("hue-tsíng-kah", "hue1tsing2kah4"),
            ("bân-lâm-gú", "ban5lam5gu2"),
            ("ho̍k-tsit", "hok8tsit4"),
            ("bīn-tíng-pah", "bin7ting2pah4"),
            ("ga̍k-guân-suè", "gak8guan5sue3"),
            ("gua̍t", "guat8"),
            ("phing-huāi", "phing1huai7"),
            ("gû-iâ", "gu5ia5"),
            ("liông-gân", "liong5gan5"),
            ("ti̍t-kak-thiāu", "tit8kak4thiau7"),
            ("ha̍h-pî", "hah8pi5"),
            ("io̍h-tíng", "ioh8ting2"),
            ("liû-lōng", "liu5long7"),
            ("kha-khàu", "kha1khau3"),
            ("hù-sū-suann", "hu3su7suann1"),
            ("tuì-khui", "tui3khui1"),
            ("thāng", "thang7"),
            ("phang-tshí", "phang1tshi2"),
            ("tsing-kuân", "tsing1kuan5"),
            ("lân-hue-bí", "lan5hue1bi2"),
            ("tsi̍t-tah-kú-á", "tsit8tah4ku2a2"),
            ("tn̂g--lâi", "tng5lai5"),
            ("tap-ho̍k", "tap4hok8"),
            ("mî-tshn̂g", "mi5tshng5"),
            ("tshenn-kâu-hōo", "tshenn1kau5hoo7"),
            ("sann-giân-nn̄g-gú", "sann1gian5nng7gu2"),
            ("tsiūnn-bé-hân", "tsiunn7be2han5"),
            ("tio̍h-lâng-un", "tioh8lang5un1"),
            ("sàn-huē", "san3hue7"),
            ("iû-kià-suán-phiò", "iu5kia3suan2phio3"),
            ("koo-tâ", "koo1ta5"),
            ("ua̍h-pán-tiàm", "uah8pan2tiam3"),
            ("kuan-tshat-li̍k", "kuan1tshat4lik8"),
            ("khah-tán", "khah4tan2"),
            ("thau-tshìn-thâu", "thau1tshin3thau5"),
            ("pha-lián-táu", "pha1lian2tau2"),
            ("tiû-á-thai", "tiu5a2thai1"),
            ("kiō-tsîng-ióng", "kio7tsing5iong2"),
            ("sîn", "sin5"),
            ("sàng-kàu", "sang3kau3"),
            ("niōo", "nioo7"),
            ("ke-lîm", "ke1lim5"),
            ("su-liām", "su1liam7"),
            ("sì-kak-toh-á", "si3kak4toh4a2"),
            ("tuǎ-tiânn", "tua6tiann5"),
            ("bô-hio̍h-tîn", "bo5hioh8tin5"),
            ("khai-tō", "khai1to7"),
            ("hān-tiān", "han7tian7"),
            ("tāi-tsia̍t", "tai7tsiat8"),
            ("kiat-liām", "kiat4liam7"),
            ("ki-ki-kiò", "ki1ki1kio3"),
            ("khàu-iau", "khau3iau1"),
            ("tsiong-kî-bé", "tsiong1ki5be2"),
            ("puânn--kè", "puann5ke3"),
            ("lia̍t-lia̍t", "liat8liat8"),
            ("liāng-sióng", "liang7siong2"),
            ("ū-tshuì-kóng-pa̍t-lâng", "u7tshui3kong2pat8lang5"),
            ("tuā-sòo-kì", "tua7soo3ki3"),
            ("pîng-tiānn", "ping5tiann7"),
            ("kòng-khang", "kong3khang1"),
            ("tuā-khu-hn̂g", "tua7khu1hng5"),
            ("tuā-tsiah-iá-lông", "tua7tsiah4ia2long5"),
            ("tshù-tiān", "tshu3tian7"),
            ("kap-tiâu", "kap4tiau5"),
            ("kāu-ko", "kau7ko1"),
            ("hoo-khip-hē-thóng", "hoo1khip4he7thong2"),
            ("thâu-ba̍k-tsai-kiā", "thau5bak8tsai1kia7"),
            ("pua̍t-tî", "puat8ti5"),
            ("ti-pak-lāi", "ti1pak4lai7"),
            ("tsháu-ê-pán", "tshau2e5pan2"),
            ("kuì-báu", "kui3bau2"),
            ("i̍k-sing-tsip-tsiàu", "ik8sing1tsip4tsiau3"),
            ("seré", "sere2"),
            ("guā-tiânn", "gua7tiann5"),
            ("tshàu-hué-ta", "tshau3hue2ta1"),
            ("tshòr-bí", "tshor3bi2"),
            ("teh-tiānn", "teh4tiann7"),
            ("thâu-pái", "thau5pai2"),
            ("siōng-tíng-siōng", "siong7ting2siong7"),
            ("ua̍h-jī-tháng-á", "uah8ji7thang2a2"),
            ("si̍t-bîn-thóng-tī", "sit8bin5thong2ti7"),
            ("bô-giân-bô-gú", "bo5gian5bo5gu2"),
            ("kòo-tan-jī-ha̍k", "koo3tan1ji7hak8"),
            ("tsip-bê-put-ngōo", "tsip4be5put4ngoo7"),
            ("tshû-tshû", "tshu5tshu5"),
            ("kái-má", "kai2ma2"),
            ("bāng-pán-ìn-suat", "bang7pan2in3suat4"),
            ("hi-nóo-khì", "hi1noo2khi3"),
            ("tuê-khòo", "tue5khoo3"),
            ("si-tsú", "si1tsu2"),
            ("tâm-hī", "tam5hi7"),
            ("sio-kīng-kha", "sio1king7kha1"),
            ("kiap-tik-thô", "kiap4tik4tho5"),
            ("înn-peh", "inn5peh4"),
            ("to̍k-phín", "tok8phin2"),
            ("too-huē", "too1hue7"),
            ("giú--khí-lâi", "giu2khi2lai5"),
            ("tiánn-te-phok", "tiann2te1phok4"),
            ("sè-tsîng", "se3tsing5"),
            ("siū-siōng", "siu7siong7"),
            ("íng-ū", "ing2u7"),
            ("bû-bîng-sī", "bu5bing5si7"),
            ("pue-oo-hóo", "pue1oo1hoo2"),
            ("tsi̍t-khoo-uî", "tsit8khoo1ui5"),
            ("biān-lîm", "bian7lim5"),
            ("nn̄g-tǹg-āu", "nng7tng3au7"),
            ("tshū-tiong-iânn", "tshu7tiong1iann5"),
            ("tshiúnn-tshiúnn-tshuah-tshuah", "tshiunn2tshiunn2tshuah4tshuah4"),
            ("tsiàm", "tsiam3"),
            ("kim-gûn", "kim1gun5"),
            ("hang-hōo-si̍k", "hang1hoo7sik8"),
            ("tsuî", "tsui5"),
            ("hî-láng-á", "hi5lang2a2"),
            ("buán-puè", "buan2pue3"),
            ("sū-lí", "su7li2"),
            ("tshâ-thâu-lâng", "tsha5thau5lang5"),
            ("tsú-nuā", "tsu2nua7"),
            ("tâi-gír-lô-má-lī", "tai5gir2lo5ma2li7"),
            ("sio̍k-sik", "siok8sik4"),
            ("jîn-li̍k", "jin5lik8"),
            ("tsûn-á", "tsun5a2"),
            ("tha̍k-liáu", "thak8liau2"),
            ("ba̍k-kháng-hî", "bak8khang2hi5"),
            ("tsuè-āu", "tsue3au7"),
            ("lí-huat-sió-tsiá", "li2huat4sio2tsia2"),
            ("môo-ki", "moo5ki1"),
            ("siat-kè-kó", "siat4ke3ko2"),
            ("kàu-tìng", "kau3ting3"),
            ("kok-tàn", "kok4tan3"),
            ("him-bōo", "him1boo7"),
            ("lāu-ta-ke", "lau7ta1ke1"),
            ("ōo-thâu", "oo7thau5"),
            ("kìn-jiàu", "kin3jiau3"),
            ("buán-huē", "buan2hue7"),
            ("thong-huè-phòng-tiùnn", "thong1hue3phong3tiunn3"),
            ("kim-tsuā", "kim1tsua7"),
            ("pháinn-tshiú-tsoh", "phainn2tshiu2tsoh4"),
            ("pik-lîm-uî-tshiûnn", "pik4lim5ui5tshiunn5"),
            ("tuā-tè", "tua7te3"),
            ("san-ḿ", "san1m2"),
            ("kim-koo-tsháu", "kim1koo1tshau2"),
            ("àm-bé-huè-pè", "am3be2hue3pe3"),
            ("tsí-tuânn", "tsi2tuann5"),
            ("mài-khìr", "mai3khir3"),
            ("phuà--khì", "phua3khi3"),
            ("kiu-á", "kiu1a2"),
            ("huán-tshî", "huan2tshi5"),
            ("tshiah-phuê", "tshiah4phue5"),
            ("sái-sìng-la̍k-tuē", "sai2sing3lak8tue7"),
            ("kàu-tuì", "kau3tui3"),
            ("tsóng-tuann", "tsong2tuann1"),
            ("tshâi-hông-toh", "tshai5hong5toh4"),
            ("gûn-kun", "gun5kun1"),
            ("tsò-kōng", "tso3kong7"),
            ("huē-gōo", "hue7goo7"),
            ("bóng-tsiong-tsiū", "bong2tsiong1tsiu7"),
            ("tâng-kun-thih-kut", "tang5kun1thih4kut4"),
            ("sè-siōng", "se3siong7"),
            ("tīng-tua̍t", "ting7tuat8"),
            ("phìng-lé", "phing3le2"),
            ("siáu-sî-tsing", "siau2si5tsing1"),
            ("iû-tsia̍h-kué", "iu5tsiah8kue2"),
            ("pông-pinn", "pong5pinn1"),
            ("kau-lâng", "kau1lang5"),
            ("bān-á-sī", "ban7a2si7"),
            ("kín-siú", "kin2siu2"),
            ("tāi-put-lia̍t-tian-kok", "tai7put4liat8tian1kok4"),
            ("tông-kám", "tong5kam2"),
            ("sann-guân-sik", "sann1guan5sik4"),
            ("siong-thîng-póo-sî", "siong1thing5poo2si5"),
            ("sé-thau-mn̄g-tsing", "se2thau1mng7tsing1"),
            ("li̍t-lo̍h-sin", "lit8loh8sin1"),
            ("tng-sū-ê", "tng1su7e5"),
            ("phok-tóo-huānn", "phok4too2huann7"),
            ("nuā-tsô", "nua7tso5"),
            ("kiám-tsng-á", "kiam2tsng1a2"),
            ("khòng-tshia", "khong3tshia1"),
            ("hu̍t-siú", "hut8siu2"),
            ("hang-lôo-sìnn", "hang1loo5sinn3"),
            ("tsháu-tùn-tìn", "tshau2tun3tin3"),
            ("tāu-hū", "tau7hu7"),
            ("phùn-siā-ki", "phun3sia7ki1"),
            ("tsū-sóo", "tsu7soo2"),
            ("lāu-hàn", "lau7han3"),
            ("jī-gōo-gûn", "ji7goo7gun5"),
            ("bû-tiong", "bu5tiong1"),
            ("siau-hông-tuī", "siau1hong5tui7"),
            ("khe-tsi-páng", "khe1tsi1pang2"),
            ("tē-hông-pôo", "te7hong5poo5"),
            ("sì-thua-puânn", "si3thua1puann5"),
            ("tsâi-bo̍k", "tsai5bok8"),
            ("sann-thâu-nn̄g-bīn", "sann1thau5nng7bin7"),
            ("kha̍k-thâm", "khak8tham5"),
            ("bī-sòo-hún", "bi7soo3hun2"),
            ("lâ-giâ", "la5gia5"),
            ("king-tsiá-iú-kî-tiân", "king1tsia2iu2ki5tian5"),
            ("tsio̍h-piah", "tsioh8piah4"),
            ("mn̄g-hō", "mng7ho7"),
            ("tshia-lián-tsháu", "tshia1lian2tshau2"),
            ("han-tsî-tshiam", "han1tsi5tshiam1"),
            ("siang-ji̍t", "siang1jit8"),
            ("khu̍t-bé", "khut8be2"),
            ("sîn-hûn", "sin5hun5"),
            ("tsn̄g-tsi-bai", "tsng7tsi1bai1"),
            ("tshuah-sái", "tshuah4sai2"),
            ("san--á", "san1a2"),
            ("khí-té", "khi2te2"),
            ("uat-tsiànn-tshiú", "uat4tsiann3tshiu2"),
            ("kóo-tsìng", "koo2tsing3"),
            ("khún-thâu", "khun2thau5"),
            ("bú-thún", "bu2thun2"),
            ("hah-hǐ", "hah4hi6"),
            ("tshiânn-tshiú", "tshiann5tshiu2"),
            ("lak-bīn", "lak4bin7"),
            ("siông-sî", "siong5si5"),
            ("lōo-thîng", "loo7thing5"),
            ("khai-kiû", "khai1kiu5"),
            ("khí-hìng", "khi2hing3"),
            ("uē-siong", "ue7siong1"),
            ("siū-suann", "siu7suann1"),
            ("síng-sū", "sing2su7"),
            ("siū-lí", "siu7li2"),
            ("kóo-jī", "koo2ji7"),
            ("lio̍k-tiâu", "liok8tiau5"),
            ("kai-kī", "kai1ki7"),
            ("tàu-hûn", "tau3hun5"),
            ("iánn-siā", "iann2sia7"),
            ("khi̍t", "khit8"),
            ("piáu-siōng", "piau2siong7"),
            ("lī-tû", "li7tu5"),
            ("tsiunn-ló-sua", "tsiunn1lo2sua1"),
            ("siang-to-tsháu-kâu", "siang1to1tshau2kau5"),
            ("khuànn-tshing-khuànn-bān", "khuann3tshing1khuann3ban7"),
            ("bô-sim-sik", "bo5sim1sik4"),
            ("miâ-siann-thàu-kiann-siânn", "mia5siann1thau3kiann1siann5"),
            ("pôo-thô", "poo5tho5"),
            ("liú-kun", "liu2kun1"),
            ("lāng-tuā", "lang7tua7"),
            ("tuā-huê-hiunn", "tua7hue5hiunn1"),
            ("bín-sé", "bin2se2"),
            ("tàu-tsáu", "tau3tsau2"),
            ("lîng-náu", "ling5nau2"),
            ("thôo-tāu-iû", "thoo5tau7iu5"),
            ("thōo-thng", "thoo7thng1"),
            ("bîng-tsu", "bing5tsu1"),
            ("hûn-liōng", "hun5liong7"),
            ("káu-bú-sua", "kau2bu2sua1"),
            ("kám-thàn-sû", "kam2than3su5"),
            ("king-thâu", "king1thau5"),
            ("thiàng", "thiang3"),
            ("tíng-io-sann-kak-hîng", "ting2io1sann1kak4hing5"),
            ("kāu-uē-sái", "kau7ue7sai2"),
            ("hia̍h-hûn", "hiah8hun5"),
            ("lio̍k-siāng", "liok8siang7"),
            ("huâinn-tn̄g-bīn", "huainn5tng7bin7"),
            ("âng-jîn-thôo", "ang5jin5thoo5"),
            ("kauh--kuè", "kauh4kue3"),
            ("líng-tué", "ling2tue2"),
            ("lí-ka", "li2ka1"),
            ("phang-ia̍h", "phang1iah8"),
    ]

    /// poj（帶調符）-> tl_num (via normalize)
    /// Expected values are in POJ numeric form; the test converts them to TL
    /// via normalizeToTL before comparison, since normalize(.poj) produces TL output.
    private let pojCases: [(input: String, expected: String)] = [
            ("choán-táu", "choan2tau2"),
            ("hông-lio̍k-chìn-jī-cha̍p", "hong5liok8chin3ji7chap8"),
            ("n̂g-kú", "ng5ku2"),
            ("siān-lâm", "sian7lam5"),
            ("siōng-súi", "siong7sui2"),
            ("lâm-thian-tek", "lam5thian1tek4"),
            ("to-kǹg", "to1kng3"),
            ("seⁿ-thâu-m̄-bat-hūn", "senn1thau5m7bat4hun7"),
            ("hù-sí", "hu3si2"),
            ("tō͘-chè", "too7che3"),
            ("iām-chong", "iam7chong1"),
            ("chhùi-bô-thàng-sim-koaⁿ", "chhui3bo5thang3sim1koann1"),
            ("the̍k", "thek8"),
            ("pàng-phùi-chhia", "pang3phui3chhia1"),
            ("ìn-chiong", "in3chiong1"),
            ("hân-kok-kiâm-chhài", "han5kok4kiam5chhai3"),
            ("khu-phiô", "khu1phio5"),
            ("bô-pē-kiáⁿ", "bo5pe7kiann2"),
            ("bô-liâu-bô-siàu", "bo5liau5bo5siau3"),
            ("î-bí", "i5bi2"),
            ("ū-sin-īn", "u7sin1in7"),
            ("chà-tân", "cha3tan5"),
            ("phòng-phā", "phong3pha7"),
            ("khí-bú", "khi2bu2"),
            ("bôe-á", "boe5a2"),
            ("gû-phīⁿ-khoân", "gu5phinn7khoan5"),
            ("iû-lō", "iu5lo7"),
            ("chi̍t-kò-ge̍h", "chit8ko3geh8"),
            ("tàu-hūn", "tau3hun7"),
            ("múi-bió-kong-chhioh-sò͘", "mui2bio2kong1chhioh4soo3"),
            ("chhàu-kî", "chhau3ki5"),
            ("chiú-khang-pâng", "chiu2khang1pang5"),
            ("ji̍p-se̍k", "jip8sek8"),
            ("tîn-sio̍k", "tin5siok8"),
            ("phah-tiān-pò", "phah4tian7po3"),
            ("a-lí-san-soaⁿ-me̍h", "a1li2san1soann1meh8"),
            ("kiò-kiù-hō͘", "kio3kiu3hoo7"),
            ("chhóaⁿ-nōa-kut", "chhoann2noa7kut4"),
            ("liāng-tō͘", "liang7too7"),
            ("kiám-ia̍t", "kiam2iat8"),
            ("lióng-hong", "liong2hong1"),
            ("sóng-lī", "song2li7"),
            ("jī--goe̍h", "ji7goeh8"),
            ("kim-liông", "kim1liong5"),
            ("chio̍h-kham", "chioh8kham1"),
            ("gōa-piáu", "goa7piau2"),
            ("hoān-sè", "hoan7se3"),
            ("sóng-sim", "song2sim1"),
            ("chit-chhì", "chit4chhi3"),
            ("tián-hiān", "tian2hian7"),
            ("séng-hōe", "seng2hoe7"),
            ("koaiⁿh--chi̍t-ē", "koainnh4chit8e7"),
            ("khip-hiat-kúi", "khip4hiat4kui2"),
            ("liâm-tiⁿ", "liam5tinn1"),
            ("saⁿ-tōa-hoat-jîn", "sann1toa7hoat4jin5"),
            ("khui-kháu", "khui1khau2"),
            ("bē-hiâm-tit", "be7hiam5tit4"),
            ("hīⁿ-á-tō͘-chiam", "hinn7a2too7chiam1"),
            ("lī-hāi-io̍h", "li7hai7ioh8"),
            ("pēng-m̄-sī", "peng7m7si7"),
            ("khioh-pe̍h-bah", "khioh4peh8bah4"),
            ("tōa-thâu-pô", "toa7thau5po5"),
            ("bē-chhun-chhia", "be7chhun1chhia1"),
            ("phō͘-khì-mo͘h", "phoo7khi3mooh4"),
            ("hu̍t-sèng", "hut8seng3"),
            ("thâm-khì-kiat-hiong", "tham5khi3kiat4hiong1"),
            ("sa̍h-chhiⁿ-chhài", "sah8chhinn1chhai3"),
            ("tē-lí-kéng-koan", "te7li2keng2koan1"),
            ("chio-á-saⁿ", "chio1a2sann1"),
            ("chok-ga̍k", "chok4gak8"),
            ("hông-hāi", "hong5hai7"),
            ("kóng-tōa-siaⁿ-ōe", "kong2toa7siann1oe7"),
            ("khoài-sok-thiap", "khoai3sok4thiap4"),
            ("giâ-ang-kê", "gia5ang1ke5"),
            ("chhî-ko͘", "chhi5koo1"),
            ("pōe-hong-bīn", "poe7hong1bin7"),
            ("it-tì", "it4ti3"),
            ("tāⁿ-ba̍k", "tann7bak8"),
            ("kî-jī-pêng", "ki5ji7peng5"),
            ("lióng-toān", "liong2toan7"),
            ("chiok-liōng", "chiok4liong7"),
            ("sió-cho͘", "sio2choo1"),
            ("ho̍k-ha̍p-keng", "hok8hap8keng1"),
            ("ti-bú-ni", "ti1bu2ni1"),
            ("an-lêng", "an1leng5"),
            ("iâⁿ-khu", "iann5khu1"),
            ("ké-chhòe", "ke2chhoe3"),
            ("khe-pêng", "khe1peng5"),
            ("lê-á-tō͘-kui", "le5a2too7kui1"),
            ("ê-tàu", "e5tau3"),
            ("siuⁿ-si-tāu", "siunn1si1tau7"),
            ("mûi-piáⁿ", "mui5piann2"),
            ("ha-bi̍t-koe", "ha1bit8koe1"),
            ("hiám-hiám", "hiam2hiam2"),
            ("iû-môa", "iu5moa5"),
            ("siâng-hiat-be̍k", "siang5hiat4bek8"),
            ("tō͘-liōng-hêng", "too7liong7heng5"),
            ("ìn-thûi", "in3thui5"),
            ("hù-si̍t", "hu3sit8"),
            ("chhiong-koàn-sòaⁿ", "chhiong1koan3soann3"),
            ("tǹg-ku", "tng3ku1"),
            ("thó͘-tē-kong", "thoo2te7kong1"),
            ("tâng-cháiⁿ", "tang5chainn2"),
            ("sí-ti̍t", "si2tit8"),
            ("bān-tang-tiū", "ban7tang1tiu7"),
            ("ti-pak-lāi", "ti1pak4lai7"),
            ("kiû-bián", "kiu5bian2"),
            ("só͘-sù", "soo2su3"),
            ("chiu-choán-kim", "chiu1choan2kim1"),
            ("táⁿ-tó͘", "tann2too2"),
            ("jî-chhut-it-tia̍t", "ji5chhut4it4tiat8"),
            ("chit-lú", "chit4lu2"),
            ("chhìn-ki-ki", "chhin3ki1ki1"),
            ("a-phiàn-kóng", "a1phian3kong2"),
            ("àn-sî-àn-ji̍t", "an3si5an3jit8"),
            ("n̂g-hoe-liám", "ng5hoe1liam2"),
            ("chia̍h-ka-tī", "chiah8ka1ti7"),
            ("thâu-kang", "thau5kang1"),
            ("phùn-seh-sap-á", "phun3seh4sap4a2"),
            ("thiⁿ-chò-thiⁿ-chhiâⁿ", "thinn1cho3thinn1chhiann5"),
            ("lûi-kong-chhùi", "lui5kong1chhui3"),
            ("thok-hù", "thok4hu3"),
            ("chóa-lî", "choa2li5"),
            ("nâ-kng-kng-tia̍p", "na5kng1kng1tiap8"),
            ("ge̍h-ge̍h-âng", "geh8geh8ang5"),
            ("kè-biô", "ke3bio5"),
            ("khiām-sí-sí", "khiam7si2si2"),
            ("òⁿ-òⁿ-lióng", "onn3onn3liong2"),
            ("chhòaⁿ-tō", "chhoann3to7"),
            ("chó-mûi", "cho2mui5"),
            ("liû-bông", "liu5bong5"),
            ("chhak-khiā", "chhak4khia7"),
            ("láu-hio̍h-á-tîn", "lau2hioh8a2tin5"),
            ("ûi-liû", "ui5liu5"),
            ("khai-kiû", "khai1kiu5"),
            ("tiàu-chè", "tiau3che3"),
            ("pe̍h-sin-lâng", "peh8sin1lang5"),
            ("phīⁿ-khang-mn̂g", "phinn7khang1mng5"),
            ("hiat-khò͘", "hiat4khoo3"),
            ("chí-tián-hāu-sio̍k", "chi2tian2hau7siok8"),
            ("pok-jī-hông-lâi", "pok4ji7hong5lai5"),
            ("lò͘-suh", "loo3suh4"),
            ("kó͘-kài", "koo2kai3"),
            ("poàn-thian-hui", "poan3thian1hui1"),
            ("iân-pán-jī", "ian5pan2ji7"),
            ("poàn-sò͘", "poan3soo3"),
            ("tám-lia̍k", "tam2liak8"),
            ("tián-ui-hêng", "tian2ui1heng5"),
            ("hân-kok-hì", "han5kok4hi3"),
            ("khùn-cheng-sîn", "khun3cheng1sin5"),
            ("thòaⁿ-chéng", "thoann3cheng2"),
            ("chhàu-leng-hoe", "chhau3leng1hoe1"),
            ("thn̂g-pang", "thng5pang1"),
            ("chhiah-khak-chu̍t", "chhiah4khak4chut8"),
            ("phôe-to", "phoe5to1"),
            ("thióng-soaⁿ", "thiong2soann1"),
            ("liāng-lē", "liang7le7"),
            ("sò͘-má-pò-chóa", "soo3ma2po3choa2"),
            ("pîⁿ-pîⁿ", "pinn5pinn5"),
            ("ba̍k-thâu-chi̍t-ē-kat", "bak8thau5chit8e7kat4"),
            ("chhù-ūn", "chhu3un7"),
            ("chi̍h-kam", "chih8kam1"),
            ("siūⁿ-bōe-chhut", "siunn7boe7chhut4"),
            ("tâng-oe-á", "tang5oe1a2"),
            ("chang-láng", "chang1lang2"),
            ("chó͘-hū", "choo2hu7"),
            ("jīm-sū", "jim7su7"),
            ("thǹg-kê", "thng3ke5"),
            ("peng-hiòng", "peng1hiong3"),
            ("hong-bō", "hong1bo7"),
            ("hok-te̍k", "hok4tek8"),
            ("tiô-kha-ke", "tio5kha1ke1"),
            ("chóng-hōe", "chong2hoe7"),
            ("pō͘-san-hó͘", "poo7san1hoo2"),
            ("phah-thong-thò", "phah4thong1tho3"),
            ("tâu-su", "tau5su1"),
            ("tāi-kah-līn", "tai7kah4lin7"),
            ("chím-thâu-kha", "chim2thau5kha1"),
            ("chiūⁿ-khò", "chiunn7kho3"),
            ("tô͘-ki", "too5ki1"),
            ("chit-pò͘-chhiúⁿ", "chit4poo3chhiunn2"),
            ("phó͘-phiàn-hòa", "phoo2phian3hoa3"),
            ("ta-sò-hoe", "ta1so3hoe1"),
            ("tiak-hiān-sián", "tiak4hian7sian2"),
            ("chhiú-tâm", "chhiu2tam5"),
            ("chu-goân-hôe-siu-tháng", "chu1goan5hoe5siu1thang2"),
            ("kàu-choa̍t-hong-niá", "kau3choat8hong1nia2"),
            ("gia̍p-û", "giap8u5"),
            ("se̍k-phê-gām-āⁿ", "sek8phe5gam7ann7"),
            ("thò-thâu-ōe", "tho3thau5oe7"),
            ("cha̍p-chhùi-tāi", "chap8chhui3tai7"),
            ("bo̍k-sio̍k", "bok8siok8"),
            ("bōe-koh-chài", "boe7koh4chai3"),
            ("chhiáⁿ-thèng-hāu", "chhiann2theng3hau7"),
            ("bô-thâu-cháng", "bo5thau5chang2"),
            ("koa̍t", "koat8"),
            ("thiam-siū", "thiam1siu7"),
            ("hong-sìn", "hong1sin3"),
            ("hé-chio̍h", "he2chioh8"),
            ("tek-cha̍h", "tek4chah8"),
            ("ba̍k-chiu-lia", "bak8chiu1lia1"),
            ("chiām-chiām", "chiam7chiam7"),
            ("se-iûⁿ-oe-á-chhài", "se1iunn5oe1a2chhai3"),
            ("chū-liân-sú", "chu7lian5su2"),
            ("nōa-sèng", "noa7seng3"),
            ("hông-gâ-lī", "hong5ga5li7"),
            ("pe̍h-hm̂", "peh8hm5"),
            ("am-mûi", "am1mui5"),
            ("jiòng-bi̍t", "jiong3bit8"),
            ("hiāⁿ-mî", "hiann7mi5"),
            ("ngī-gê--ê", "ngi7ge5e5"),
            ("sái", "sai2"),
            ("àu-tah", "au3tah4"),
            ("o͘-khí-ná-oah", "oo1khi2na2oah4"),
            ("ǔ-sin", "u6sin1"),
            ("chhiú-hêng", "chhiu2heng5"),
            ("pó͘-iông", "poo2iong5"),
            ("hàn-io̍h-tiàm", "han3ioh8tiam3"),
            ("su-êng", "su1eng5"),
            ("tōa-him", "toa7him1"),
            ("chhùn", "chhun3"),
            ("thióng-sēng", "thiong2seng7"),
            ("mn̂g-hō͘-chi-kiàn", "mng5hoo7chi1kian3"),
            ("gō͘-káu-sì-cha̍p-gō͘", "goo7kau2si3chap8goo7"),
            ("bō͘-bêng", "boo7beng5"),
            ("giû-seng", "giu5seng1"),
            ("sòe-siu", "soe3siu1"),
            ("sok-kì", "sok4ki3"),
            ("chò-khiàn-sńg", "cho3khian3sng2"),
            ("sé-sin-khu-cheng", "se2sin1khu1cheng1"),
            ("chha̍t-á-kut", "chhat8a2kut4"),
            ("chiàm-khoân", "chiam3khoan5"),
            ("tì-hāu-sû", "ti3hau7su5"),
            ("it-lám-piáu", "it4lam2piau2"),
            ("ló͘-mī", "loo2mi7"),
            ("hoa̍h-kòe", "hoah8koe3"),
            ("pn̄g-khok-á", "png7khok4a2"),
            ("lāi-soaⁿ-táu-tóe", "lai7soann1tau2toe2"),
            ("hûi-a̍p", "hui5ap8"),
            ("pe̍h-lāi-chiàng", "peh8lai7chiang3"),
            ("mô͘-kâu", "moo5kau5"),
            ("páng-phiò-húi-tô͘", "pang2phio3hui2too5"),
            ("niau-á-kiáⁿ", "niau1a2kiann2"),
            ("chek-mā", "chek4ma7"),
            ("khûn-kang", "khun5kang1"),
            ("chiàu-chiat", "chiau3chiat4"),
            ("jîn-som", "jin5som1"),
            ("chhu-lián-pang", "chhu1lian2pang1"),
            ("pēⁿ-chèng", "penn7cheng3"),
            ("lō͘-bé-sin", "loo7be2sin1"),
            ("bah-îⁿ-á", "bah4inn5a2"),
            ("kông-ke̍h", "kong5keh8"),
            ("hng-hng-hìⁿ-hìⁿ", "hng1hng1hinn3hinn3"),
            ("teng-á-bé", "teng1a2be2"),
            ("hián-sī-phìⁿ", "hian2si7phinn3"),
            ("soe-bóe-tō-jîn", "soe1boe2to7jin5"),
            ("tiâu-tō͘", "tiau5too7"),
            ("tāi-lio̍k-meh-á-chhài", "tai7liok8meh4a2chhai3"),
            ("khăn-jió͘", "khan9jioo2"),
            ("thiò-chhiú", "thio3chhiu2"),
            ("tn̂g-bé-tīn-á", "tng5be2tin7a2"),
            ("siù-io̍k", "siu3iok8"),
            ("kek-khiáu", "kek4khiau2"),
            ("chhéng-khoán", "chheng2khoan2"),
            ("tô͘-giân", "too5gian5"),
            ("kiâm-siap", "kiam5siap4"),
            ("khòaⁿ-bē-hiáu", "khoann3be7hiau2"),
            ("béng-sè", "beng2se3"),
            ("hó͘-phê-jio̍k", "hoo2phe5jiok8"),
            ("ngá-koan", "nga2koan1"),
            ("khiâ-bé-long", "khia5be2long1"),
            ("chhài-chhī-á-miâ", "chhai3chhi7a2mia5"),
            ("ngô͘-lo̍k", "ngoo5lok8"),
            ("sn̂g", "sng5"),
            ("chòng-iông", "chong3iong5"),
            ("ūi-tn̂g-iām", "ui7tng5iam7"),
            ("choa̍h-hn̄g", "choah8hng7"),
            ("kui-hòa", "kui1hoa3"),
            ("kòe-kak", "koe3kak4"),
            ("iok-nî", "iok4ni5"),
            ("hok-im-tn̂g", "hok4im1tng5"),
            ("bô-liâng-sim", "bo5liang5sim1"),
            ("chhek-gê", "chhek4ge5"),
            ("āu-bó-bīn", "au7bo2bin7"),
            ("khioh-khǹg", "khioh4khng3"),
            ("khòng-tāi", "khong3tai7"),
            ("āu-khut-khe", "au7khut4khe1"),
            ("siû-phiò", "siu5phio3"),
            ("chhut-seng-ji̍p-sú", "chhut4seng1jip8su2"),
            ("chhēng-saⁿ", "chheng7sann1"),
            ("chài-tông-hiaⁿ-tī", "chai3tong5hiann1ti7"),
            ("kiān-choân", "kian7choan5"),
            ("loān-nāu", "loan7nau7"),
            ("lī-bē-khui", "li7be7khui1"),
            ("tē-cho͘-toaⁿ", "te7choo1toann1"),
            ("chiáu-chia̍h-be̍h", "chiau2chiah8beh8"),
            ("lōng-tiâu", "long7tiau5"),
            ("chhâ-kho̍k", "chha5khok8"),
            ("siang-bīn-kng", "siang1bin7kng1"),
            ("tē-jī-sió-thê-khîm", "te7ji7sio2the5khim5"),
    ]

    // MARK: - Tests

    func testTlToTlNum() {
        for (input, expected) in tlCases {
            let result = InputNormalizer.normalize(input, mode: .tl)
            XCTAssertEqual(
                result,
                expected,
                "normalize(\"\(input)\", .tl) should be \"\(expected)\", got \"\(result)\""
            )
        }
    }

    // MARK: - Mode Validation

    func testNormalize_pojMode_acceptsPOJInput() {
        let cases: [(input: String, reason: String)] = [
            ("ch", "POJ initial prefix"),
            ("chi", "POJ syllable"),
            ("eng", "POJ final"),
            ("goa", "POJ final oa"),
            ("hoo2", "oo is shared"),
            ("ka", "shared syllable"),
        ]
        for (input, reason) in cases {
            let result = InputNormalizer.normalize(input, mode: .poj)
            XCTAssertNotEqual(
                result, "",
                "normalize(\"\(input)\", .poj) should not be empty: \(reason)"
            )
        }
    }

    func testNormalize_tlMode_acceptsTLInput() {
        let cases: [(input: String, reason: String)] = [
            ("ts", "TL initial prefix"),
            ("tsi", "TL syllable"),
            ("gua", "TL final ua"),
            ("ing", "TL final"),
            ("eng", "TL final (嬰)"),
            ("ka", "shared syllable"),
        ]
        for (input, reason) in cases {
            let result = InputNormalizer.normalize(input, mode: .tl)
            XCTAssertNotEqual(
                result, "",
                "normalize(\"\(input)\", .tl) should not be empty: \(reason)"
            )
        }
    }

    func testPojDiacriticToPojNum() {
        for (input, expected) in pojCases {
            let result = InputNormalizer.normalize(input, mode: .poj)
            // normalize(.poj) now stays in POJ form (no TL conversion);
            // the trie prefix (poj:) is added at query boundary instead
            XCTAssertEqual(
                result,
                expected,
                "normalize(\"\(input)\", .poj) should be \"\(expected)\", got \"\(result)\""
            )
        }
    }
}
