# i18n codegen core: parse the canonical i18n/*.json sources and produce every generated artifact.
#
# `build_outputs(repo_root)` returns {repo-relative path -> file content}. generate.py writes them;
# check.py compares them byte-for-byte against the committed tree. Keeping a single pure function as
# the source of truth means the freshness gate cannot drift from the generator.

import json
import math
import re
from pathlib import Path

# --- Schema constants -------------------------------------------------------

# Base language: every key MUST define this. Other languages are authored in later phases
# (P2 en / P3a ja / P3b TL / P3c POJ); their absence is a deliberate fallback, not an error.
BASE_LANGUAGE = "hanji"

# Display languages emitted to the Kotlin TL/POJ map (no OS locale -> GeneratedMap path).
GENERATED_MAP_LANGUAGES = ("tailo", "poj")

VALID_PLATFORMS = {"ios", "android"}
VALID_SURFACES = {"host", "extension"}
VALID_VALUE_LANGUAGES = {"hanji", "tailo", "poj", "ja", "en"}

# Output locations (repo-relative).
ANDROID_PKG = "android/app/src/main/java/com/siansiansu/taigikeyboard"
ANDROID_RES_ROOT = "android/app/src/main/res"
GEN_PKG_DIR = f"{ANDROID_PKG}/i18n/generated"

# Languages resolved via native Android resource dirs (plan D2). hanji -> default values/ (always
# emitted); en/ja -> language-qualified dirs, emitted only once a key actually carries that value.
NATIVE_RESOURCE_DIRS = {
    "hanji": "values",
    "en": "values-en",
    "ja": "values-ja",
}

GENERATED_HEADER = "GENERATED by tools/i18n/generate.py — DO NOT EDIT. Run `make i18n`."

PLACEHOLDER_RE = re.compile(r"\{[^}]*\}")
DUPLICATE_KEY_ERROR = "duplicate key"


# --- Parsing (with duplicate-key detection) ---------------------------------


def _no_duplicate_keys(pairs):
    # json.load silently keeps the last duplicate; a duplicate key in a source file is almost
    # always an editing mistake that would silently drop a string, so reject it loudly.
    seen = {}
    for key, value in pairs:
        if key in seen:
            raise ValueError(f"{DUPLICATE_KEY_ERROR}: {key!r}")
        seen[key] = value
    return seen


def load_namespace(path: Path) -> dict:
    text = path.read_text(encoding="utf-8")
    try:
        data = json.loads(text, object_pairs_hook=_no_duplicate_keys)
    except ValueError as exc:
        raise ValueError(f"{path}: {exc}") from exc
    return data


# --- Validation -------------------------------------------------------------


def validate_namespace(namespace: str, data: dict, path: Path) -> None:
    if data.get("namespace") != namespace:
        raise ValueError(f"{path}: top-level 'namespace' must equal {namespace!r}")
    keys = data.get("keys")
    if not isinstance(keys, dict):
        raise ValueError(f"{path}: missing 'keys' object")
    for key, entry in keys.items():
        if not re.fullmatch(r"[a-z][a-zA-Z0-9]*", key):
            raise ValueError(f"{path}: key {key!r} must be lowerCamelCase")
        scope = entry.get("scope", {})
        platforms = set(scope.get("platforms", []))
        surfaces = set(scope.get("surfaces", []))
        if not platforms or not platforms <= VALID_PLATFORMS:
            raise ValueError(f"{path}:{key}: scope.platforms must be a non-empty subset of {sorted(VALID_PLATFORMS)}")
        if not surfaces or not surfaces <= VALID_SURFACES:
            raise ValueError(f"{path}:{key}: scope.surfaces must be a non-empty subset of {sorted(VALID_SURFACES)}")
        values = entry.get("values", {})
        if BASE_LANGUAGE not in values or not values[BASE_LANGUAGE]:
            raise ValueError(f"{path}:{key}: missing required base-language value '{BASE_LANGUAGE}'")
        unknown = set(values) - VALID_VALUE_LANGUAGES
        if unknown:
            raise ValueError(f"{path}:{key}: unknown value languages {sorted(unknown)}")
        # Sorted-list (not set) compare so a duplicated placeholder is caught too.
        base_placeholders = sorted(PLACEHOLDER_RE.findall(values[BASE_LANGUAGE]))
        # If a key declares `placeholders`, it must match the placeholders actually used in base text.
        declared = entry.get("placeholders")
        if declared is not None:
            declared_spans = sorted("{" + name + "}" for name in declared)
            if declared_spans != base_placeholders:
                raise ValueError(f"{path}:{key}: declared placeholders {declared_spans} != base text {base_placeholders}")
        for lang, text in values.items():
            # Reject empty authored values — a blank string would render blank, not fall back to base.
            if not text:
                raise ValueError(f"{path}:{key}: empty value for '{lang}'")
            # Placeholder consistency: every authored language must carry the same placeholders as base.
            if sorted(PLACEHOLDER_RE.findall(text)) != base_placeholders:
                raise ValueError(f"{path}:{key}: placeholder mismatch in '{lang}' vs base")


# --- Name transforms --------------------------------------------------------


def _camel_to_snake(name: str) -> str:
    return re.sub(r"(?<!^)(?=[A-Z])", "_", name).lower()


def res_name(namespace: str, key: str) -> str:
    return f"i18n_{namespace}_{key}"


def string_key_const(namespace: str, key: str) -> str:
    return f"{namespace.upper()}_{_camel_to_snake(key).upper()}"


def l10n_accessor(namespace: str, key: str) -> str:
    return f"{namespace}{key[0].upper()}{key[1:]}"


# --- Pseudo-locale ----------------------------------------------------------

_ACCENT = {
    "a": "á", "b": "ḅ", "c": "ç", "d": "ḋ", "e": "é", "f": "ḟ", "g": "ǧ",
    "h": "ḣ", "i": "í", "j": "ĵ", "k": "ḱ", "l": "ĺ", "m": "ṁ", "n": "ñ",
    "o": "ó", "p": "ṗ", "q": "q̧", "r": "ŕ", "s": "š", "t": "ť", "u": "ú",
    "v": "v̧", "w": "ẃ", "x": "x̌", "y": "ý", "z": "ž",
    "A": "Á", "B": "Ḅ", "C": "Ç", "D": "Ḋ", "E": "É", "F": "Ḟ", "G": "Ǧ",
    "H": "Ḣ", "I": "Í", "J": "Ĵ", "K": "Ḱ", "L": "Ĺ", "M": "Ṁ", "N": "Ñ",
    "O": "Ó", "P": "Ṗ", "Q": "Q̧", "R": "Ŕ", "S": "Š", "T": "Ť", "U": "Ú",
    "V": "V̧", "W": "Ẃ", "X": "X̌", "Y": "Ý", "Z": "Ž",
}


def pseudo(text: str) -> str:
    # Accent ASCII, preserve {placeholders} verbatim, then bracket + length-inflate ~40%
    # so Hanji-heavy strings (no ASCII to accent) still exercise clipping/layout limits.
    parts = PLACEHOLDER_RE.split(text)
    placeholders = PLACEHOLDER_RE.findall(text)
    rebuilt = []
    visible_len = 0
    for index, chunk in enumerate(parts):
        rebuilt.append("".join(_ACCENT.get(char, char) for char in chunk))
        visible_len += len(chunk)
        if index < len(placeholders):
            rebuilt.append(placeholders[index])
    pad = "·" * max(2, math.ceil(visible_len * 0.4))
    return f"⟦{''.join(rebuilt)}{pad}⟧"


# --- Escaping ---------------------------------------------------------------


def xml_escape(value: str) -> str:
    # `>` is legal as raw text in XML element content (Android strings.xml never escapes it),
    # so only `&` and `<` need entity-escaping; quotes/newline use Android's backslash form.
    out = (
        value.replace("&", "&amp;")
        .replace("<", "&lt;")
        .replace('"', "\\\"")
        .replace("'", "\\'")
        .replace("\n", "\\n")
    )
    if out[:1] in ("@", "?"):
        out = "\\" + out
    return out


def kotlin_escape(value: str) -> str:
    return (
        value.replace("\\", "\\\\")
        .replace('"', '\\"')
        .replace("$", "\\$")
        .replace("\n", "\\n")
    )


# --- Emitters ---------------------------------------------------------------


def _collect_entries(repo_root: Path):
    # Returns an ordered list of (namespace, key, entry) across all i18n/*.json sources.
    src_dir = repo_root / "i18n"
    entries = []
    for path in sorted(src_dir.glob("*.json")):
        namespace = path.stem
        data = load_namespace(path)
        validate_namespace(namespace, data, path)
        for key, entry in data["keys"].items():
            entries.append((namespace, key, entry))
    return entries


def _emit_strings_xml(entries, lang: str) -> str:
    lines = ['<?xml version="1.0" encoding="utf-8"?>', f"<!-- {GENERATED_HEADER} -->", "<resources>"]
    for namespace, key, entry in entries:
        if lang not in entry["values"]:
            continue
        value = xml_escape(entry["values"][lang])
        lines.append(f'    <string name="{res_name(namespace, key)}">{value}</string>')
    lines.append("</resources>")
    return "\n".join(lines) + "\n"


def _emit_string_key(entries) -> str:
    lines = [
        f"// {GENERATED_HEADER}",
        "package com.siansiansu.taigikeyboard.i18n.generated",
        "",
        "import androidx.annotation.StringRes",
        "import com.siansiansu.taigikeyboard.R",
        "",
        "/** Typed key for every i18n string. [resId] points at the Hanji default in res/values/strings_i18n.xml. */",
        "enum class StringKey(",
        "    @StringRes val resId: Int,",
        ") {",
    ]
    for namespace, key, _entry in entries:
        lines.append(f"    {string_key_const(namespace, key)}(R.string.{res_name(namespace, key)}),")
    lines.append("}")
    return "\n".join(lines) + "\n"


def _emit_taigi_map(entries) -> str:
    lines = [
        f"// {GENERATED_HEADER}",
        "package com.siansiansu.taigikeyboard.i18n.generated",
        "",
        "import com.siansiansu.taigikeyboard.i18n.DisplayLanguage",
        "",
        "/**",
        " * TL/POJ string overrides (the GeneratedMap resolution path — these languages have no OS locale).",
        " * Empty entries fall back to the Hanji default; later phases (P3b TL / P3c POJ) populate them.",
        " */",
        "object GeneratedTaigiStrings {",
    ]
    for lang in GENERATED_MAP_LANGUAGES:
        pairs = [(namespace, key, entry) for namespace, key, entry in entries if lang in entry["values"]]
        if pairs:
            lines.append(f"    private val {lang}: Map<StringKey, String> =")
            lines.append("        mapOf(")
            for namespace, key, entry in pairs:
                value = kotlin_escape(entry["values"][lang])
                lines.append(f'            StringKey.{string_key_const(namespace, key)} to "{value}",')
            lines.append("        )")
        else:
            lines.append(f"    private val {lang}: Map<StringKey, String> = emptyMap()")
    lines.extend(
        [
            "",
            "    fun lookup(",
            "        language: DisplayLanguage,",
            "        key: StringKey,",
            "    ): String? =",
            "        when (language) {",
            "            DisplayLanguage.TAILO -> tailo[key]",
            "            DisplayLanguage.POJ -> poj[key]",
            "            else -> null",
            "        }",
            "}",
        ]
    )
    return "\n".join(lines) + "\n"


def _emit_pseudo_map(entries) -> str:
    lines = [
        f"// {GENERATED_HEADER}",
        "package com.siansiansu.taigikeyboard.i18n.generated",
        "",
        "/** Debug-only pseudo-locale strings (length-inflated layout/clipping probe). Never shown in release. */",
        "object GeneratedPseudoStrings {",
        "    private val map: Map<StringKey, String> =",
        "        mapOf(",
    ]
    for namespace, key, entry in entries:
        value = kotlin_escape(pseudo(entry["values"][BASE_LANGUAGE]))
        lines.append(f'            StringKey.{string_key_const(namespace, key)} to "{value}",')
    lines.extend(
        [
            "        )",
            "",
            "    fun lookup(key: StringKey): String? = map[key]",
            "}",
        ]
    )
    return "\n".join(lines) + "\n"


def _emit_l10n(entries) -> str:
    lines = [
        f"// {GENERATED_HEADER}",
        "package com.siansiansu.taigikeyboard.i18n.generated",
        "",
        "import androidx.compose.runtime.Composable",
        "import com.siansiansu.taigikeyboard.i18n.stringRes",
        "",
        "/** Typed Compose accessors — one per i18n key, resolved under the active display language. */",
        "object L10n {",
    ]
    for namespace, key, _entry in entries:
        accessor = l10n_accessor(namespace, key)
        const = string_key_const(namespace, key)
        lines.append(f"    val {accessor}: String")
        lines.append(f"        @Composable get() = stringRes(StringKey.{const})")
    lines.append("}")
    return "\n".join(lines) + "\n"


def build_outputs(repo_root: Path) -> dict:
    all_entries = _collect_entries(repo_root)
    # Android artifacts cover only android-scoped keys (D5 scope filtering); an iOS-only key
    # must not leak into the Android resource set.
    entries = [item for item in all_entries if "android" in item[2]["scope"]["platforms"]]

    outputs = {}
    # Native resource sets: always emit the base (Hanji) default; emit en/ja only once a key
    # carries that value, so authoring a language later just works (no silent drop).
    for lang, res_dir in NATIVE_RESOURCE_DIRS.items():
        has_value = any(lang in entry["values"] for _ns, _key, entry in entries)
        if lang == BASE_LANGUAGE or has_value:
            outputs[f"{ANDROID_RES_ROOT}/{res_dir}/strings_i18n.xml"] = _emit_strings_xml(entries, lang)
    outputs[f"{GEN_PKG_DIR}/StringKey.kt"] = _emit_string_key(entries)
    outputs[f"{GEN_PKG_DIR}/GeneratedTaigiStrings.kt"] = _emit_taigi_map(entries)
    outputs[f"{GEN_PKG_DIR}/GeneratedPseudoStrings.kt"] = _emit_pseudo_map(entries)
    outputs[f"{GEN_PKG_DIR}/L10n.kt"] = _emit_l10n(entries)
    return outputs
