# i18n codegen core: parse the canonical i18n/*.json sources and produce every generated artifact.
#
# `build_outputs(repo_root)` returns {repo-relative path -> file content}. generate.py writes them;
# check.py compares them byte-for-byte against the committed tree. Keeping a single pure function as
# the source of truth means the freshness gate cannot drift from the generator.

import json
import math
import re
from pathlib import Path

# --- Schema constants -------------------------------------------------------

# Base language: every key MUST define this. Other languages are authored in later phases
# (P2 en / P3a ja / P3b TL / P3c POJ); their absence is a deliberate fallback, not an error.
BASE_LANGUAGE = "hanji"

# Display languages emitted to the Kotlin TL/POJ map (no OS locale -> GeneratedMap path).
GENERATED_MAP_LANGUAGES = ("tailo", "poj")

VALID_PLATFORMS = {"ios", "android"}
VALID_SURFACES = {"host", "extension"}
VALID_VALUE_LANGUAGES = {"hanji", "tailo", "poj", "ja", "en"}

# Output locations (repo-relative).
ANDROID_PKG = "android/app/src/main/java/com/siansiansu/taigikeyboard"
ANDROID_RES_ROOT = "android/app/src/main/res"
GEN_PKG_DIR = f"{ANDROID_PKG}/i18n/generated"

# iOS output locations. Both the String Catalog and the generated Swift live where the build
# already picks them up: the catalog is in the host+extension Copy-Bundle-Resources phase, and
# Strings/ is an Xcode synchronized group (auto-includes new files, no pbxproj edit).
IOS_XCSTRINGS = "ios/Localizable.xcstrings"
IOS_STRINGS_DIR = "ios/Sources/TaigiKeyboard/Strings"
IOS_GEN_DIR = f"{IOS_STRINGS_DIR}/Generated"

# Hanji has no OS locale; pin a Taiwanese-Hanji BCP-47 that maps NO Android resource-qualifier dir
# (so a Context built from it always yields the default values/ set) and is the iOS catalog's
# source language (see XCSTRINGS_SOURCE_LANGUAGE). Mirrors the Kotlin BCP47_HANJI top-level const.
BCP47_HANJI = "nan-Hant-TW"

# Authored language -> BCP-47 tag for the iOS String Catalog. TL/POJ use private-use subtags
# (RFC5646 §2.2.7); Xcode emits a loadable .lproj for them (R2b architecture probe).
# MIRROR: each tag here MUST equal `DisplayLanguage.bcp47` in
# ios/Sources/TaigiKeyboard/Strings/DisplayLanguage.swift — the catalog emits each localization under
# this tag and the runtime resolver loads `<tag>.lproj`; drift silently breaks resolution.
LANG_TO_BCP47 = {
    "hanji": BCP47_HANJI,
    "tailo": "nan-Latn-TW-x-tailo",
    "poj": "nan-Latn-TW-x-poj",
    "ja": "ja",
    "en": "en",
}

# The catalog's source language MUST be the canonical base (Hanji), NOT "en". With sourceLanguage
# "en", Xcode emits every key into en.lproj as its own identifier value (`"i18n_x"="i18n_x"`) even
# when only Hanji is authored, which defeats the runtime sentinel fallback so English would render
# the raw synthetic key. Verified on Xcode 26.5 xcstringstool (Codex pre-impl Q1).
XCSTRINGS_SOURCE_LANGUAGE = BCP47_HANJI

# Languages resolved via native Android resource dirs (plan D2). hanji -> default values/ (always
# emitted); en/ja -> language-qualified dirs, emitted only once a key actually carries that value.
NATIVE_RESOURCE_DIRS = {
    "hanji": "values",
    "en": "values-en",
    "ja": "values-ja",
}

GENERATED_HEADER = "GENERATED by tools/i18n/generate.py — DO NOT EDIT. Run `make i18n`."

PLACEHOLDER_RE = re.compile(r"\{[^}]*\}")
DUPLICATE_KEY_ERROR = "duplicate key"

# Identifier shape shared by namespace keys and placeholder names (both become Kotlin symbols).
IDENTIFIER_RE = re.compile(r"[a-z][a-zA-Z0-9]*")

# Placeholder type vocabulary: schema type -> per-target facets. The table is the single, complete
# extension point — adding a type propagates to both the typed accessor signature and the emitted
# format spec on every platform. Facets per target:
#   param — accessor signature type (Kotlin / Swift).
#   conv  — printf conversion char. Android `%d` (Java int); iOS `%lld` because Swift Int is 64-bit
#           and Apple's `%d` is 32-bit, so the unsuffixed spec would truncate large counts (Codex Q8.1).
#   cast  — (iOS only) expression wrapping the arg before String(format:) to match its conv char.
#           Android needs no cast (`%d` takes Int directly).
# Only `int` is needed today (every format arg is a count).
PLACEHOLDER_TYPES = {
    "int": {
        "android": {"param": "Int", "conv": "d"},
        "ios": {"param": "Int", "conv": "lld", "cast": "Int64"},
    },
}

# Swift hard keywords — a generated accessor name maps to a Swift symbol, so reject any that
# cannot be one. The accessor is namespace-prefixed (`commonCancel`), so a collision is unlikely,
# but the codegen validates it loudly rather than emit code that fails to compile.
SWIFT_KEYWORDS = frozenset(
    {
        "associatedtype", "class", "deinit", "enum", "extension", "fileprivate", "func", "import",
        "init", "inout", "internal", "let", "open", "operator", "private", "protocol", "public",
        "rethrows", "static", "struct", "subscript", "typealias", "var", "break", "case", "continue",
        "default", "defer", "do", "else", "fallthrough", "for", "guard", "if", "in", "repeat",
        "return", "switch", "where", "while", "as", "catch", "false", "is", "nil", "super", "self",
        "throw", "throws", "true", "try",
    }
)

# Kotlin hard keywords — a placeholder name maps directly to a function parameter, so reject any
# name that cannot be a Kotlin identifier.
KOTLIN_KEYWORDS = frozenset(
    {
        "as", "break", "class", "continue", "do", "else", "false", "for", "fun", "if", "in",
        "interface", "is", "null", "object", "package", "return", "super", "this", "throw",
        "true", "try", "typealias", "typeof", "val", "var", "when", "while",
    }
)


# --- Placeholder transforms -------------------------------------------------


def _placeholder_names_in_order(text: str) -> list:
    # Names of the {placeholder} spans, de-duplicated, in order of first appearance. The base-language
    # text defines the canonical positional order shared by every language (Fork 6: substitute by name).
    seen = []
    for match in PLACEHOLDER_RE.finditer(text):
        name = match.group()[1:-1]
        if name not in seen:
            seen.append(name)
    return seen


def _to_positional(text: str, order: list, declared: dict, target: str) -> str:
    # Convert authored {name} placeholders to positional args (%1$d, %2$d, ...), assigning each name
    # the index it has in `order` (the base-text appearance order) so a reordered translation still
    # maps each name to the right argument; the conversion char comes from the declared type + target
    # (Android %d vs iOS %lld). Run AFTER escaping/pseudo so the inserted specs are not accented/re-escaped.
    if not order:
        return text  # plain key: leave literal % untouched (it is never String.format'd)
    out = text.replace("%", "%%")  # escape literal % first; the named text has no positional specs yet
    for index, name in enumerate(order):
        conversion = PLACEHOLDER_TYPES[declared[name]][target]["conv"]
        out = out.replace("{" + name + "}", f"%{index + 1}${conversion}")
    return out


def _finalize_value(raw: str, escape, entry: dict, target: str) -> str:
    # Convert any placeholders to positional specs for `target`, THEN escape for the output (XML /
    # Kotlin / Swift / JSON-identity). Escaping last is load-bearing: `kotlin_escape` must turn the
    # inserted `%1$d`'s `$` into `\$` so the Kotlin source string is not read as a template; xml_escape
    # and the JSON-identity escape leave it untouched. `raw` is already pseudo-transformed by the caller
    # where applicable, so pseudo never accents `%N$d`. Order + declared types come from the base-language
    # text, so every language shares one mapping.
    base_text = entry["values"][BASE_LANGUAGE]
    return escape(_to_positional(raw, _placeholder_names_in_order(base_text), entry.get("placeholders", {}), target))


# --- Parsing (with duplicate-key detection) ---------------------------------


def _no_duplicate_keys(pairs):
    # json.load silently keeps the last duplicate; a duplicate key in a source file is almost
    # always an editing mistake that would silently drop a string, so reject it loudly.
    seen = {}
    for key, value in pairs:
        if key in seen:
            raise ValueError(f"{DUPLICATE_KEY_ERROR}: {key!r}")
        seen[key] = value
    return seen


def load_namespace(path: Path) -> dict:
    text = path.read_text(encoding="utf-8")
    try:
        data = json.loads(text, object_pairs_hook=_no_duplicate_keys)
    except ValueError as exc:
        raise ValueError(f"{path}: {exc}") from exc
    return data


# --- Validation -------------------------------------------------------------


def validate_namespace(namespace: str, data: dict, path: Path) -> None:
    if data.get("namespace") != namespace:
        raise ValueError(f"{path}: top-level 'namespace' must equal {namespace!r}")
    keys = data.get("keys")
    if not isinstance(keys, dict):
        raise ValueError(f"{path}: missing 'keys' object")
    for key, entry in keys.items():
        if not IDENTIFIER_RE.fullmatch(key):
            raise ValueError(f"{path}: key {key!r} must be lowerCamelCase")
        scope = entry.get("scope", {})
        platforms = set(scope.get("platforms", []))
        surfaces = set(scope.get("surfaces", []))
        if not platforms or not platforms <= VALID_PLATFORMS:
            raise ValueError(f"{path}:{key}: scope.platforms must be a non-empty subset of {sorted(VALID_PLATFORMS)}")
        if not surfaces or not surfaces <= VALID_SURFACES:
            raise ValueError(f"{path}:{key}: scope.surfaces must be a non-empty subset of {sorted(VALID_SURFACES)}")
        values = entry.get("values", {})
        if BASE_LANGUAGE not in values or not values[BASE_LANGUAGE]:
            raise ValueError(f"{path}:{key}: missing required base-language value '{BASE_LANGUAGE}'")
        unknown = set(values) - VALID_VALUE_LANGUAGES
        if unknown:
            raise ValueError(f"{path}:{key}: unknown value languages {sorted(unknown)}")
        # Placeholder discipline. Canonical names = those used in the base (Hanji) text; positional
        # index is assigned by first appearance there (see _to_positional). A format key MUST declare
        # `placeholders` (name -> type) so the generated typed accessor has an explicit signature.
        base_placeholder_names = set(_placeholder_names_in_order(values[BASE_LANGUAGE]))
        declared = entry.get("placeholders")
        if base_placeholder_names:
            if not declared:
                raise ValueError(f"{path}:{key}: base text uses placeholders {sorted(base_placeholder_names)} but none declared")
            if set(declared) != base_placeholder_names:
                raise ValueError(f"{path}:{key}: declared placeholders {sorted(declared)} != base text {sorted(base_placeholder_names)}")
            for name, ptype in declared.items():
                # A placeholder name becomes a function parameter on BOTH platforms (Kotlin in
                # StringResolverFormats.kt, Swift in StringResolverFormats.swift), so reject a name
                # that is a keyword on either — e.g. `default` is legal in Kotlin but emits an illegal
                # Swift `default: Int` parameter (Codex post-impl).
                if not IDENTIFIER_RE.fullmatch(name) or name in KOTLIN_KEYWORDS or name in SWIFT_KEYWORDS:
                    raise ValueError(f"{path}:{key}: placeholder name {name!r} must be a lowerCamelCase non-keyword identifier")
                if ptype not in PLACEHOLDER_TYPES:
                    raise ValueError(f"{path}:{key}: placeholder {name!r} type {ptype!r} not in {sorted(PLACEHOLDER_TYPES)}")
        elif declared:
            raise ValueError(f"{path}:{key}: declared placeholders {sorted(declared)} but base text has none")
        for lang, text in values.items():
            # Reject empty authored values — a blank string would render blank, not fall back to base.
            if not text:
                raise ValueError(f"{path}:{key}: empty value for '{lang}'")
            # Every authored language must use the same placeholder names as base (order may differ —
            # substitution is by name, not position, so a reordered translation is allowed).
            if set(_placeholder_names_in_order(text)) != base_placeholder_names:
                raise ValueError(f"{path}:{key}: placeholder names in '{lang}' differ from base")


# --- Name transforms --------------------------------------------------------


def _camel_to_snake(name: str) -> str:
    return re.sub(r"(?<!^)(?=[A-Z])", "_", name).lower()


def res_name(namespace: str, key: str) -> str:
    return f"i18n_{namespace}_{key}"


def string_key_const(namespace: str, key: str) -> str:
    return f"{namespace.upper()}_{_camel_to_snake(key).upper()}"


def l10n_accessor(namespace: str, key: str) -> str:
    return f"{namespace}{key[0].upper()}{key[1:]}"


# --- Pseudo-locale ----------------------------------------------------------

_ACCENT = {
    "a": "á", "b": "ḅ", "c": "ç", "d": "ḋ", "e": "é", "f": "ḟ", "g": "ǧ",
    "h": "ḣ", "i": "í", "j": "ĵ", "k": "ḱ", "l": "ĺ", "m": "ṁ", "n": "ñ",
    "o": "ó", "p": "ṗ", "q": "q̧", "r": "ŕ", "s": "š", "t": "ť", "u": "ú",
    "v": "v̧", "w": "ẃ", "x": "x̌", "y": "ý", "z": "ž",
    "A": "Á", "B": "Ḅ", "C": "Ç", "D": "Ḋ", "E": "É", "F": "Ḟ", "G": "Ǧ",
    "H": "Ḣ", "I": "Í", "J": "Ĵ", "K": "Ḱ", "L": "Ĺ", "M": "Ṁ", "N": "Ñ",
    "O": "Ó", "P": "Ṗ", "Q": "Q̧", "R": "Ŕ", "S": "Š", "T": "Ť", "U": "Ú",
    "V": "V̧", "W": "Ẃ", "X": "X̌", "Y": "Ý", "Z": "Ž",
}


def pseudo(text: str) -> str:
    # Accent ASCII, preserve {placeholders} verbatim, then bracket + length-inflate ~40%
    # so Hanji-heavy strings (no ASCII to accent) still exercise clipping/layout limits.
    parts = PLACEHOLDER_RE.split(text)
    placeholders = PLACEHOLDER_RE.findall(text)
    rebuilt = []
    visible_len = 0
    for index, chunk in enumerate(parts):
        rebuilt.append("".join(_ACCENT.get(char, char) for char in chunk))
        visible_len += len(chunk)
        if index < len(placeholders):
            rebuilt.append(placeholders[index])
    pad = "·" * max(2, math.ceil(visible_len * 0.4))
    return f"⟦{''.join(rebuilt)}{pad}⟧"


# --- Escaping ---------------------------------------------------------------


def xml_escape(value: str) -> str:
    # `>` is legal as raw text in XML element content (Android strings.xml never escapes it),
    # so only `&` and `<` need entity-escaping; quotes/newline use Android's backslash form.
    out = (
        value.replace("&", "&amp;")
        .replace("<", "&lt;")
        .replace('"', "\\\"")
        .replace("'", "\\'")
        .replace("\n", "\\n")
    )
    if out[:1] in ("@", "?"):
        out = "\\" + out
    return out


def kotlin_escape(value: str) -> str:
    return (
        value.replace("\\", "\\\\")
        .replace('"', '\\"')
        .replace("$", "\\$")
        .replace("\n", "\\n")
    )


def swift_escape(value: str) -> str:
    # Swift string-literal escaping. Backslash first so a literal `\(` becomes `\\(` (a backslash +
    # paren, not a string interpolation). Swift has no `$` template syntax, so `%1$lld` is left as-is.
    return (
        value.replace("\\", "\\\\")
        .replace('"', '\\"')
        .replace("\n", "\\n")
    )


def _json_identity(value: str) -> str:
    # The xcstrings emitter serializes via json.dumps, which performs all JSON escaping; values are
    # passed through unchanged so placeholder conversion is the only transform applied beforehand.
    return value


# --- Emitters ---------------------------------------------------------------


def _validate_global(entries) -> None:
    # Cross-namespace checks the per-file validator cannot see: the synthetic resource name and the
    # typed accessor are both global symbols, so two namespaces must never collapse to the same one,
    # and no accessor may be a reserved keyword on either platform (it becomes a Kotlin val / Swift case).
    seen_res = {}
    seen_accessor = {}
    for namespace, key, _entry in entries:
        origin = f"{namespace}:{key}"
        name = res_name(namespace, key)
        if name in seen_res:
            raise ValueError(f"duplicate resource name {name!r}: {seen_res[name]} and {origin}")
        seen_res[name] = origin
        accessor = l10n_accessor(namespace, key)
        if accessor in seen_accessor:
            raise ValueError(f"duplicate accessor {accessor!r}: {seen_accessor[accessor]} and {origin}")
        seen_accessor[accessor] = origin
        if accessor in KOTLIN_KEYWORDS or accessor in SWIFT_KEYWORDS:
            raise ValueError(f"accessor {accessor!r} ({origin}) is a reserved Kotlin/Swift keyword")


def _collect_entries(repo_root: Path):
    # Returns an ordered list of (namespace, key, entry) across all i18n/*.json sources.
    src_dir = repo_root / "i18n"
    entries = []
    for path in sorted(src_dir.glob("*.json")):
        namespace = path.stem
        data = load_namespace(path)
        validate_namespace(namespace, data, path)
        for key, entry in data["keys"].items():
            entries.append((namespace, key, entry))
    _validate_global(entries)
    return entries


def _emit_strings_xml(entries, lang: str) -> str:
    lines = ['<?xml version="1.0" encoding="utf-8"?>', f"<!-- {GENERATED_HEADER} -->", "<resources>"]
    for namespace, key, entry in entries:
        if lang not in entry["values"]:
            continue
        value = _finalize_value(entry["values"][lang], xml_escape, entry, "android")
        lines.append(f'    <string name="{res_name(namespace, key)}">{value}</string>')
    lines.append("</resources>")
    return "\n".join(lines) + "\n"


def _emit_string_key(entries) -> str:
    lines = [
        f"// {GENERATED_HEADER}",
        "package com.siansiansu.taigikeyboard.i18n.generated",
        "",
        "import androidx.annotation.StringRes",
        "import com.siansiansu.taigikeyboard.R",
        "",
        "/** Typed key for every i18n string. [resId] points at the Hanji default in res/values/strings_i18n.xml. */",
        "enum class StringKey(",
        "    @StringRes val resId: Int,",
        ") {",
    ]
    for namespace, key, _entry in entries:
        lines.append(f"    {string_key_const(namespace, key)}(R.string.{res_name(namespace, key)}),")
    lines.append("}")
    return "\n".join(lines) + "\n"


def _emit_taigi_map(entries) -> str:
    lines = [
        f"// {GENERATED_HEADER}",
        "package com.siansiansu.taigikeyboard.i18n.generated",
        "",
        "import com.siansiansu.taigikeyboard.i18n.DisplayLanguage",
        "",
        "/**",
        " * TL/POJ string overrides (the GeneratedMap resolution path — these languages have no OS locale).",
        " * Empty entries fall back to the Hanji default; later phases (P3b TL / P3c POJ) populate them.",
        " */",
        "object GeneratedTaigiStrings {",
    ]
    for lang in GENERATED_MAP_LANGUAGES:
        pairs = [(namespace, key, entry) for namespace, key, entry in entries if lang in entry["values"]]
        if pairs:
            lines.append(f"    private val {lang}: Map<StringKey, String> =")
            lines.append("        mapOf(")
            for namespace, key, entry in pairs:
                value = _finalize_value(entry["values"][lang], kotlin_escape, entry, "android")
                lines.append(f'            StringKey.{string_key_const(namespace, key)} to "{value}",')
            lines.append("        )")
        else:
            lines.append(f"    private val {lang}: Map<StringKey, String> = emptyMap()")
    lines.extend(
        [
            "",
            "    fun lookup(",
            "        language: DisplayLanguage,",
            "        key: StringKey,",
            "    ): String? =",
            "        when (language) {",
            "            DisplayLanguage.TAILO -> tailo[key]",
            "            DisplayLanguage.POJ -> poj[key]",
            "            else -> null",
            "        }",
            "}",
        ]
    )
    return "\n".join(lines) + "\n"


def _emit_pseudo_map(entries) -> str:
    lines = [
        f"// {GENERATED_HEADER}",
        "package com.siansiansu.taigikeyboard.i18n.generated",
        "",
        "/** Debug-only pseudo-locale strings (length-inflated layout/clipping probe). Never shown in release. */",
        "object GeneratedPseudoStrings {",
        "    private val map: Map<StringKey, String> =",
        "        mapOf(",
    ]
    for namespace, key, entry in entries:
        # Pseudo runs on the named text first (keeps {placeholders} verbatim); _finalize_value then
        # converts to positional and kotlin-escapes — so `%N$d` is neither accented nor left unescaped.
        value = _finalize_value(pseudo(entry["values"][BASE_LANGUAGE]), kotlin_escape, entry, "android")
        lines.append(f'            StringKey.{string_key_const(namespace, key)} to "{value}",')
    lines.extend(
        [
            "        )",
            "",
            "    fun lookup(key: StringKey): String? = map[key]",
            "}",
        ]
    )
    return "\n".join(lines) + "\n"


def _emit_l10n(entries) -> str:
    lines = [
        f"// {GENERATED_HEADER}",
        "package com.siansiansu.taigikeyboard.i18n.generated",
        "",
        "import androidx.compose.runtime.Composable",
        "import com.siansiansu.taigikeyboard.i18n.stringRes",
        "",
        "/** Typed Compose accessors — one per plain i18n key, resolved under the active display language. */",
        "object L10n {",
    ]
    for namespace, key, entry in entries:
        # Format keys get a typed StringResolver.<accessor>(args) function instead (StringResolverFormats.kt);
        # a plain String getter would leak the raw "%1$d" template and invite mis-use.
        if _placeholder_names_in_order(entry["values"][BASE_LANGUAGE]):
            continue
        accessor = l10n_accessor(namespace, key)
        const = string_key_const(namespace, key)
        lines.append(f"    val {accessor}: String")
        lines.append(f"        @Composable get() = stringRes(StringKey.{const})")
    lines.append("}")
    return "\n".join(lines) + "\n"


def _emit_string_resolver_formats(entries) -> str:
    # Typed non-Compose format accessors: one extension fn per format key, args in canonical
    # (base-text first-appearance) order. Callers resolve outside a Composition (coroutine lambdas,
    # Activity callbacks); formatString() is the hand-written helper in StringResolver.kt.
    fmt_entries = [
        (namespace, key, entry)
        for namespace, key, entry in entries
        if _placeholder_names_in_order(entry["values"][BASE_LANGUAGE])
    ]
    lines = [
        f"// {GENERATED_HEADER}",
        "package com.siansiansu.taigikeyboard.i18n.generated",
        "",
    ]
    if not fmt_entries:
        lines.append("// No format-arg keys are currently authored.")
        return "\n".join(lines) + "\n"
    lines.extend(
        [
            "import com.siansiansu.taigikeyboard.i18n.StringResolver",
            "import com.siansiansu.taigikeyboard.i18n.formatString",
            "",
            "// Typed format accessors for placeholder-bearing keys (the raw \"%1\\$d\" template never reaches a call site).",
        ]
    )
    for namespace, key, entry in fmt_entries:
        order = _placeholder_names_in_order(entry["values"][BASE_LANGUAGE])
        declared = entry["placeholders"]
        params = ", ".join(f"{name}: {PLACEHOLDER_TYPES[declared[name]]['android']['param']}" for name in order)
        args = ", ".join(order)
        accessor = l10n_accessor(namespace, key)
        const = string_key_const(namespace, key)
        lines.append("")
        lines.append(f"fun StringResolver.{accessor}({params}): String =")
        lines.append(f"    formatString(StringKey.{const}, {args})")
    return "\n".join(lines) + "\n"


# --- iOS emitters -----------------------------------------------------------


def _ios_format_arg(ptype: str, name: str) -> str:
    cast = PLACEHOLDER_TYPES[ptype]["ios"]["cast"]
    return f"{cast}({name})" if cast else name


def _emit_xcstrings(entries) -> str:
    # iOS String Catalog. Keyed by the synthetic res_name (shared with the Android R.string name, so
    # one naming function owns both platforms). Each authored language becomes a localization keyed by
    # its BCP-47 tag; Xcode compiles each into a per-tag .lproj (incl. the private-use TL/POJ tags).
    # sort_keys makes the committed catalog byte-stable for `make i18n-check` and aligns the key order
    # with Xcode's own alphabetical sort (comment < extractionState < localizations, state < value).
    strings = {}
    for namespace, key, entry in entries:
        localizations = {}
        for lang, text in entry["values"].items():
            value = _finalize_value(text, _json_identity, entry, "ios")
            localizations[LANG_TO_BCP47[lang]] = {"stringUnit": {"state": "translated", "value": value}}
        unit = {"extractionState": "manual", "localizations": localizations}
        comment = entry.get("comment")
        if comment:
            unit["comment"] = comment
        strings[res_name(namespace, key)] = unit
    catalog = {"sourceLanguage": XCSTRINGS_SOURCE_LANGUAGE, "strings": strings, "version": "1.0"}
    return json.dumps(catalog, indent=2, ensure_ascii=False, sort_keys=True) + "\n"


def _emit_ios_string_key(entries) -> str:
    lines = [
        f"// {GENERATED_HEADER}",
        "",
        "/// Typed key for every iOS i18n string. The raw value is the String Catalog key.",
        "enum StringKey: String {",
    ]
    for namespace, key, _entry in entries:
        lines.append(f'    case {l10n_accessor(namespace, key)} = "{res_name(namespace, key)}"')
    lines.append("}")
    return "\n".join(lines) + "\n"


def _emit_ios_pseudo(entries) -> str:
    # Debug-only length-inflated layout probe. Wrapped in #if DEBUG so neither the strings nor the
    # lookup exist in a release binary (the resolver's pseudo branch is likewise DEBUG-gated).
    lines = [
        f"// {GENERATED_HEADER}",
        "",
        "#if DEBUG",
        "import Foundation",
        "",
        "/// Debug-only pseudo-locale strings (length-inflated layout/clipping probe). Never shipped.",
        "enum GeneratedPseudoStrings {",
        "    private static let map: [StringKey: String] = [",
    ]
    for namespace, key, entry in entries:
        # Pseudo runs on the named text first (keeps {placeholders} verbatim); _finalize_value then
        # converts to positional + swift-escapes, so `%N$lld` is neither accented nor mis-escaped.
        value = _finalize_value(pseudo(entry["values"][BASE_LANGUAGE]), swift_escape, entry, "ios")
        lines.append(f'        .{l10n_accessor(namespace, key)}: "{value}",')
    lines.extend(
        [
            "    ]",
            "",
            "    static func lookup(_ key: StringKey) -> String? { map[key] }",
            "}",
            "#endif",
        ]
    )
    return "\n".join(lines) + "\n"


def _emit_ios_formats(entries) -> str:
    # Typed format accessors on StringResolver — one per placeholder-bearing key, args in canonical
    # (base-text first-appearance) order, each cast to match the %lld spec. The raw template never
    # reaches a call site; `format(_:_:)` is the hand-written variadic helper in StringResolver.swift.
    fmt_entries = [
        (namespace, key, entry)
        for namespace, key, entry in entries
        if _placeholder_names_in_order(entry["values"][BASE_LANGUAGE])
    ]
    lines = [f"// {GENERATED_HEADER}", ""]
    if not fmt_entries:
        lines.append("// No format-arg keys are currently authored.")
        return "\n".join(lines) + "\n"
    lines.extend(["import Foundation", "", "extension StringResolver {"])
    for index, (namespace, key, entry) in enumerate(fmt_entries):
        order = _placeholder_names_in_order(entry["values"][BASE_LANGUAGE])
        declared = entry["placeholders"]
        params = ", ".join(f"{name}: {PLACEHOLDER_TYPES[declared[name]]['ios']['param']}" for name in order)
        args = ", ".join(_ios_format_arg(declared[name], name) for name in order)
        accessor = l10n_accessor(namespace, key)
        if index:
            lines.append("")
        lines.append(f"    func {accessor}({params}) -> String {{")
        lines.append(f"        format(.{accessor}, {args})")
        lines.append("    }")
    lines.append("}")
    return "\n".join(lines) + "\n"


def build_outputs(repo_root: Path) -> dict:
    all_entries = _collect_entries(repo_root)
    # Android artifacts cover only android-scoped keys (D5 scope filtering); an iOS-only key
    # must not leak into the Android resource set.
    entries = [item for item in all_entries if "android" in item[2]["scope"]["platforms"]]

    outputs = {}
    # Native resource sets: always emit the base (Hanji) default; emit en/ja only once a key
    # carries that value, so authoring a language later just works (no silent drop).
    for lang, res_dir in NATIVE_RESOURCE_DIRS.items():
        has_value = any(lang in entry["values"] for _ns, _key, entry in entries)
        if lang == BASE_LANGUAGE or has_value:
            outputs[f"{ANDROID_RES_ROOT}/{res_dir}/strings_i18n.xml"] = _emit_strings_xml(entries, lang)
    outputs[f"{GEN_PKG_DIR}/StringKey.kt"] = _emit_string_key(entries)
    outputs[f"{GEN_PKG_DIR}/GeneratedTaigiStrings.kt"] = _emit_taigi_map(entries)
    outputs[f"{GEN_PKG_DIR}/GeneratedPseudoStrings.kt"] = _emit_pseudo_map(entries)
    outputs[f"{GEN_PKG_DIR}/L10n.kt"] = _emit_l10n(entries)
    outputs[f"{GEN_PKG_DIR}/StringResolverFormats.kt"] = _emit_string_resolver_formats(entries)

    # iOS artifacts cover only ios-scoped keys. The String Catalog holds all 5 languages and is the
    # single resolution path — the .lproj it compiles to works for every tag (no Native/GeneratedMap
    # split; that is Android-only). Pseudo is a Swift map because it is not a CFBundleLocalization.
    ios_entries = [item for item in all_entries if "ios" in item[2]["scope"]["platforms"]]
    outputs[IOS_XCSTRINGS] = _emit_xcstrings(ios_entries)
    outputs[f"{IOS_GEN_DIR}/StringKey.swift"] = _emit_ios_string_key(ios_entries)
    outputs[f"{IOS_GEN_DIR}/GeneratedPseudoStrings.swift"] = _emit_ios_pseudo(ios_entries)
    outputs[f"{IOS_GEN_DIR}/StringResolverFormats.swift"] = _emit_ios_formats(ios_entries)
    return outputs
