[package]
name = "cli"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false

[lints]
workspace = true

[[bin]]
name = "cli"
path = "src/main.rs"

[dependencies]
phonetics = { workspace = true }
clap = { workspace = true }
anyhow = { workspace = true }
