// App version-history changelog. Body text is language-invariant English (synced from
// changelog/<version>.md by the release-helper skill); excluded from i18n per the multi-language plan.
// 中文: App 版本歷史。內容為語言無關英文(release 時由 release-helper 從 changelog/<v>.md 同步),
// 中文: 依多語計畫排除於 i18n 之外。對應 Android content/VersionHistory.kt(僅對齊放置方式,內容各平台可不同)。

// 中文: 版本歷史資料來源。每筆 tuple = (版本號, 釋出日期, 變更條目)。
enum VersionHistory {
    static let entries: [(version: String, date: String, changes: [String])] = [
        ("3.6.3", "2026/06/20", [
            "New: typing a tone in TPS (注音) now shows only that tone's readings, matching TL / POJ; typing without a tone still shows all tones.",
            "New: TPS ninth tone (ˆ) can now be typed via the 9 digit key.",
            "Fixed: TPS words with the ir vowel after ts / tsh / s / j (自 / 事 / 故事) can now be typed.",
            "Fixed: typing a single initial in TL / POJ / TPS now surfaces common single characters again, not only longer words.",
            "Fixed: the emoji keyboard shows 4 rows again, and the emoji set is refreshed.",
            "Changed: 顯示羅馬字 (show romanization) now defaults off — turn it on in settings to keep the romanization you type as the first candidate.",
        ]),
        ("3.6.2", "2026/06/10", [
            "New: keyboard themes — a new 主題 tab lets you pick a look. Built-in themes come in three key styles (經典 filled / 框線 outlined / 簡潔 borderless) across several colours, including soft gradients (櫻花 / 金煌 / 海風 / 翠青 / 藤紫) and a dark 暗眠山貓 (Catppuccin) theme.",
            "New: create your own themes — a theme editor lets you set keyboard colours, key sizes, and key shadow, and save up to 5 custom themes.",
            "New: 顯示羅馬字 (show romanization) is now a toggle — when on, the romanization you type appears as the first candidate; turn it off to free up candidate-strip space.",
            "Fixed: imported or added custom-dictionary words now show up in the keyboard candidates again, in every input mode.",
            "Changed: the global keyboard font moved to 齒盤設定 (keyboard settings), separate from themes.",
        ]),
        ("3.6.1", "2026/06/06", [
            "New: frequency, next-word prediction, and the custom dictionary now work consistently across TL / POJ / TPS — learn or add a word in one input mode and it's found and ranked in the others.",
            "New: the same 漢字 with different readings (e.g. 重 tāng / tîng) now keeps separate frequency counts and ranks independently.",
            "New: in TL / POJ the romanization itself appears as the first candidate, so you can mix 漢羅 (Han-Lo) and commit the roman spelling in one tap — no need to switch to 文/A.",
            "Fixed: TL and POJ composing now shows exactly what you type — no automatic spelling conversion (teng stays teng).",
            "Fixed: TPS first-tone continuous input now segments correctly, with or without a separating space (ㄍㄠㄉㄞ → 交代), and some words hidden by auto-correct (雞胸 / 烏白 / 包袱) now appear as candidates.",
            "Fixed: whole-word continuous input now follows the dictionary's spacing / 輕聲 form (hoogua → 予我 hōo--guá), and next-word predictions learned via continuous input recall correctly and no longer appear twice.",
            "Fixed: a leading 輕聲 -- is now treated as normal text — only the syllable underlines while composing.",
            "Changed: the 詞頻 (frequency) list now shows each word's romanization with the 漢字, listing different readings separately.",
            "Changed: with auto-space on, attaching punctuation after a committed word now keeps the space after the punctuation (guá? not guá ?).",
            "Changed: the 姓名 (name) appendix dictionary source now defaults on.",
            "Changed: learned typing data (frequency, associations, custom words) is no longer included in iCloud / system backup — use the in-app 備份 (.taigi export) to move it to a new device.",
            "The first candidate again shows a filled keycap-colour background hint.",
        ]),
        ("3.6.0", "2026/05/31", [
            "New: each 教典 (MOE dictionary) subcollection is now its own toggle — turn individual 腔調 (accent) readings and the 姓名 (name) appendix on or off in the dictionary settings.",
            "New: multi-character words now carry 語音差異 (per-accent) readings, not just single characters.",
            "New: 詞庫增補檔案 — a new toggleable supplement source (~2,500 added words: 一府五院 / 菜市仔名 / 台臺 / 教典僻智識 / 數字時間日期 / 行政區).",
            "Changed: turning a dictionary source off now also removes its words from the keyboard's candidates, not just the dictionary browse tab.",
            "Fixed: typing an explicit tone in continuous input (e.g. tai5) now shows only that tone's readings; typing without a tone (tai) still shows all tones.",
            "Updated dictionary data.",
        ]),
        ("3.5.9", "2026/05/27", [
            "New: TPS (Bopomofo-Taiwanese) continuous input — type a whole TPS sentence and the keyboard segments it into candidates, same as TL / POJ.",
            "Fixed: toneless TPS strings whose syllables start with a medial (e.g. ㄉㄞㄨㄢ for 台灣) no longer return zero candidates.",
            "Fixed: TPS auto-correct no longer corrupts the next initial after a precomposed nasal coda (ㄉㄞㄨㄢㄉ … no longer becomes ㄉㄞㄨㄢㆵ …).",
            "Fixed: typing a lone Bopomofo initial like ㄉ now returns prefix-matched candidates instead of nothing.",
            "Fixed: continuous-input in POJ mode now stays POJ end-to-end — POJ phrases no longer fall back to TL display, and user-frequency learning is shared between POJ and TL.",
            "Fixed: short common words no longer dropped from the partial-prefix candidate list under load.",
            "Updated dictionary data.",
        ]),
        ("3.5.8", "2026/05/20", [
            "New: 連續輸入 — type a whole romanized phrase without committing each syllable; the keyboard segments the sentence and offers candidates per position. Tap to commit a segment, Enter to commit the raw text. Works with POJ / TL, the custom dictionary, user-frequency learning, and next-word prediction.",
            "Continuous-input candidates now show romanization and 漢字 on two lines.",
            "Replaced the 寄付支持 tab with a 關於開發者 page linking to the official website.",
            "Updated dictionary data.",
        ]),
        ("3.5.7", "2026/05/09", [
            "Fixed: LKK 漢羅文 mixed-script suggestions now correctly stay enabled after a settings reset.",
            "Renamed font display name 源樣黑體 → 源樣烏體 (matches official ButTaiwan naming).",
            "Updated dictionary data — regenerated POJ entries and corrected the Tab3 (Hanji) character range.",
            "Internal: end-to-end keystroke trace IDs for debug-build diagnostics.",
        ]),
        ("3.5.6", "2026/05/02", [
            "Internal: dictionary read path rewritten in Rust (no behavior change).",
        ]),
        ("3.5.5", "2026/05/02", [
            "Internal: next-word prediction engine rewritten in Rust (no behavior change).",
        ]),
        ("3.5.4", "2026/05/01", [
            "Internal: composing buffer engine rewritten in Rust (no behavior change).",
        ]),
        ("3.5.3", "2026/04/29", [
            "Internal: engine workspace cleanup, removed duplicate platform implementations (no behavior change).",
        ]),
        ("3.5.2", "2026/04/29", [
            "Internal: candidate ranking pipeline rewritten in Rust (no behavior change).",
        ]),
        ("3.5.1", "2026/04/28", [
            "Internal: phonetics conversion engine rewritten in Rust (no behavior change).",
        ]),
        ("3.5.0", "2026/04/25", [
            "Added 源樣明體 (serif) and 源樣烏體 (sans-serif) font options.",
            "Restored POJ candidates for words containing o͘ / ⁿ — about 21% of romanization queries had been missing matches.",
            "Fixed next-word candidate inserting raw TL form instead of POJ when typing in POJ mode.",
            "Fixed candidates occasionally remaining on screen after backspacing.",
            "Fixed emoji key not committing the active candidate before inserting the emoji.",
            "Fixed icon rendering on devices configured for non-Latin locales.",
            "Updated dictionary data.",
        ]),
        ("3.4.9", "2026/04/12", [
            "Reduced iOS app size by 73% (48 MB → 13 MB).",
            "Increased candidate display limit from 100 to 200.",
        ]),
        ("3.4.8", "2026/04/11", [
            "Fixed an issue where app storage grew excessively over time.",
        ]),
        ("3.4.7", "2026/04/05", [
            "Added globe key toggle to show or hide the keyboard switch key.",
            "Added custom dictionary enable/disable toggle.",
            "Added frequency recording toggle to enable or disable word frequency tracking.",
            "Added association recording toggle to enable or disable next-word prediction learning.",
            "Added CSV import/export for word frequency and association data.",
            "Rewrote feature guides with detailed input mode and romanization tutorials.",
            "Settings now show info buttons with feature descriptions.",
            "Dictionary settings now show source descriptions and links.",
            "Custom dictionary now shows CSV format example.",
            "Added Samsung keyboard quick-switch FAQ.",
            "Fixed TPS input incorrectly joining syllables after tone marks.",
            "Fixed certain POJ words with o͘ not showing candidates.",
            "Fixed duplicate candidates appearing in TPS mode.",
            "Fixed symbols like arrows incorrectly entering composition mode.",
        ]),
        ("3.4.6", "2026/03/24", [
            "Added in-keyboard settings panel accessible from toolbar.",
            "Added toolbar auto-collapse toggle in settings.",
            "TPS layout auto-corrects palatalized initials (ㄗ+ㄧ→ㄐ, ㄘ+ㄧ→ㄑ, etc.).",
            "TPS layout: digit keys accessible via long-press on row 1.",
            "Improved TPS syllable boundary detection for more accurate input.",
            "Fixed custom dictionary link not responding in dictionary settings.",
            "Enabled 台語工藝詞庫 and 學科術語辭典 by default.",
        ]),
        ("3.4.5", "2026/03/21", [
            "Added symbol selection panel for inserting special characters.",
            "Added dictionary search in the dictionary settings page.",
            "TPS layout auto-selects ㄇ/ㄫ initial and final forms based on context.",
            "Added dismiss keyboard button in toolbar.",
            "Improved number key input.",
            "Redesigned dictionary settings page with descriptions and categories.",
            "Improved symbol panel touch targets and fixed invisible characters.",
            "Fixed an issue where some candidates were missing from search results.",
            "Updated dictionary data.",
        ]),
        ("3.4.4", "2026/03/09", [
            "Fixed an issue where some words could not be found when typing.",
        ]),
        ("3.4.2", "2026/03/08", [
            "Added custom dictionary for adding your own words.",
            "Added diagnostic info for easier bug reporting.",
            "Fixed custom dictionary entries not appearing in search results.",
            "Fixed custom dictionary capitalization not matching other candidates.",
            "Fixed word-grouped POJ display conversion.",
        ]),
        ("3.4.1", "2026/02/26", [
            "Added tone diacritic hints above number keys.",
            "Added punctuation hints on MOE1/MOE2 layout keys.",
            "Added MOE Layout 1 and MOE Layout 2 keyboards.",
            "Added TPS (方音符號) keyboard layout.",
            "Added keyboard appearance customization settings.",
            "Added in-keyboard layout selection panel.",
            "Added STTI (學科術語辭典) dictionary source.",
            "Added phrase learning for continuous word selections.",
            "Improved continuous typing with word-grouped display.",
            "Fixed POJ and TL input mode separation.",
        ]),
        ("3.4.0", "2025/12/31", [
            "Adjusted the four-syllable input limit.",
            "Fixed an issue where o͘ did not trigger candidate search.",
        ]),
        ("3.3.9", "2025/12/30", [
            "Added an English keyboard.",
            "Added explanations for 'Typing History Dictionary' and 'Capitalization Toggle.'",
            "Added more symbols to the punctuation keyboard.",
            "Added quick toggle shortcuts to the candidate bar.",
            "Adopted Apple’s default UI components.",
            "Fixed an issue where candidates did not appear when typing tone 1 or 4 directly.",
            "Fixed an issue where capitalization was not working correctly.",
            "Fixed inconsistent font sizing across different iPhone models.",
            "Refactored the codebase for better cleanliness and maintainability.",
            "Updated the app logo.",
            "Upgraded KeyboardKit to v10.",
        ]),
        ("3.3.8", "2025/12/25", [
            "Refreshed the app interface and improved in-app explanations for better clarity.",
        ]),
    ]
}
